"use client";

import { useState } from "react";
import type { CalendarDay, CalendarDayType, CalendarException, Training } from "../../lib/types";

export function CalendarDayModal({ day, trainings, onClose, onOpenTraining, onSaveException }: { day: CalendarDay; trainings: Training[]; onClose: () => void; onOpenTraining: (training: Training) => void; onSaveException: (exception: Partial<CalendarException> & Pick<CalendarException, "data" | "tipo_giornata">) => Promise<void> }) {
  const [type, setType] = useState<CalendarDayType>(day.tipo_giornata);
  const [notes, setNotes] = useState(day.note ?? "");
  const [saving, setSaving] = useState(false);
  const label = new Intl.DateTimeFormat("it-IT", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date(`${day.data}T12:00:00`));
  async function save() { setSaving(true); await onSaveException({ data: day.data, tipo_giornata: type, note: notes || null }); setSaving(false); }
  return <div className="modal-backdrop" onClick={onClose}><div className="modal calendar-day-modal" onClick={event => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">Giornata calendario</span><h2>{label}</h2><div className="calendar-day-summary"><strong>{day.tipo_giornata}</strong>{day.match_day_relation && <span>{day.match_day_relation}</span>}{day.phase && <span>{day.phase.tipo}</span>}{day.richiamo_atletico && <span>Richiamo atletico</span>}</div>{day.match && <section className="calendar-match-detail"><h3>{day.match.tipo}</h3><p>{day.match.avversario || "Avversario non indicato"}{day.match.casa_trasferta ? ` · ${day.match.casa_trasferta}` : ""}</p></section>}<section className="day-training-list">{trainings.map(training => <button key={training.id} onClick={() => onOpenTraining(training)}><strong>{training.session_type || "Seduta portieri"}</strong><span>{training.content_status === "empty" ? "Seduta vuota programmata" : `${training.training_exercises.length} esercizi`}</span></button>)}</section><section className="calendar-exception-editor"><h3>Eccezione per questo giorno</h3><div className="field"><label>Tipo giornata</label><select value={type} onChange={event => setType(event.target.value as CalendarDayType)}>{["Allenamento", "Gara", "Amichevole", "Riposo", "Recupero", "Allenamento extra", "Annullato", "Altro"].map(item => <option key={item}>{item}</option>)}</select></div><div className="field"><label>Note</label><textarea rows={3} value={notes} onChange={event => setNotes(event.target.value)} /></div></section><div className="modal-actions"><button className="secondary" onClick={onClose}>Chiudi</button><button disabled={saving} onClick={save}>{saving ? "Salvataggio…" : "Salva eccezione"}</button></div></div></div>;
}
