import test from "node:test";
import assert from "node:assert/strict";
import { buildSessionProfile } from "../lib/session-planner/index.ts";
import { calculateRotationScore, getControlledVarietyPool, getExerciseCandidates, mdLoadFit, scoreExercise, selectSessionExercises, type ExerciseSelectionInput } from "../lib/session-planner/exercise-selection.ts";
import type { Exercise, PhysicalAssessmentDimension, ScoredExerciseCandidate, SessionBlock } from "../lib/types.ts";

const objective = { id:"fis13",codice:"FIS-013",macro_area:"Esplosività",obiettivo_fisico:"Spinta esplosiva",descrizione:"",priorita_portiere:"Alta",precampionato:"Alta",periodo_competitivo:"Alta",richiamo_mantenimento:"Media",recupero_rigenerazione:"Bassa",abbinamenti_tecnici:"",note_programmazione:"",attivo:true } as const;
const dimension = { id:"explosive",codice:"PHY-ESP",nome:"Esplosività",descrizione:"",ordine:1,attivo:true,objective_mappings:[{peso:1,physical_objective:objective}] } as PhysicalAssessmentDimension;
function exercise(id:string, patch:Partial<Exercise>={}): Exercise { return { id,codice:id,nome:`Esercizio ${id}`,category_id:1,subcategory_id:1,categoria:"Uscite alte e palle aeree",sottocategoria:"Uscite alte",fase:"Analitico",obiettivo:"Tecnica uscita",descrizione:"Qualità e precisione",durata_min:12,portieri_min:1,portieri_max:4,intensita:"Media",difficolta:2,materiale:"Palloni",variante:null,coaching_points:"",errori_comuni:"",schema_step_1:null,schema_step_2:null,schema_step_3:null,schema_step_4:null,schema_step_5:null,schema_step_6:null,scenario_gara:null,numero_azioni:null,schema_url:null,foto_url:null,attivo:true,physical_mappings:[{id:`m-${id}`,exercise_id:id,physical_objective_id:"fis13",ruolo:"Principale",peso:5,motivazione:null,attivo:true,physical_objective:objective}],...patch } as Exercise; }
function block(order:number, phase="Analitico"): SessionBlock { const kinds=["Attivazione","Tecnico principale","Disturbo / tecnico-fisico","Situazionale / Match Simulation"] as const; return {tipo_blocco:kinds[order-1],ordine:order,durata_target:20,fase_metodologica_preferita:phase,carico_target:"Medio",technical_category_id:1,physical_dimension_id:"explosive",notes:null,transition_minutes:2}; }
function input(exercises:Exercise[], overrides:Partial<ExerciseSelectionInput>={}): ExerciseSelectionInput { return {seed:"session-test",date:"2026-08-08",seasonId:"season",profile:buildSessionProfile({matchDayOffset:-4,duration:80}),goalkeeperCount:3,exercises,blocks:[block(1),block(2),block(3,"Disturbo"),block(4,"Situazionale")],technicalPrimaryId:1,technicalSecondaryId:2,physicalPrimaryId:"explosive",physicalDimensions:[dimension],history:[],...overrides}; }

test("caso A: Uscite alte + Esplosività a MD-4 privilegia coerenza tecnica e fisica",()=>{ const good=exercise("GOOD"); const weak=exercise("WEAK",{category_id:2,categoria:"Tecnica di piede",physical_mappings:[]}); const scored=[scoreExercise(good,block(2),input([good,weak]),0),scoreExercise(weak,block(2),input([good,weak]),1)]; assert.ok(scored[0].exercise_score>scored[1].exercise_score); assert.ok(scored[0].breakdown.physical_fit>=90); });
test("caso B: esercizio usato due giorni fa è fortemente penalizzato",()=>{ assert.ok(calculateRotationScore({last_used_date:"2026-08-06",days_since_last_use:2,uses_this_season:1,uses_last_30_days:1,uses_last_14_days:1,uses_last_7_days:1})<=5); });
test("caso C: un esercizio fresco può superare uno leggermente più coerente ma abusato",()=>{ const used=exercise("USED"); const fresh=exercise("FRESH",{category_id:2,categoria:"Parate ravvicinate"}); const context=input([used,fresh],{history:[{exercise_id:"USED",training_date:"2026-08-07",season_id:"season"},{exercise_id:"USED",training_date:"2026-08-04",season_id:"season"}]}); const a=scoreExercise(used,block(3,"Disturbo"),context,0); const b=scoreExercise(fresh,block(3,"Disturbo"),context,1); assert.ok(b.exercise_score>a.exercise_score); });
test("caso D: a MD-2 il carico metabolico eccessivo riceve malus",()=>{ const high=exercise("HIGH",{intensita:"Alta",descrizione:"Lavoro metabolico continuo ad alta densità"}); const light=exercise("LIGHT",{intensita:"Bassa-Media",descrizione:"Rapidità e precisione"}); const profile=buildSessionProfile({matchDayOffset:-2,duration:65}); assert.ok(mdLoadFit(light,block(3,"Disturbo"),profile)>mdLoadFit(high,block(3,"Disturbo"),profile)); });
test("caso E: con tre portieri un esercizio con minimo quattro è escluso",()=>{ const item=exercise("FOUR",{portieri_min:4,portieri_max:6}); assert.equal(getExerciseCandidates(input([item]),block(2),0).length,0); });
test("caso F: candidati 91 e 90.7 entrano entrambi nel pool controllato",()=>{ const base={exercise:exercise("A"),breakdown:{technical_fit:0,physical_fit:0,methodological_fit:0,rotation_score:0,md_load_fit:0,practical_fit:0},group_weakness_bonus:0,similarity_penalty:0,fallback_level:0,usage:{last_used_date:null,days_since_last_use:null,uses_this_season:0,uses_last_30_days:0,uses_last_14_days:0,uses_last_7_days:0},reasons:[],penalties:[]} as ScoredExerciseCandidate; assert.equal(getControlledVarietyPool([{...base,exercise_score:91},{...base,exercise:exercise("B"),exercise_score:90.7}]).length,2); });
test("caso G: nel blocco D un Match Simulation coerente è favorito",()=>{ const match=exercise("MATCH",{category_id:9,categoria:"Match Simulation",fase:"Situazionale complesso",scenario_gara:"Cross, seconda palla e decision making"}); const generic=exercise("GEN",{fase:"Situazionale"}); const context=input([match,generic],{technicalPrimaryId:1}); assert.ok(scoreExercise(match,block(4,"Situazionale"),context,0).exercise_score>scoreExercise(generic,block(4,"Situazionale"),context,0).exercise_score); });
test("caso H: senza candidato perfetto applica fallback senza crash",()=>{ const fallback=exercise("FALLBACK",{category_id:3,categoria:"Tema complementare",fase:"Scenario aperto"}); const result=selectSessionExercises(input([fallback],{blocks:[block(2)]})); assert.equal(result.selections.length,1); assert.ok(result.selections[0].fallback_level>=2); });
test("caso I: la generazione funziona senza valutazioni dei portieri",()=>{ const items=[exercise("ONE"),exercise("TWO",{fase:"Disturbo"}),exercise("THREE",{categoria:"Match Simulation",category_id:9,fase:"Situazionale complesso"})]; const result=selectSessionExercises(input(items)); assert.ok(result.selections.length>=3); assert.equal(new Set(result.selections.map(item=>item.exercise.id)).size,result.selections.length); });
