import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import type { Exercise } from "../lib/types.ts";
import { getFieldModeIndex, groupSessionExercises, variantsForGoalkeeper, type SessionDisplayExercise } from "../lib/session-visualization.ts";

function exercise(id:string,patch:Partial<Exercise>={}):Exercise{return{id,codice:id,nome:`Esercizio ${id}`,category_id:1,subcategory_id:1,categoria:"Tecnica",sottocategoria:"Presa alta",fase:"Analitico",obiettivo:"Obiettivo",descrizione:"Descrizione",durata_min:10,portieri_min:1,portieri_max:4,intensita:"Media",difficolta:2,materiale:"Palloni",variante:null,coaching_points:"Appoggio corto; testa sulla palla",errori_comuni:"",schema_step_1:null,schema_step_2:null,schema_step_3:null,schema_step_4:null,schema_step_5:null,schema_step_6:null,scenario_gara:null,numero_azioni:null,attivo:true,...patch};}
function item(id:string,blockOrder:number,blockPosition=0,patch:Partial<SessionDisplayExercise>={}):SessionDisplayExercise{return{id,exercise:exercise(id),plannedDuration:10,blockOrder,blockPosition,locked:false,reasons:[],variants:[],...patch};}

test("caso A: quattro esercizi compaiono nei rispettivi quattro blocchi",()=>{const items=[1,2,3,4].map(order=>item(`E${order}`,order));for(let order=1;order<=4;order++)assert.equal(groupSessionExercises(items,order)[0].id,`E${order}`);});
test("caso B: due esercizi nello stesso blocco rispettano la posizione",()=>{const items=[item("E2",2,1),item("E1",2,0)];assert.deepEqual(groupSessionExercises(items,2).map(value=>value.id),["E1","E2"]);});
test("caso E: la card espone l’azione Apri esercizio",()=>{const source=readFileSync(new URL("../app/components/session-exercise-card.tsx",import.meta.url),"utf8");assert.match(source,/Apri esercizio/);assert.match(source,/props\.onOpen/);});
test("caso F: Match Simulation mantiene scenario e numero azioni",()=>{const value=exercise("MS",{categoria:"Match Simulation",scenario_gara:"Cross e seconda palla",numero_azioni:"6"});assert.equal(value.scenario_gara,"Cross e seconda palla");assert.equal(value.numero_azioni,"6");});
test("caso G: più obiettivi fisici restano disponibili nella scheda reale",()=>{const mappings=[{id:"1"},{id:"2"},{id:"3"}] as Exercise["physical_mappings"];assert.equal(exercise("E",{physical_mappings:mappings}).physical_mappings?.length,3);});
test("caso H: variante individuale appare solo per il portiere interessato",()=>{const variants=[{goalkeeper_id:"g1",tipo:"tecnica",variante_individuale:"Ridurre distanza",motivazione:null,priority_source:null},{goalkeeper_id:"g2",tipo:"tecnica",variante_individuale:"Aumentare distanza",motivazione:null,priority_source:null}];assert.deepEqual(variantsForGoalkeeper(variants,"g1").map(value=>value.variante_individuale),["Ridurre distanza"]);});
test("caso I: modalità campo rispetta i limiti precedente e successivo",()=>{assert.equal(getFieldModeIndex(0,-1,5),0);assert.equal(getFieldModeIndex(0,1,5),1);assert.equal(getFieldModeIndex(4,1,5),4);});
test("caso J: layout smartphone impedisce overflow della card",()=>{const css=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8");assert.match(css,/@media \(max-width:640px\)[\s\S]*\.session-exercise-card\{grid-template-columns:1fr;max-width:100%;overflow:hidden\}/);});
test("caso K: su mobile l'espansione degli altri blocchi non viene azzerata a ogni render",()=>{const source=readFileSync(new URL("../app/keeper-app.tsx",import.meta.url),"utf8");assert.match(source,/const blocks=useMemo\(\(\)=>\[\.\.\.\(training\.training_blocks\?\?\[\]\)\]\.sort\(\(a,b\)=>a\.ordine-b\.ordine\),\[training\.training_blocks\]\)/);assert.match(source,/setExpanded\(current=>\(\{\.\.\.current,\[block\.ordine\]:!isOpen\}\)\)/);});
