import test from"node:test";import assert from"node:assert/strict";import{buildIndividualVariantSuggestions,calculateSessionQuality,getReplacementCandidates,regenerateBlock,regenerateSession,scoreManualExercise}from"../lib/session-planner/index.ts";import{buildSessionProfile}from"../lib/session-planner/index.ts";import type{EditableExerciseSelection,EditableGeneratedSession,Exercise,Goalkeeper,SessionBlock}from"../lib/types.ts";
function ex(id:string,patch:Partial<Exercise>={}):Exercise{return{id,codice:id,nome:id,category_id:1,subcategory_id:Number(id.replace(/\D/g,""))||1,categoria:"Uscite alte",sottocategoria:"Uscite alte",fase:"Analitico",obiettivo:"Uscite",descrizione:"Precisione",durata_min:15,portieri_min:1,portieri_max:4,intensita:"Media",difficolta:2,materiale:"Palloni",variante:null,coaching_points:"",errori_comuni:"",schema_step_1:null,schema_step_2:null,schema_step_3:null,schema_step_4:null,schema_step_5:null,schema_step_6:null,scenario_gara:null,numero_azioni:null,attivo:true,physical_mappings:[],...patch}as Exercise}
const kinds=["Attivazione","Tecnico principale","Disturbo / tecnico-fisico","Situazionale / Match Simulation"]as const;function block(n:number):SessionBlock{return{tipo_blocco:kinds[n-1],ordine:n,durata_target:n===1?15:20,fase_metodologica_preferita:n===3?"Disturbo":n===4?"Situazionale":"Analitico",carico_target:"Medio",technical_category_id:1,physical_dimension_id:null,notes:null,transition_minutes:2}}
function sel(e:Exercise,order:number,locked=false,score=80):EditableExerciseSelection{return{exercise:e,exercise_score:score,breakdown:{technical_fit:score,physical_fit:score,methodological_fit:score,rotation_score:score,md_load_fit:score,practical_fit:score},group_weakness_bonus:0,similarity_penalty:0,fallback_level:0,usage:{last_used_date:null,days_since_last_use:null,uses_this_season:0,uses_last_30_days:0,uses_last_14_days:0,uses_last_7_days:0},reasons:[],penalties:[],block_order:order,block_position:0,planned_duration_minutes:order===1?13:18,individual_variant_suggestion:null,locked,source:"generated",variants:[]}}
function result(items:EditableExerciseSelection[]):EditableGeneratedSession{return{seed:"s",selections:items,debug:{},net_minutes:items.reduce((a,b)=>a+b.planned_duration_minutes,0),transition_minutes:8,total_minutes:items.reduce((a,b)=>a+b.planned_duration_minutes,0)+8}}
function context(exercises:Exercise[]):any{return{seed:"s",date:"2026-08-08",seasonId:"season",profile:buildSessionProfile({matchDayOffset:-4,duration:75}),goalkeeperCount:3,exercises,blocks:[1,2,3,4].map(block),technicalPrimaryId:1,technicalSecondaryId:2,physicalPrimaryId:null,physicalDimensions:[],history:[]}}
test("caso A: rigenerazione seduta preserva due esercizi bloccati",()=>{const items=[sel(ex("E1"),1,true),sel(ex("E2",{fase:"Analitico"}),2),sel(ex("E3",{fase:"Disturbo"}),3),sel(ex("E4",{fase:"Situazionale"}),4,true)];const next=regenerateSession(context([...items.map(x=>x.exercise),ex("N1"),ex("N2",{fase:"Disturbo"}),ex("N3",{fase:"Situazionale"})]),result(items),1);assert.ok(next.selections.some(x=>x.exercise.id==="E1"&&x.locked));assert.ok(next.selections.some(x=>x.exercise.id==="E4"&&x.locked));});
test("caso B: alternative sono ordinate per ranking",()=>{const target=sel(ex("T"),2);const alt1=ex("A1"),alt2=ex("A2",{category_id:2});const ranked=getReplacementCandidates(context([target.exercise,alt1,alt2]),result([target]),target);assert.ok(ranked.every((x,i)=>i===0||ranked[i-1].exercise_score>=x.exercise_score));});
test("caso C: inserimento manuale incoerente è consentito e valutabile",()=>{const target=sel(ex("T"),2);const manual=ex("M",{category_id:9,categoria:"Tema libero",fase:"Scenario aperto",intensita:"Alta"});const scored=scoreManualExercise(context([manual]),result([target]),manual,2);assert.ok(scored.exercise_score>=0);assert.ok(scored.exercise_score<70);});
test("caso D: rimozione esercizio ricalcola indice",()=>{const a=sel(ex("A"),1),b=sel(ex("B"),2);const q1=calculateSessionQuality({selections:[a,b],blocks:[1,2,3,4].map(block),durationTarget:75,goalkeeperCount:3,technicalPrimaryId:1,technicalSecondaryId:null});const q2=calculateSessionQuality({selections:[a],blocks:[1,2,3,4].map(block),durationTarget:75,goalkeeperCount:3,technicalPrimaryId:1,technicalSecondaryId:null});assert.notEqual(q1.score,q2.score);});
test("caso E: esercizio pesante a MD-2 abbassa coerenza e genera warning",()=>{const heavy=sel(ex("H",{intensita:"Alta"}),3,false,35);heavy.breakdown.md_load_fit=15;const q=calculateSessionQuality({selections:[heavy],blocks:[1,2,3,4].map(block),durationTarget:65,goalkeeperCount:3,technicalPrimaryId:1,technicalSecondaryId:null});assert.ok(q.components.md_load<30);assert.ok(q.validation.some(x=>x.code==="load"&&x.level==="warning"));});
test("caso F: variante pertinente viene proposta",()=>{const g={id:"g",nome:"Marco",cognome:"Rossi",attivo:true,assessments:[{id:"a",data_valutazione:"2026-08-01",items:[{tipo:"Tecnica",exercise_category_id:1,score:4.3}]}]}as Goalkeeper;assert.equal(buildIndividualVariantSuggestions(sel(ex("E"),2),[g]).length,1);});
test("caso G: carenza non pertinente non crea variante",()=>{const g={id:"g",nome:"Marco",cognome:"Rossi",attivo:true,assessments:[{id:"a",data_valutazione:"2026-08-01",items:[{tipo:"Tecnica",exercise_category_id:9,score:4.1}]}]}as Goalkeeper;assert.equal(buildIndividualVariantSuggestions(sel(ex("E"),2),[g]).length,0);});
test("caso H: rigenera blocco preserva locked",()=>{const locked=sel(ex("L"),1,true);const next=regenerateBlock(context([locked.exercise,ex("N")]),result([locked]),1,2);assert.equal(next.selections[0].exercise.id,"L");});
test("caso I: 74 su 75 produce duration score molto alto",()=>{const item=sel(ex("D"),2);item.planned_duration_minutes=66;const q=calculateSessionQuality({selections:[item],blocks:[1,2,3,4].map(block),durationTarget:75,goalkeeperCount:3,technicalPrimaryId:1,technicalSecondaryId:null});assert.ok(q.components.duration>=95);});
test("caso J: duplicato produce warning",()=>{const e=ex("DUP");const q=calculateSessionQuality({selections:[sel(e,1),sel(e,2)],blocks:[1,2,3,4].map(block),durationTarget:75,goalkeeperCount:3,technicalPrimaryId:1,technicalSecondaryId:null});assert.ok(q.validation.some(x=>x.code==="duplicates"&&x.level==="warning"));});
