import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import type { Exercise, TacticalDiagram, TacticalDiagramAction } from "../lib/types.ts";
import { addDiagramAction, addDiagramElement, applySemanticTacticalComposition, chooseTacticalViewType, classifyTacticalFamily, createEmptyTacticalDiagram, duplicateDiagramElement, generateTacticalDiagram, getActionAnnotationLayout, getTacticalFieldGeometry, mirrorTacticalPoint, moveDiagramElement, normalizeGeneratedActions, normalizeTacticalDiagram, optimizeTacticalDiagramLayout, refineTacticalComposition, removeDiagramItem, resolveTacticalCompositionSide, resolveTacticalTemplate, TACTICAL_COMPOSITION_DISTANCES, TACTICAL_ZONES } from "../lib/tactical-diagram.ts";
import { computeTacticalViewBox, widenTacticalViewBox } from "../lib/tactical-renderer-framing.ts";
import { projectTacticalAssetDepthScale, projectTacticalBallDepthScale, projectTacticalPoint, projectTacticalScale, tacticalHorizontalExpansion, tacticalPerspectiveStrength } from "../lib/tactical-renderer-projection.ts";

const baseExercise: Exercise = {
  id: "exercise-1", codice: "GK-TEST-001", nome: "Presa frontale", category_id: 1, subcategory_id: 1,
  categoria: "Tecnica presa", sottocategoria: "Presa alta", fase: "Analitico", obiettivo: "Tecnica di presa",
  descrizione: "Il tiratore passa e conclude", durata_min: 10, portieri_min: 1, portieri_max: 2, intensita: "Media",
  difficolta: 2, materiale: "Palloni, coni", variante: null, coaching_points: "Mani avanti", errori_comuni: "Mani rigide",
  schema_step_1: "Passaggio del tiratore", schema_step_2: "Presa e recupero al centro", schema_step_3: null, schema_step_4: null,
  schema_step_5: null, schema_step_6: null, scenario_gara: null, numero_azioni: null, attivo: true,
};
const exercise = (patch: Partial<Exercise> = {}) => ({ ...baseExercise, ...patch });
const source = (file: string) => readFileSync(new URL(file, import.meta.url), "utf8");

test("1. generazione automatica produce un JSON completo", () => { const value = generateTacticalDiagram(baseExercise); assert.ok(value.elements.length); assert.ok(value.actions.length); assert.equal(value.version, 1); });
test("2. schema salvato è normalizzabile", () => assert.deepEqual(normalizeTacticalDiagram(generateTacticalDiagram(baseExercise))?.version, 1));
test("3. refresh conserva il JSON senza rigenerarlo", () => { const value = JSON.parse(JSON.stringify(generateTacticalDiagram(baseExercise))); assert.deepEqual(normalizeTacticalDiagram(value), value); });
test("4. drag limita le coordinate al canvas", () => { const value = addDiagramElement(createEmptyTacticalDiagram(), "goalkeeper"); const moved = moveDiagramElement(value, value.elements[0].id, 120, -8); assert.equal(moved.elements[0].x, 98); assert.equal(moved.elements[0].y, 2); });
test("5. touch usa Pointer Events", () => assert.match(source("../app/components/exercise-tactical-board.tsx"), /onPointerDown/));
test("6. frecce di precisione sono disponibili", () => assert.match(source("../app/components/tactical-diagram-editor.tsx"), /ArrowUp/));
test("7. keyboard arrows spostano l’elemento", () => assert.match(source("../app/components/tactical-diagram-editor.tsx"), /ArrowRight/));
test("8. duplicazione crea un id distinto", () => { const value = addDiagramElement(createEmptyTacticalDiagram(), "ball"); const next = duplicateDiagramElement(value, value.elements[0].id); assert.equal(next.elements.length, 2); assert.notEqual(next.elements[0].id, next.elements[1].id); });
test("9. eliminazione rimuove elemento e azioni collegate", () => { const value = addDiagramElement(createEmptyTacticalDiagram(), "player"); assert.equal(removeDiagramItem(value, value.elements[0].id).elements.length, 0); });
test("10. rotazione è una proprietà del modello", () => assert.equal(addDiagramElement(createEmptyTacticalDiagram(), "goalkeeper").elements[0].rotation, 0));
test("11. aggiunta pallone", () => assert.equal(addDiagramElement(createEmptyTacticalDiagram(), "ball").elements[0].type, "ball"));
test("12. aggiunta giocatore", () => assert.equal(addDiagramElement(createEmptyTacticalDiagram(), "player").elements[0].type, "player"));
test("13. passaggio", () => assert.equal(addDiagramAction(createEmptyTacticalDiagram(), "passaggio").actions[0].type, "passaggio"));
test("14. tiro", () => assert.equal(addDiagramAction(createEmptyTacticalDiagram(), "tiro").actions[0].type, "tiro"));
test("15. cross usa template laterale", () => assert.equal(resolveTacticalTemplate(exercise({ nome: "Cross da sinistra" })), "cross"));
test("16. tuffo usa template dedicato", () => assert.equal(resolveTacticalTemplate(exercise({ nome: "Tuffo laterale" })), "tuffo_laterale"));
test("17. sequenza numerata parte da uno", () => assert.equal(addDiagramAction(createEmptyTacticalDiagram(), "tiro").actions[0].sequence, 1));
test("18. undo è presente", () => assert.match(source("../app/components/tactical-diagram-editor.tsx"), /setCursor\(value => Math\.max/));
test("19. redo è presente", () => assert.match(source("../app/components/tactical-diagram-editor.tsx"), /setCursor\(value => Math\.min/));
test("20. reset/rigenerazione non salva immediatamente", () => assert.match(source("../app/components/tactical-diagram-editor.tsx"), /Rigenera/));
test("21. responsive usa viewBox e aspect ratio", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /viewBox="0 0 100 100"/); assert.match(board, /aspectRatio/); });
test("22. generazione massiva ha avanzamento", () => assert.match(source("../app/keeper-app.tsx"), /onProgress\(index \+ 1/));
test("23. generazione massiva non sovrascrive", () => assert.match(source("../app/keeper-app.tsx"), /\.is\("tactical_diagram", null\)/));
test("24. migration non modifica RLS", () => { const sql = source("../supabase/migrations/0027_exercise_tactical_diagrams.sql"); assert.doesNotMatch(sql, /create policy|drop policy|disable row level/i); });
test("25. generazione massiva è catalog-admin", () => assert.match(source("../app/keeper-app.tsx"), /!catalogAdmin/));
test("26. catalogo usa ExerciseTacticalBoard", () => assert.match(source("../app/components/exercise-card.tsx"), /ExerciseTacticalBoard/));
test("27. sedute usano ExerciseTacticalBoard", () => assert.match(source("../app/components/session-exercise-card.tsx"), /ExerciseTacticalBoard/));
test("coordinate del JSON sono percentuali", () => { const value: TacticalDiagram = generateTacticalDiagram(baseExercise); for (const item of value.elements) assert.ok(item.x >= 0 && item.x <= 100 && item.y >= 0 && item.y <= 100); });
test("il solo campo materiale non aggiunge coni", () => assert.equal(generateTacticalDiagram(baseExercise).elements.filter(item => item.type === "cone").length, 0));
test("regola tiratore assegna il ruolo senza duplicati", () => assert.equal(generateTacticalDiagram(exercise({ descrizione: "Il tiratore serve il tiratore che conclude", schema_step_1: "Il tiratore effettua il tiro" })).elements.filter(item => item.role?.toLowerCase() === "tiratore").length, 1));
test("cronologia drag mantiene il cursore entro le versioni disponibili", () => { const editor = source("../app/components/tactical-diagram-editor.tsx"); assert.match(editor, /Math\.min\(cursor, current\.length - 1\)/); assert.match(editor, /setCursor\(updated\.length - 1\)/); });
test("esercizio per tre portieri mostra un solo GK attivo", () => { const diagram = generateTacticalDiagram(exercise({ portieri_min: 3, portieri_max: 3 })); assert.equal(diagram.elements.filter(item => item.type === "goalkeeper").length, 1); });
test("secondo GK esplicitamente attivo mostra due goalkeeper", () => { const diagram = generateTacticalDiagram(exercise({ portieri_min: 3, portieri_max: 3, schema_step_2: "Il secondo portiere interviene sulla seconda conclusione" })); assert.equal(diagram.elements.filter(item => item.type === "goalkeeper").length, 2); });
test("sei coni elencati ma non usati non compaiono", () => { const diagram = generateTacticalDiagram(exercise({ materiale: "6 coni, palloni", descrizione: "Il servitore passa la palla al portiere", schema_step_1: "Presa frontale", schema_step_2: null })); assert.equal(diagram.elements.filter(item => item.type === "cone").length, 0); });
test("tiro laterale sposta e orienta il GK verso il lato palla", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tiro laterale da sinistra", descrizione: "Il tiratore conclude da sinistra" })); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); assert.ok(goalkeeper); assert.ok(goalkeeper.x < 50); assert.notEqual(goalkeeper.rotation, 0); });
test("1 contro 1 porta il GK in posizione avanzata", () => { const diagram = generateTacticalDiagram(exercise({ nome: "1 contro 1 frontale", descrizione: "L’attaccante conduce verso la porta" })); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); assert.ok(goalkeeper && goalkeeper.y < 65); });
test("cross posiziona il servitore largo", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Cross da sinistra", descrizione: "Il servitore effettua un cross" })); const servant = diagram.elements.find(item => item.role === "Servitore"); assert.ok(servant && servant.x < 20); });
test("badge di sequenza è calcolato sul percorso dell’azione", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /action-sequence-badge/); assert.match(board, /getActionAnnotationLayout/); assert.doesNotMatch(board, /cx=\{item\.endX\} cy=\{item\.endY\} r="3\.2"/); });
test("template reattività conserva i coni funzionali", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Reattività su stimolo", descrizione: "Reazione a stimolo visivo", materiale: "Palloni" })); assert.ok(diagram.elements.some(item => item.type === "cone")); });
test("auto-layout: tiratore, pallone e GK non risultano sovrapposti", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale", descrizione: "Il tiratore conclude centralmente e il GK esegue il tuffo" })); const actors = diagram.elements.filter(item => ["goalkeeper", "attacker", "ball"].includes(item.type)); for (let left = 0; left < actors.length; left += 1) for (let right = left + 1; right < actors.length; right += 1) assert.ok(Math.hypot(actors[left].x - actors[right].x, actors[left].y - actors[right].y) >= 5); });
test("auto-layout: badge sequenza evita GK e giocatori", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale", descrizione: "Il tiratore conclude e il GK esegue il tuffo" })); for (const action of diagram.actions) { const annotation = getActionAnnotationLayout(action, diagram.elements); for (const item of diagram.elements.filter(element => ["goalkeeper", "attacker", "player", "coach"].includes(element.type))) assert.ok(Math.hypot(annotation.badgeX - item.x, annotation.badgeY - item.y) > 4); } });
test("auto-layout: label Tiro resta vicina alla propria traiettoria", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale", descrizione: "Il tiratore conclude" })); const shot = diagram.actions.find(item => item.type === "tiro"); assert.ok(shot); const annotation = getActionAnnotationLayout(shot, diagram.elements); const midpoint = { x: (shot.startX + shot.endX) / 2, y: (shot.startY + shot.endY) / 2 }; assert.ok(Math.hypot(annotation.labelX - midpoint.x, annotation.labelY - midpoint.y) < 14); });
test("auto-layout: label Tuffo resta vicina alla traiettoria GK", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale", descrizione: "Il GK esegue il tuffo" })); const dive = diagram.actions.find(item => item.type === "tuffo"); assert.ok(dive); const annotation = getActionAnnotationLayout(dive, diagram.elements); assert.ok(Math.hypot(annotation.labelX - (dive.startX + dive.endX) / 2, annotation.labelY - (dive.startY + dive.endY) / 2) < 16); });
test("auto-layout: il tuffo parte dal bordo del GK senza duplicarlo", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale", descrizione: "Il GK esegue un tuffo" })); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); const dive = diagram.actions.find(item => item.type === "tuffo"); assert.ok(goalkeeper && dive); assert.equal(dive.fromElementId, goalkeeper.id); const distance = Math.hypot(dive.startX - goalkeeper.x, dive.startY - goalkeeper.y); assert.ok(distance >= 4 && distance <= 7); assert.equal(diagram.elements.filter(item => item.type === "goalkeeper").length, 1); });
test("auto-layout: il pallone non viene coperto dalle label", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale", descrizione: "Il tiratore conclude" })); const ball = diagram.elements.find(item => item.type === "ball"); assert.ok(ball); for (const action of diagram.actions) { const annotation = getActionAnnotationLayout(action, diagram.elements); assert.ok(Math.hypot(annotation.labelX - ball.x, annotation.labelY - ball.y) > 4); } });
test("auto-layout: cross da destra mantiene il servitore largo", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Cross da destra", descrizione: "Il servitore effettua il cross da destra" })); const servant = diagram.elements.find(item => item.role === "Servitore"); assert.ok(servant && servant.x > 80); });
test("auto-layout: uno schema semplice utilizza l’altezza disponibile", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Presa frontale", descrizione: "Il servitore passa al GK" })); const ys = diagram.elements.map(item => item.y); assert.ok(Math.max(...ys) - Math.min(...ys) > 30); });
test("auto-layout: schema complesso resta nella safe area", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Match Simulation seconda palla", descrizione: "Il tiratore conclude, l’appoggio serve la seconda palla, il secondo portiere interviene, usando coni, sagoma, ostacolo e porticina" })); for (const item of diagram.elements) { assert.ok(item.x >= 6 && item.x <= 94); assert.ok(item.y >= 6 && item.y <= 94); } for (const action of diagram.actions) { assert.ok(action.startX >= 6 && action.startX <= 94 && action.endX >= 6 && action.endX <= 94); assert.ok(action.startY >= 6 && action.startY <= 94 && action.endY >= 6 && action.endY <= 94); } });
test("auto-layout: porta di background e pallone leggibile rispettano la vista", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale", descrizione: "Il tiratore conclude" })); assert.equal(diagram.elements.some(item => item.type === "goal"), false); assert.ok((diagram.elements.find(item => item.type === "ball")?.scale ?? 0) >= 1.24); assert.match(source("../app/components/exercise-tactical-board.tsx"), /primary-goal-background/); });
test("auto-layout: uno schema manuale non viene modificato", () => { const diagram = generateTacticalDiagram(baseExercise); assert.equal(optimizeTacticalDiagramLayout(diagram, "manual"), diagram); assert.equal(optimizeTacticalDiagramLayout(diagram, "automatic_edited"), diagram); });
test("composition refinement: manual e automatic_edited restano identici",()=>{const diagram=generateTacticalDiagram(baseExercise,{refineComposition:false});assert.equal(refineTacticalComposition(diagram,"presa","manual"),diagram);assert.equal(refineTacticalComposition(diagram,"presa","automatic_edited"),diagram);});
test("composition refinement: preserva semantica e identità delle actions",()=>{const input=generateTacticalDiagram(exercise({nome:"Tuffo laterale",descrizione:"Il tiratore conclude e il portiere si tuffa"}),{refineComposition:false});const output=refineTacticalComposition(input,"tuffo_laterale");assert.deepEqual(output.actions.map(({id,type,sequence,fromElementId,toElementId})=>({id,type,sequence,fromElementId,toElementId})),input.actions.map(({id,type,sequence,fromElementId,toElementId})=>({id,type,sequence,fromElementId,toElementId})));assert.deepEqual(output.elements.map(({id,type,role})=>({id,type,role})),input.elements.map(({id,type,role})=>({id,type,role})));});
test("composition refinement: GK mantiene distanza dalla porta",()=>{for(const nome of ["Tuffo laterale","Uscita alta","Uscita bassa","Posizionamento porta"]){const diagram=generateTacticalDiagram(exercise({nome}));const gk=diagram.elements.find(item=>item.type==="goalkeeper");assert.ok(gk&&gk.y<=94-TACTICAL_COMPOSITION_DISTANCES.goalkeeperGoalLine);}});
test("composition refinement: cross usa la larghezza e 1vs1 avanza il GK",()=>{const cross=generateTacticalDiagram(exercise({nome:"Cross da sinistra",descrizione:"Il servitore effettua un cross"}));assert.ok((cross.elements.find(item=>item.role==="Servitore")?.x??50)<=10);const one=generateTacticalDiagram(exercise({nome:"1vs1",descrizione:"L’attaccante conduce verso la porta"}));assert.ok((one.elements.find(item=>item.type==="goalkeeper")?.y??100)<=57);});
test("composition refinement: pallone leggibile e separato dal proprietario",()=>{for(const patch of [{nome:"Tuffo laterale",descrizione:"Il tiratore conclude"},{nome:"Tecnica di piede",descrizione:"Il portiere passa all’appoggio"},{nome:"Cross da destra",descrizione:"Il servitore effettua il cross"}]){const diagram=generateTacticalDiagram(exercise(patch));const ball=diagram.elements.find(item=>item.type==="ball");const nearest=diagram.elements.filter(item=>["goalkeeper","attacker","player","coach"].includes(item.type)).sort((a,b)=>Math.hypot(a.x-(ball?.x??0),a.y-(ball?.y??0))-Math.hypot(b.x-(ball?.x??0),b.y-(ball?.y??0)))[0];assert.ok(ball&&nearest&&Math.hypot(nearest.x-ball.x,nearest.y-ball.y)>=TACTICAL_COMPOSITION_DISTANCES.playerBall-.2);}});
test("composition refinement: badge provano 25 50 75 percento e non si sovrappongono",()=>{const diagram=generateTacticalDiagram(exercise({nome:"Match Simulation seconda palla",descrizione:"Il tiratore conclude e l’appoggio serve la seconda palla"}));const occupied:Array<{x:number;y:number}>=[];for(const action of diagram.actions){const badge=getActionAnnotationLayout(action,diagram.elements,occupied);assert.ok(diagram.elements.every(item=>Math.hypot(item.x-badge.badgeX,item.y-badge.badgeY)>3.5));assert.ok(occupied.every(item=>Math.hypot(item.x-badge.badgeX,item.y-badge.badgeY)>5));occupied.push({x:badge.badgeX,y:badge.badgeY});}assert.match(source("../lib/tactical-diagram.ts"),/candidates\(\[\.25, \.5, \.75\]/);});
test("composition refinement: copre dieci tipologie reali",()=>{const names=["Tuffo laterale","Cross","Tecnica di piede","1vs1","Uscita alta","Uscita bassa","Doppio intervento combinazione","Seconda palla","Posizionamento porta","Match Simulation"];for(const nome of names){const diagram=generateTacticalDiagram(exercise({nome,descrizione:`Esercizio ${nome} con tiratore, servitore e pallone`}));assert.ok(diagram.elements.length>0&&diagram.actions.length>0);assert.ok(diagram.elements.every(item=>item.x>=6&&item.x<=94&&item.y>=6&&item.y<=94));}});
test("semantic composition: classifica le famiglie richieste",()=>{const cases:[string,string][]=[["Parata su tiro","SHOT_SAVE"],["Tuffo laterale","DIVE"],["Cross","CROSS"],["Uscita alta","HIGH_CLAIM"],["Uscita bassa","LOW_CLAIM"],["1 contro 1","ONE_V_ONE"],["Tecnica di piede","FOOTWORK"],["Doppio intervento","DOUBLE_SAVE"],["Seconda palla","SECOND_BALL"],["Posizionamento porta","POSITIONING"],["Reattività","REACTION"],["Match Simulation","MATCH_SIMULATION"]];for(const [nome,family] of cases)assert.equal(classifyTacticalFamily(exercise({nome,descrizione:nome})),family);});
test("semantic composition: mirroring conserva y e specchia x",()=>{assert.deepEqual(mirrorTacticalPoint({x:18,y:31},false),{x:18,y:31});assert.deepEqual(mirrorTacticalPoint({x:18,y:31},true),{x:82,y:31});assert.equal(resolveTacticalCompositionSide(exercise({nome:"Cross da destra"})),"right");});
test("semantic composition: GK usa base laterale e posizione avanzata",()=>{const dive=generateTacticalDiagram(exercise({nome:"Tuffo laterale"})),one=generateTacticalDiagram(exercise({nome:"1 contro 1"}));const diveGoalkeeper=dive.elements.find(item=>item.type==="goalkeeper");assert.equal(diveGoalkeeper?.y,TACTICAL_ZONES.GOALKEEPER_BASE.y);assert.ok((diveGoalkeeper?.x??50)>50);assert.equal(one.elements.find(item=>item.type==="goalkeeper")?.y,TACTICAL_ZONES.GOALKEEPER_ADVANCED.y);});
test("semantic composition: cross laterale è specchiato",()=>{const left=generateTacticalDiagram(exercise({nome:"Cross da sinistra"})),right=generateTacticalDiagram(exercise({nome:"Cross da destra"}));assert.equal(left.elements.find(item=>item.role==="Servitore")?.x,TACTICAL_ZONES.LEFT_SERVICE.x);assert.equal(right.elements.find(item=>item.role==="Servitore")?.x,TACTICAL_ZONES.RIGHT_SERVICE.x);});
test("semantic composition: doppio intervento separa le destinazioni",()=>{const diagram=generateTacticalDiagram(exercise({nome:"Doppio intervento combinazione",descrizione:"Doppio intervento con recupero"}));assert.ok(diagram.actions.length>=2);assert.ok(Math.hypot(diagram.actions[0].endX-diagram.actions[1].endX,diagram.actions[0].endY-diagram.actions[1].endY)>=18);});
test("semantic composition: seconda palla mantiene triangolo e almeno tre azioni distinte",()=>{const diagram=generateTacticalDiagram(exercise({nome:"Seconda palla",descrizione:"Il tiratore conclude e l’appoggio serve la seconda palla"}));const shooter=diagram.elements.find(item=>item.role==="Tiratore"),support=diagram.elements.find(item=>item.role==="Appoggio");assert.ok(shooter&&support&&Math.abs(shooter.x-support.x)>35);assert.ok(diagram.actions.length>=3);assert.ok(new Set(diagram.actions.map(item=>`${item.endX}:${item.endY}`)).size>=3);});
test("semantic composition: positioning collega palla, posizioni e recupero",()=>{const diagram=generateTacticalDiagram(exercise({nome:"Posizionamento porta da sinistra"}));const ball=diagram.elements.find(item=>item.type==="ball"),markers=diagram.elements.filter(item=>item.type==="marker");assert.ok(ball&&ball.x<25&&markers.length===2);assert.equal(diagram.actions[0].endX,markers[0].x);assert.deepEqual({x:diagram.actions[1].endX,y:diagram.actions[1].endY},TACTICAL_ZONES.RECOVERY_CENTER);});
test("semantic composition: collision refinement non distrugge gli attori principali",()=>{const raw=generateTacticalDiagram(exercise({nome:"Cross da sinistra"}),{refineComposition:false});const semantic=applySemanticTacticalComposition(raw,"CROSS","left");assert.equal(semantic.elements.find(item=>item.role==="Servitore")?.x,TACTICAL_ZONES.LEFT_SERVICE.x);assert.equal(semantic.elements.find(item=>item.type==="goalkeeper")?.y,TACTICAL_ZONES.GOALKEEPER_BASE.y);assert.equal(applySemanticTacticalComposition(raw,"CROSS","left","manual"),raw);});

test("rifinitura 1: porta principale allineata alla linea di fondo", () => { const field = getTacticalFieldGeometry("front_goal"); assert.equal(field.goalLineY, 94); assert.ok(field.goalDepthY < field.goalLineY); const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /className="goal-frame"/); assert.match(board, /field\.goalLineY/); });
test("rifinitura 2: area di porta parte dalla stessa linea di fondo", () => { const field = getTacticalFieldGeometry("penalty_area"); assert.equal(field.goalLineY, 94); assert.ok(field.goalAreaTop < field.goalLineY); const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /goalAreaLeft.*goalLineY.*goalAreaTop.*goalAreaRight.*goalLineY/); });
test("rifinitura 3: la porta regolamentare non è un elemento automatico duplicato", () => { const diagram = generateTacticalDiagram(baseExercise); assert.equal(diagram.elements.filter(item => item.type === "goal").length, 0); assert.match(source("../app/components/exercise-tactical-board.tsx"), /primary-goal-background/); });
test("rifinitura 4: tuffo ha origine dal bordo del GK", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale", descrizione: "Il portiere si tuffa" })); const dive = diagram.actions.find(item => item.type === "tuffo"); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); assert.ok(dive && goalkeeper); assert.equal(dive.fromElementId, goalkeeper.id); const distance = Math.hypot(dive.startX - goalkeeper.x, dive.startY - goalkeeper.y); assert.ok(distance >= 4 && distance <= 7); });
test("rifinitura 5: tiro ha origine dal pallone o dal tiratore", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Parata su tiro", descrizione: "Il tiratore conclude" })); const shot = diagram.actions.find(item => item.type === "tiro"); const ball = diagram.elements.find(item => item.type === "ball"); const shooter = diagram.elements.find(item => item.role === "Tiratore"); assert.ok(shot && ball && shooter); assert.ok(shot.fromElementId === ball.id || shot.fromElementId === shooter.id); assert.ok(Math.min(Math.hypot(shot.startX - ball.x, shot.startY - ball.y), Math.hypot(shot.startX - shooter.x, shot.startY - shooter.y)) < 3); });
test("rifinitura 6: due Tiro semanticamente duplicati diventano uno", () => { const shots: TacticalDiagramAction[] = [{ id: "shot-1", type: "tiro", startX: 40, startY: 30, endX: 50, endY: 70, sequence: 1, fromElementId: "ball", toElementId: "gk" }, { id: "shot-2", type: "tiro", startX: 42, startY: 32, endX: 51, endY: 69, sequence: 2, fromElementId: "ball", toElementId: "gk" }]; assert.equal(normalizeGeneratedActions(shots).length, 1); });
test("rifinitura 7: badge rispetta la zona di esclusione del GK", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale" })); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); assert.ok(goalkeeper); for (const item of diagram.actions) { const annotation = getActionAnnotationLayout(item, diagram.elements); assert.ok(Math.hypot(annotation.badgeX - goalkeeper.x, annotation.badgeY - goalkeeper.y) > 7); } });
test("rifinitura 8: label rispetta la zona di esclusione del GK", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale" })); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); assert.ok(goalkeeper); for (const item of diagram.actions) { const annotation = getActionAnnotationLayout(item, diagram.elements); assert.ok(Math.hypot(annotation.labelX - goalkeeper.x, annotation.labelY - goalkeeper.y) > 7); } });
test("rifinitura 9: label non copre il pallone", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Parata su tiro centrale" })); const ball = diagram.elements.find(item => item.type === "ball"); assert.ok(ball); for (const item of diagram.actions) { const annotation = getActionAnnotationLayout(item, diagram.elements); assert.ok(Math.hypot(annotation.labelX - ball.x, annotation.labelY - ball.y) > 5); } });
test("rifinitura 10: schema semplice usa spazio verticale e orizzontale", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Presa frontale", descrizione: "Il servitore passa al portiere" })); const xs = diagram.elements.map(item => item.x); const ys = diagram.elements.map(item => item.y); assert.ok(Math.max(...ys) - Math.min(...ys) > 30); assert.ok(Math.max(...xs) - Math.min(...xs) > 6); });
test("rifinitura 11: schema complesso resta nella safe area", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Match Simulation seconda palla", descrizione: "Tiratore, appoggio, secondo portiere, coni, sagoma, ostacolo e porticina" })); assert.ok(diagram.elements.every(item => item.x >= 6 && item.x <= 94 && item.y >= 6 && item.y <= 94)); assert.ok(diagram.actions.every(item => [item.startX, item.startY, item.endX, item.endY].every(value => value >= 6 && value <= 94))); });
test("rifinitura 12: cross usa la vista larga dell’area", () => assert.equal(chooseTacticalViewType(exercise({ nome: "Cross da destra" })), "penalty_area"));
test("rifinitura 13: 1vs1 usa una vista ravvicinata", () => assert.equal(chooseTacticalViewType(exercise({ nome: "1 contro 1 frontale" })), "front_goal"));
test("rifinitura 14: tecnica di piede usa metà campo", () => assert.equal(chooseTacticalViewType(exercise({ nome: "Tecnica di piede e costruzione" })), "half_pitch"));
test("rifinitura 15: manual resta identico per riferimento", () => { const diagram = generateTacticalDiagram(baseExercise); assert.equal(optimizeTacticalDiagramLayout(diagram, "manual"), diagram); });
test("rifinitura 16: automatic_edited resta identico per riferimento", () => { const diagram = generateTacticalDiagram(baseExercise); assert.equal(optimizeTacticalDiagramLayout(diagram, "automatic_edited"), diagram); });

test("rendering essenziale: le label azioni sono nascoste per default", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /showActionLabels = false/); assert.match(board, /showLabel && item\.label/); });
test("rendering essenziale: le preview non attivano label azioni", () => { const card = source("../app/components/exercise-card.tsx"); const session = source("../app/components/session-exercise-card.tsx"); assert.doesNotMatch(card, /showActionLabels/); assert.doesNotMatch(session, /showActionLabels/); });
test("rendering essenziale: badge numerici restano visibili", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /action-sequence-badge/); assert.match(board, />\{item\.sequence\}<\/text>/); });
test("rendering essenziale: GK e sole etichette brevi restano leggibili", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /shortLabel\.length <= 3/); const diagram = generateTacticalDiagram(baseExercise); assert.equal(diagram.elements.find(item => item.type === "goalkeeper")?.label, "GK"); });
test("rendering essenziale: dettaglio mostra la sequenza testuale esterna", () => { const card = source("../app/components/exercise-card.tsx"); assert.match(card, /manual-procedure/); assert.match(card, /schema_step_1/); assert.match(card, /<ol>/); });
test("rendering essenziale: action type e label restano nel JSON", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale", descrizione: "Il tiratore conclude e il portiere si tuffa" })); const dive = diagram.actions.find(item => item.type === "tuffo"); assert.ok(dive); assert.equal(dive.type, "tuffo"); assert.equal(dive.label, "Tuffo"); assert.equal(normalizeTacticalDiagram(JSON.parse(JSON.stringify(diagram)))?.actions.find(item => item.id === dive.id)?.label, "Tuffo"); });
test("rendering essenziale: editor conserva tipo label e sequenza", () => { const editor = source("../app/components/tactical-diagram-editor.tsx"); assert.match(editor, /selectedAction\.type/); assert.match(editor, /selectedAction\.label/); assert.match(editor, /selectedAction\.sequence/); });
test("rendering essenziale: tooltip discreto usa sequenza e label", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /const tooltip = `\$\{item\.sequence\} · \$\{item\.label/); assert.match(board, /<title>\{tooltip\}<\/title>/); });

test("Tactical Board V2: JSON V1 resta compatibile e V2 è il default", () => { const wrapper = source("../app/components/exercise-tactical-board.tsx"); assert.match(wrapper, /rendererVersion === "v1"/); assert.match(wrapper, /<TacticalBoardV2/); assert.equal(normalizeTacticalDiagram(generateTacticalDiagram(baseExercise))?.version, 1); });
test("Tactical Board V2: coordinate e azioni non vengono mutate dal renderer", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); assert.match(renderer, /const renderY = \(value: number\) => 100 - value/); assert.doesNotMatch(renderer, /diagram\.elements\.(push|splice)|diagram\.actions\.(push|splice)/); assert.match(renderer, /item\.startX/); assert.match(renderer, /renderY\(item\.startY\)/); });
test("Tactical Board V2: porta e area sono sul lato superiore", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); assert.match(renderer, /goalLineY: 12/); assert.match(renderer, /goalDepthY: 5/); assert.match(renderer, /v2-primary-goal/); assert.match(renderer, /v2-goal-area/); });
test("Tactical Board V2: simboli professionali coprono tutti gli elementi", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); for (const component of ["TacticalGoalkeeper", "TacticalAttacker", "TacticalPlayer", "TacticalCoach", "TacticalBall", "TacticalCone", "TacticalMannequin", "TacticalHurdle", "TacticalMiniGoal", "TacticalMarker"]) assert.match(renderer, new RegExp(`function ${component}`)); assert.match(renderer, /v2-ball/); assert.match(renderer, /v2-goalkeeper/); });
test("Tactical Board V2: azioni usano palette e stili funzionali", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); assert.match(renderer, /action\.type === "tiro"/); assert.match(renderer, /action\.type === "tuffo"/); assert.match(renderer, /action\.type === "passaggio" \|\| action\.type === "cross"/); assert.match(renderer, /action\.type === "conduzione"/); assert.match(renderer, /strokeDasharray=\{appearance\.dash\}/); });
test("Tactical Board V2: badge sequenza e label brevi restano leggibili", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); assert.match(renderer, /function TacticalSequenceBadge/); assert.match(renderer, /v2-element-label/); assert.match(renderer, /explicit\.length <= 3/); assert.doesNotMatch(renderer, /showActionLabels = true/); });
test("Tactical Board V2: ghost deriva dalle azioni senza aggiungere JSON", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); assert.match(renderer, /function TacticalGhosts/); assert.match(renderer, /x: item\.endX, y: item\.endY/); assert.match(renderer, /ghost \? \.28 : 1/); assert.match(renderer, /diagram\.elements\.length > 7/); });
test("Tactical Board V2: preview compatta riduce ghost rete e ombre", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); const css = source("../app/globals.css"); assert.match(renderer, /compact-board\|session-board/); assert.match(renderer, /!compact &&/); assert.match(css, /is-compact \.v2-ghost-positions\{display:none\}/); });
test("Tactical Board V2: editor espone il confronto locale con lo stesso JSON", () => { const editor = source("../app/components/tactical-diagram-editor.tsx"); assert.match(editor, /rendererVersion="v2-refined"/); assert.match(editor, /rendererVersion="v2-final"/); assert.match(editor, /diagram=\{diagram\}/); assert.match(editor, /localhost/); });
test("Tactical Board V2: confronto copre quindici tipologie automatiche", () => { const cases: Partial<Exercise>[] = [
  { nome: "Tuffo laterale" }, { nome: "Reattività su stimolo" }, { nome: "Tiro frontale" }, { nome: "Presa su passaggio", descrizione: "Il preparatore passa al portiere" }, { nome: "Cross da sinistra" }, { nome: "Uscita alta" }, { nome: "Uscita bassa" }, { nome: "1 contro 1" }, { nome: "Tecnica di piede" }, { nome: "Seconda palla" }, { nome: "Reattività con coni", descrizione: "Slalom tra coni" }, { nome: "Parata con sagoma", descrizione: "La sagoma crea disturbo" }, { nome: "Tuffo con ostacolo", descrizione: "Supera un ostacolo e interviene" }, { nome: "Presa semplice" }, { nome: "Match Simulation complesso", descrizione: "Tiratore, appoggio, coni, sagoma e ostacolo" },
  ]; for (const patch of cases) { const diagram = generateTacticalDiagram(exercise(patch)); assert.equal(diagram.version, 1); assert.ok(diagram.elements.length > 0); assert.ok(diagram.actions.length > 0); } });
test("Tactical Board V2: responsive resta disponibile su catalogo seduta campo ed editor", () => { const css = source("../app/globals.css"); assert.match(css, /@media\(max-width:780px\)/); assert.match(source("../app/components/exercise-card.tsx"), /ExerciseTacticalBoard/); assert.match(source("../app/components/session-exercise-card.tsx"), /ExerciseTacticalBoard/); assert.match(source("../app/components/session-field-mode.tsx"), /ExerciseTacticalBoard/); assert.match(source("../app/components/tactical-diagram-editor.tsx"), /ExerciseTacticalBoard/); });

test("V2 Refined: auto-framing non modifica il JSON", () => { const diagram = generateTacticalDiagram(baseExercise); const snapshot = JSON.stringify(diagram); computeTacticalViewBox(diagram, "compact"); assert.equal(JSON.stringify(diagram), snapshot); });
test("V2 Refined: anteprima usa un framing piu stretto del campo completo", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale su tiro" })); const frame = computeTacticalViewBox(diagram, "compact"); assert.ok(frame.width < 100 || frame.height < 100); assert.ok(frame.width >= 58 && frame.height >= 54); });
test("V2 Refined: framing include elementi e estremi delle azioni", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Cross da sinistra" })); const frame = computeTacticalViewBox(diagram, "detail"); const inside = (x: number, y: number) => x >= frame.x - .01 && x <= frame.x + frame.width + .01 && 100 - y >= frame.y - .01 && 100 - y <= frame.y + frame.height + .01; for (const item of diagram.elements.filter(item => !(item.type === "goal" && item.role === "Porta"))) assert.ok(inside(item.x, item.y)); for (const item of diagram.actions) assert.ok(inside(item.startX, item.startY) && inside(item.endX, item.endY)); });
test("V2 Refined: editor conserva l'intero sistema coordinate", () => { const frame = computeTacticalViewBox(generateTacticalDiagram(baseExercise), "editor"); assert.deepEqual(frame, { x: 0, y: 0, width: 100, height: 100 }); });
test("V2 Refined: componenti SVG e defs hanno identita univoca", () => { const renderer = source("../app/components/tactical-board-v2-refined.tsx"); for (const component of ["TacticalGoal", "TacticalGoalkeeper", "TacticalAttacker", "TacticalPlayer", "TacticalCoach", "TacticalBall", "TacticalCone", "TacticalMannequin", "TacticalHurdle", "TacticalMiniGoal", "TacticalSequenceBadge", "TacticalAction", "TacticalGhosts"]) assert.match(renderer, new RegExp(`function ${component}`)); assert.match(renderer, /useId\(\)/); assert.match(renderer, /v2r-arrow-/); });
test("V2 Refined: rotation resta nel modello ma non ruota le persone finali", () => { const renderer = source("../app/components/tactical-board-v2-refined.tsx"); assert.match(renderer, /displayRotation=neutral&&\["goalkeeper","attacker","player","coach"\]\.includes\(item\.type\)\?0:-item\.rotation/); assert.match(renderer, /scale\(\$\{renderedSymbolScale\(item,neutral,rescaled,compact\)\*depthScale\}\)/); });
test("V2 Final: wrapper mantiene i renderer precedenti e usa Final come default", () => { const wrapper = source("../app/components/exercise-tactical-board.tsx"); assert.match(wrapper, /rendererVersion === "v1"/); assert.match(wrapper, /rendererVersion === "v2"/); assert.match(wrapper, /rendererVersion === "v2-refined"/); assert.match(wrapper, /TacticalBoardV2Final/); });
test("V2 Final: confronto locale mostra Refined 2D e Final Perspective", () => { const editor = source("../app/components/tactical-diagram-editor.tsx"); assert.match(editor, /V2 Refined 2D \/ V2 Final Perspective/); assert.match(editor, /rendererVersion="v2-refined"/); assert.match(editor, /rendererVersion="v2-final"/); assert.equal((editor.match(/diagram=\{diagram\}/g) ?? []).length, 3); });
test("V2 Final: limite zoom conserva piu contesto", () => { const diagram=generateTacticalDiagram(exercise({nome:"Tuffo laterale"})); const current=computeTacticalViewBox(diagram,"compact"); const final=computeTacticalViewBox(diagram,"compact",{limitZoom:true}); assert.ok(final.width>=current.width&&final.height>=current.height); assert.ok(final.width>=68&&final.height>=60); });
test("V2 Final: dettaglio conserva piu campo della card", () => { const diagram=generateTacticalDiagram(baseExercise); const card=computeTacticalViewBox(diagram,"compact",{limitZoom:true}); const detail=computeTacticalViewBox(diagram,"detail",{limitZoom:true}); assert.ok(detail.width>=card.width&&detail.height>=card.height); });
test("V2 Final: proiezione stringe solo la parte alta del campo", () => { const strength=tacticalPerspectiveStrength.detail; const top=projectTacticalPoint(10,10,strength); const bottom=projectTacticalPoint(10,90,strength); assert.ok(top.x>10); assert.ok(bottom.x<top.x); assert.equal(top.y,10); assert.equal(bottom.y,90); });
test("V2 Final: elementi lontani hanno una scala solo moderatamente inferiore", () => { const strength=tacticalPerspectiveStrength.detail; assert.ok(projectTacticalScale(10,strength)>=.92); assert.ok(projectTacticalScale(90,strength)>projectTacticalScale(10,strength)); });
test("V2 Final: editor resta in proiezione 2D", () => assert.equal(tacticalPerspectiveStrength.editor,0));
test("V2 Final: ghost singola, discreta e disabilitata negli schemi affollati", () => { const renderer=source("../app/components/tactical-board-v2-refined.tsx"); assert.match(renderer,/function significantGhost/); assert.match(renderer,/candidates\.find/); assert.match(renderer,/item\.type!=="ball"/); assert.match(renderer,/ghost \? \.19 : 1/); assert.match(renderer,/diagram\.actions\.length>5/); });
test("V2 Final Wide: viewBox usa tutto il rapporto orizzontale senza cambiare il JSON",()=>{const diagram=generateTacticalDiagram(baseExercise),snapshot=JSON.stringify(diagram),base=computeTacticalViewBox(diagram,"detail",{limitZoom:true}),wide=widenTacticalViewBox(base,diagram.canvas.widthRatio/diagram.canvas.heightRatio);assert.ok(Math.abs(wide.width/wide.height-diagram.canvas.widthRatio/diagram.canvas.heightRatio)<.001);assert.equal(JSON.stringify(diagram),snapshot);});
test("V2 Final Wide: prato occupa il 92-96 percento secondo il contesto",()=>{assert.ok(tacticalHorizontalExpansion.compact>=.92&&tacticalHorizontalExpansion.compact<=.96);assert.ok(tacticalHorizontalExpansion.detail>=.92&&tacticalHorizontalExpansion.detail<=.96);assert.ok(tacticalHorizontalExpansion.field>=.92&&tacticalHorizontalExpansion.field<=.96);});
test("V2 Final Figure Refined: figure principali usano gli asset frontali di riferimento",()=>{const renderer=source("../app/components/tactical-board-v2-refined.tsx");assert.match(renderer,/ReferenceGoalkeeper/);assert.match(renderer,/ReferenceAttacker/);assert.match(renderer,/ReferenceCoach/);assert.match(renderer,/ReferencePlayer/);assert.match(renderer,/displayRotation=neutral&&\["goalkeeper","attacker","player","coach"\]\.includes\(item\.type\)\?0/);});
test("V2 Final Figure Refined: soltanto la ghost di tuffo usa la posa dinamica",()=>{const renderer=source("../app/components/tactical-board-v2-refined.tsx");assert.match(renderer,/function TacticalDiveGhost/);assert.match(renderer,/item\.actionType==="tuffo"/);assert.match(renderer,/opacity="\.18"/);});
test("asset rescaled: la profondità resta nel range moderato 0.96-1.04",()=>{assert.equal(projectTacticalAssetDepthScale(0),.96);assert.equal(projectTacticalAssetDepthScale(100),1.04);assert.ok(projectTacticalAssetDepthScale(50)>.96&&projectTacticalAssetDepthScale(50)<1.04);});
test("asset final: scala definitiva è centralizzata, immutabile e uniforme",()=>{const assets=source("../lib/tactical-visual-scale.ts");assert.match(assets,/TACTICAL_VISUAL_SCALE[^=]*= Object\.freeze/);for(const type of ["goalkeeper","attacker","player","coach"])assert.match(assets,new RegExp(`${type}: \\.83`));assert.match(assets,/ball: \.845/);assert.match(assets,/cone: \.22/);assert.match(assets,/mannequin: \.52/);assert.match(assets,/mini_goal: \.74/);assert.match(assets,/resolveTacticalAssetScale/);});
test("pallone rescaled: scala, minimi compatti e profondità restano leggibili",()=>{const assets=source("../lib/tactical-visual-scale.ts"),renderer=source("../app/components/tactical-board-v2-refined.tsx");assert.match(assets,/ball: \.78/);assert.match(assets,/marker: \.38/);assert.equal(projectTacticalBallDepthScale(0),.99);assert.equal(projectTacticalBallDepthScale(100),1.01);assert.match(renderer,/item\.type==="ball"\?projectTacticalBallDepthScale/);});
test("asset final: è l'unica configurazione attiva e il wrapper non espone override DEV",()=>{const assets=source("../app/components/tactical-assets.tsx"),wrapper=source("../app/components/exercise-tactical-board.tsx"),renderer=source("../app/components/tactical-board-v2-refined.tsx");assert.doesNotMatch(assets,/TACTICAL_RESCALED_VISUAL_SCALE|TACTICAL_SCALE/);assert.doesNotMatch(wrapper,/v2-assets-current|v2-assets-rescaled|v2-final-wide|v2-final-figures/);assert.match(renderer,/variant="asset-final"/);assert.match(renderer,/projectTacticalAssetDepthScale/);});
test("asset final: badge e silhouette hanno contrasto e arti rinforzati",()=>{const assets=source("../app/components/tactical-assets.tsx");assert.match(assets,/fontSize="3\.05"/);assert.match(assets,/stroke="#f6fbf7" strokeWidth=\{goalkeeper\?2\.65:2\.4\}/);assert.match(assets,/stroke=\{highlight\} strokeWidth="\.62"/);});
test("asset definitivi: tutti i componenti SVG richiesti sono riutilizzabili",()=>{const assets=source("../app/components/tactical-assets.tsx");for(const name of ["TacticalGoalkeeper","TacticalAttacker","TacticalCoach","TacticalPlayer","TacticalBall","TacticalCone","TacticalMannequin","TacticalMiniGoal"])assert.match(assets,new RegExp(`export function ${name}`));});
test("pagina dev tactical-assets confronta riferimento SVG e proporzioni",()=>{const page=source("../app/dev/tactical-assets/page.tsx");assert.match(page,/REFERENCE/);assert.match(page,/SVG IMPLEMENTATION/);assert.match(page,/PROPORTION TEST/);assert.match(page,/tactical-board-reference\.png/);assert.match(page,/TACTICAL_VISUAL_SCALE/);});
