import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { createTacticalCatalogAudit, selectCatalogAuditSample, summarizeTacticalAudit } from "../lib/tactical-catalog-audit.ts";
import type { Exercise } from "../lib/types.ts";

const exercise=(index:number,patch:Partial<Exercise>={}):Exercise=>({id:`audit-${index}`,codice:`GK-AUD-${String(index).padStart(3,"0")}`,nome:`Esercizio ${index}`,category_id:1,subcategory_id:1,categoria:index%2?"Tecnica":"Situazionale",sottocategoria:"Test",fase:"Analitico",obiettivo:"Audit",descrizione:"Presa frontale",durata_min:10,portieri_min:1,portieri_max:2,intensita:"Media",difficolta:2,materiale:"Palloni",variante:null,coaching_points:"",errori_comuni:"",schema_step_1:null,schema_step_2:null,schema_step_3:null,schema_step_4:null,schema_step_5:null,schema_step_6:null,scenario_gara:null,numero_azioni:null,schema_url:null,foto_url:null,attivo:true,...patch});
const source=(path:string)=>readFileSync(new URL(path,import.meta.url),"utf8");

test("audit catalogo: seleziona al massimo trenta esercizi reali e diversifica",()=>{const records=Array.from({length:45},(_,index)=>exercise(index+1,index%6===0?{nome:"Cross",descrizione:"Cross con uscita alta"}:index%5===0?{nome:"Seconda palla",descrizione:"Il tiratore conclude e l'appoggio serve la seconda palla"}:index%4===0?{nome:"Slalom",descrizione:"Slalom tra 5 cinesini"}:{})),sample=selectCatalogAuditSample(records,30);assert.equal(sample.length,30);assert.ok(new Set(sample.map(item=>item.nome)).size>2);assert.ok(new Set(sample.map(item=>item.categoria)).size>1);});
test("audit catalogo: quality score e validazioni sono solo calcolati in memoria",()=>{const item=createTacticalCatalogAudit(exercise(1,{nome:"Cross",descrizione:"Il servitore effettua un cross"}));assert.ok(item.qualityScore>=0&&item.qualityScore<=100);assert.ok(["VALID","VALID_WITH_WARNINGS","NEEDS_REVIEW"].includes(item.status));assert.ok(item.diagram.elements.length>0);});
test("audit catalogo: preview manuale è marcata e non sovrascritta",()=>{const original=exercise(2,{diagram_source:"manual"}),item=createTacticalCatalogAudit(original);assert.equal(item.alternativePreview,true);assert.equal(original.tactical_diagram,undefined);});
test("audit catalogo: statistiche sommano stati famiglie ed equipment",()=>{const items=[createTacticalCatalogAudit(exercise(1,{nome:"Cross",descrizione:"Cross da sinistra"})),createTacticalCatalogAudit(exercise(2,{nome:"Slalom",descrizione:"Slalom tra 5 cinesini"}))],summary=summarizeTacticalAudit(items);assert.equal(summary.total,2);assert.equal(summary.valid+summary.warnings+summary.review,2);assert.ok(summary.families.length>=1);assert.ok(summary.equipment.some(row=>row.tag==="CINESINI"&&row.total===1));});
test("marker tecnici: production hidden e debug esplicito",()=>{const renderer=source("../app/components/tactical-board-v2-refined.tsx"),css=source("../app/globals.css"),comparison=source("../app/dev/tactical-technical-markers/page.tsx");assert.match(renderer,/showTechnicalMarkers=false/);assert.match(renderer,/v2r-technical-markers/);assert.match(css,/\.v2r-technical-markers\{display:none\}/);assert.match(css,/\.show-technical-markers \.v2r-technical-markers\{display:block\}/);assert.match(comparison,/WITHOUT TECHNICAL MARKERS/);});
test("badge chiari: numero usa contrasto scuro e non viene scambiato per marker",()=>{const renderer=source("../app/components/tactical-board-v2-refined.tsx");assert.match(renderer,/const light=\[/);assert.match(renderer,/fill=\{light\?"#101914":"#fff"\}/);});
