import assert from "node:assert/strict";
import test from "node:test";
import { classifyTacticalFamily, generateTacticalDiagram, resolveTacticalTemplate } from "../lib/tactical-diagram.ts";
import { createTacticalCatalogAudit, diagnoseTacticalCollisions } from "../lib/tactical-catalog-audit.ts";
import { extractTacticalSetupRequirements, validateTacticalSetup } from "../lib/tactical-setup-validation.ts";
import { calculateTacticalLayoutDensity, EQUIPMENT_MIN_DISTANCE, refineEquipmentLayout, validateEquipmentLayout } from "../lib/tactical-equipment-layout.ts";
import type { Exercise, TacticalDiagram } from "../lib/types.ts";

const base:Exercise={id:"validation",codice:"GK-VAL",nome:"Setup",category_id:1,subcategory_id:1,categoria:"Tecnica",sottocategoria:"Setup",fase:"Analitico",obiettivo:"Setup",descrizione:"",durata_min:10,portieri_min:1,portieri_max:2,intensita:"Media",difficolta:2,materiale:"Palloni",variante:null,coaching_points:"",errori_comuni:"",schema_step_1:null,schema_step_2:null,schema_step_3:null,schema_step_4:null,schema_step_5:null,schema_step_6:null,scenario_gara:null,numero_azioni:null,attivo:true};
const exercise=(patch:Partial<Exercise>):Exercise=>({...base,...patch});
const empty: TacticalDiagram={version:1,canvas:{viewType:"penalty_area",widthRatio:16,heightRatio:10},elements:[{id:"gk",type:"goalkeeper",x:50,y:68,rotation:0,scale:1,role:"Portiere"}],actions:[]};

test("validazione setup: tra due coni richiede e crea un varco funzionale",()=>{const item=exercise({descrizione:"Il GK parte tra due coni e para"}),requirements=extractTacticalSetupRequirements(item),result=validateTacticalSetup(item,empty);assert.equal(requirements.find(value=>value.type==="cone")?.count,2);assert.equal(result.diagram.elements.filter(value=>value.type==="cone").length,2);assert.equal(result.status,"VALID");});
test("validazione setup: due porticine laterali occupano entrambi i lati",()=>{const item=exercise({nome:"Tecnica di piede",descrizione:"Il GK passa in una delle due porticine laterali"}),result=validateTacticalSetup(item,generateTacticalDiagram(item,{refineComposition:false}));const goals=result.diagram.elements.filter(value=>value.type==="mini_goal");assert.equal(goals.length,2);assert.ok(goals.some(value=>value.x<40)&&goals.some(value=>value.x>60));assert.ok(result.diagram.actions.some(action=>goals.some(goal=>action.toElementId===goal.id)));});
test("validazione setup: slalom tra cinque cinesini produce un percorso ordinato",()=>{const item=exercise({descrizione:"Slalom tra cinque cinesini e passaggio"}),result=validateTacticalSetup(item,empty);const markers=result.diagram.elements.filter(value=>value.type==="marker");assert.equal(markers.length,5);assert.equal(new Set(markers.map(value=>value.y)).size,5);assert.equal(result.status,"VALID");});
test("validazione setup: supera tre ostacoli produce tre hurdle",()=>{const item=exercise({descrizione:"Il portiere supera 3 ostacoli e recupera"}),result=validateTacticalSetup(item,empty);assert.equal(result.diagram.elements.filter(value=>value.type==="hurdle").length,3);});
test("validazione setup: passaggio tra due sagome crea un varco",()=>{const item=exercise({descrizione:"Passaggio tra due sagome"}),result=validateTacticalSetup(item,empty);const mannequins=result.diagram.elements.filter(value=>value.type==="mannequin");assert.equal(mannequins.length,2);assert.ok(Math.abs(mannequins[0].x-mannequins[1].x)>=8);});
test("validazione setup: seconda palla genera due origini distinte",()=>{const item=exercise({nome:"Seconda palla",descrizione:"Il tiratore conclude e l'appoggio serve la seconda palla"}),diagram=generateTacticalDiagram(item),result=validateTacticalSetup(item,diagram,{autoRepair:false});const balls=result.diagram.elements.filter(value=>value.type==="ball");assert.equal(balls.length,2);assert.ok(Math.hypot(balls[0].x-balls[1].x,balls[0].y-balls[1].y)>=5);assert.equal(result.status,"VALID");});
test("validazione setup: materiale dichiarato ma non funzionale produce solo info",()=>{const item=exercise({materiale:"10 palloni, 8 coni"}),result=validateTacticalSetup(item,empty,{autoRepair:false});assert.equal(result.status,"VALID");assert.equal(result.issues.length,0);assert.equal(result.warnings.length,0);assert.equal(result.infos.length,2);assert.deepEqual(result.equipmentInventory.find(value=>value.type==="cone"),{type:"cone",declared:8,required:0,optional:8,rendered:0});});
test("validazione setup: confronta declared required e rendered senza penalizzare la scorta",()=>{const item=exercise({materiale:"8 coni",descrizione:"Il GK parte tra due coni"}),result=validateTacticalSetup(item,empty);assert.equal(result.status,"VALID");assert.deepEqual(result.equipmentInventory.find(value=>value.type==="cone"),{type:"cone",declared:8,required:2,optional:6,rendered:2});assert.match(result.infos[0],/8 dichiarati, 2 semanticamente necessari/);});
test("validazione setup: porticina solo nei materiali è informativa",()=>{const item=exercise({materiale:"Palloni, 1 porticina",descrizione:"Il preparatore effettua un tiro e il GK para"}),result=validateTacticalSetup(item,generateTacticalDiagram(item),{autoRepair:false});assert.equal(result.expectedElements.some(value=>value.type==="mini_goal"),false);assert.equal(result.warnings.some(value=>/porticina/i.test(value)),false);assert.ok(result.infos.some(value=>/Porticine.*non richiesti/i.test(value)));});
test("validazione setup: più palloni dichiarati non implicano origini multiple",()=>{const item=exercise({materiale:"10 palloni",descrizione:"Il preparatore effettua un tiro e il GK para"}),requirements=extractTacticalSetupRequirements(item);assert.equal(requirements.find(value=>value.relation==="second_ball_source"),undefined);assert.equal(requirements.find(value=>value.relation==="ball_owner")?.count,1);});
test("validazione setup: intervalli dichiarati usano il minimo e requisiti sovrapposti non si sommano",()=>{const item=exercise({materiale:"10-16 palloni",descrizione:"Il tiratore conclude e l'appoggio serve la seconda palla"}),result=validateTacticalSetup(item,generateTacticalDiagram(item),{autoRepair:false}),balls=result.equipmentInventory.find(value=>value.type==="ball");assert.equal(balls?.declared,10);assert.equal(balls?.required,2);assert.equal(balls?.rendered,2);});
test("validazione setup: manual e automatic_edited non vengono corretti",()=>{for(const source of ["manual","automatic_edited"] as const){const item=exercise({descrizione:"Il GK parte tra due coni",diagram_source:source}),result=validateTacticalSetup(item,empty);assert.equal(result.status,"NEEDS_REVIEW");assert.equal(result.diagram.elements.filter(value=>value.type==="cone").length,0);assert.equal(result.repairs.length,0);}});
test("validazione setup: dieci palloni di scorta non diventano dieci icone",()=>{const item=exercise({materiale:"10 palloni"}),result=validateTacticalSetup(item,generateTacticalDiagram(item));assert.ok(result.diagram.elements.filter(value=>value.type==="ball").length<10);});
test("relazioni setup: mini goal presente ma non collegata richiede revisione",()=>{const item=exercise({descrizione:"Il GK effettua un passaggio nella porticina"}),diagram={...empty,elements:[...empty.elements,{id:"ball",type:"ball" as const,x:54,y:74,rotation:0,scale:1},{id:"goal",type:"mini_goal" as const,x:80,y:40,rotation:0,scale:1}],actions:[{id:"pass",type:"passaggio" as const,fromElementId:"ball",startX:54,startY:74,endX:50,endY:45,sequence:1}]},result=validateTacticalSetup(item,diagram,{autoRepair:false});assert.equal(result.elementValidation.valid,true);assert.equal(result.relationValidation.valid,false);assert.equal(result.status,"NEEDS_REVIEW");});
test("relazioni setup: marker presenti ma non in slalom richiedono revisione",()=>{const item=exercise({descrizione:"Slalom tra 5 cinesini"}),diagram={...empty,elements:[...empty.elements,...Array.from({length:5},(_,index)=>({id:`m-${index}`,type:"marker" as const,x:40+index*3,y:50,rotation:0,scale:1}))]},result=validateTacticalSetup(item,diagram,{autoRepair:false});assert.equal(result.elementValidation.valid,true);assert.equal(result.relationValidation.valid,false);assert.equal(result.status,"NEEDS_REVIEW");});
test("relazioni setup: quadrato, rombo e corridoio derivano dalla semantica",()=>{const square=validateTacticalSetup(exercise({descrizione:"Quadrato di 4 coni"}),empty),diamond=validateTacticalSetup(exercise({descrizione:"Rombo con quattro coni"}),empty),corridor=validateTacticalSetup(exercise({descrizione:"Corridoio con 6 cinesini"}),empty);assert.equal(square.relationValidation.valid,true);assert.equal(diamond.relationValidation.valid,true);assert.equal(corridor.relationValidation.valid,true);assert.equal(corridor.diagram.elements.filter(item=>item.type==="marker").length,6);});
test("relazioni setup: ostacoli e slalom generano actions che attraversano il percorso",()=>{for(const item of [exercise({descrizione:"Il GK supera 3 ostacoli e para"}),exercise({descrizione:"Il GK esegue slalom tra 5 cinesini"})]){const result=validateTacticalSetup(item,empty);assert.ok(result.diagram.actions.some(action=>action.id.startsWith("validation-path-")));const relation=item.descrizione.includes("ostacoli")?"hurdle_sequence":"slalom";assert.equal(result.relationValidation.checks.find(check=>check.relation===relation)?.valid,true);}});
test("relazioni setup: ball ownership collega pallone, proprietario e action",()=>{const item=exercise({descrizione:"Il servitore passa il pallone al portiere"}),diagram=generateTacticalDiagram(item),result=validateTacticalSetup(item,diagram,{autoRepair:false});const ball=result.diagram.elements.find(value=>value.type==="ball");assert.ok(ball&&result.diagram.actions.some(action=>action.fromElementId===ball.id));assert.equal(result.relationValidation.valid,true);});
test("relazioni setup: seconda palla usa due proprietari e due action origins",()=>{const item=exercise({nome:"Seconda palla",descrizione:"Il tiratore conclude e l'appoggio serve la seconda palla"}),result=validateTacticalSetup(item,generateTacticalDiagram(item),{autoRepair:false});const balls=result.diagram.elements.filter(value=>value.type==="ball");assert.equal(balls.length,2);assert.ok(balls.every(ball=>result.diagram.actions.some(action=>action.fromElementId===ball.id)));assert.equal(result.relationValidation.valid,true);});
test("parser setup: con target non diventa cono e passa nella porticina crea il target",()=>{const item=exercise({nome:"Tecnica di piede con target",descrizione:"Il GK passa nella porticina"}),requirements=extractTacticalSetupRequirements(item);assert.equal(requirements.some(value=>value.type==="cone"),false);assert.equal(requirements.find(value=>value.relation==="mini_goal_target")?.count,1);assert.equal(requirements.find(value=>value.relation==="ball_owner")?.count,1);});
test("layout equipment: distanze minime sono specifiche per coppia",()=>{assert.notEqual(EQUIPMENT_MIN_DISTANCE["marker-marker"],EQUIPMENT_MIN_DISTANCE["hurdle-hurdle"]);assert.ok(EQUIPMENT_MIN_DISTANCE["equipment-goalkeeper"]>EQUIPMENT_MIN_DISTANCE["equipment-player"]);});
test("layout equipment: slalom automatico usa zig-zag e spacing leggibile",()=>{const item=exercise({descrizione:"Il GK esegue uno slalom tra 5 cinesini e passa"}),raw=validateTacticalSetup(item,empty,{refineLayout:false}),result=refineEquipmentLayout(raw.diagram,raw.expectedElements),markers=result.diagram.elements.filter(value=>value.type==="marker");assert.equal(markers.length,5);assert.ok(new Set(markers.map(value=>Math.sign(value.x-50))).size>1);assert.equal(result.validation.metrics.pathTooCompressed,false);});
test("layout equipment: ostacoli seguono zone sequenziali",()=>{const item=exercise({descrizione:"Il GK supera 3 ostacoli e recupera"}),result=validateTacticalSetup(item,empty),hurdles=result.diagram.elements.filter(value=>value.type==="hurdle");assert.ok(hurdles.every((value,index)=>index===0||value.y<hurdles[index-1].y));assert.ok(Math.max(...hurdles.map(value=>value.x))-Math.min(...hurdles.map(value=>value.x))>4);});
test("layout equipment: setup complesso usa densità e superficie senza zoom",()=>{const item=exercise({descrizione:"Il GK parte tra due coni, esegue uno slalom tra 4 cinesini e passa nella porticina"}),raw=generateTacticalDiagram(item,{validateSetup:false}),result=validateTacticalSetup(item,raw);assert.ok(["MEDIUM","HIGH"].includes(result.layoutDensity));assert.equal(result.layoutValidation.metrics.excessiveDensity,false);assert.equal(result.diagram.canvas.widthRatio,raw.canvas.widthRatio);assert.equal(result.diagram.canvas.heightRatio,raw.canvas.heightRatio);});
test("layout equipment: routing aggiorna actions dopo lo spacing",()=>{const item=exercise({descrizione:"Il GK supera 3 ostacoli e recupera"}),result=validateTacticalSetup(item,empty),hurdles=result.diagram.elements.filter(value=>value.type==="hurdle"),paths=result.diagram.actions.filter(value=>value.id.startsWith("validation-path-")).sort((a,b)=>a.sequence-b.sequence);assert.equal(paths.length,3);assert.ok(paths.every((action,index)=>action.endX===hurdles[index].x&&action.endY===hurdles[index].y));});
test("layout equipment: validazione rileva overlap e percorso compresso",()=>{const requirements=extractTacticalSetupRequirements(exercise({descrizione:"Slalom tra 5 cinesini"})),diagram:TacticalDiagram={...empty,elements:[...empty.elements,...Array.from({length:5},(_,index)=>({id:`compressed-${index}`,type:"marker" as const,x:50+index*.3,y:50,rotation:0,scale:1}))]},layout=validateEquipmentLayout(diagram,requirements,calculateTacticalLayoutDensity(diagram));assert.ok(layout.metrics.excessiveOverlap>0);assert.equal(layout.metrics.pathTooCompressed,true);assert.equal(layout.valid,false);});
test("layout equipment: manual e automatic_edited restano identici",()=>{const requirements=extractTacticalSetupRequirements(exercise({descrizione:"Slalom tra 5 cinesini"}));for(const source of ["manual","automatic_edited"] as const)assert.equal(refineEquipmentLayout(empty,requirements,source).diagram,empty);});

test("semantic gap fix: recupera solo gli alias specifici FOOTWORK, ONE_V_ONE e HIGH_CLAIM",()=>{
  const foot=exercise({codice:"GK-TP-035",categoria:"Tecnica di piede",sottocategoria:"Combinazione in costruzione",nome:"Uscita dalla pressione con terzo uomo",descrizione:"Posizionamento e scansione. Ricezione del pallone. Primo controllo orientamento. Scelta soluzione e trasmissione."});
  const footTwo=exercise({codice:"GK-TP-023",categoria:"Tecnica di piede",sottocategoria:"Combinazione tecnica",nome:"Uno-due con compagno",descrizione:foot.descrizione});
  const duel=exercise({codice:"GK-CA-032",categoria:"Tecnica 1v1 - copertura angoli",nome:"Palla filtrante",descrizione:"Situazione 1v1 con attaccante libero: leggere porta e velocità e le possibili soluzioni."});
  const duelTwo=exercise({codice:"GK-CA-033",categoria:"Tecnica 1v1 - copertura angoli",nome:"Attaccante con recupero difensore",descrizione:"Attaccante libero: leggere palla, porta e velocità prima delle possibili soluzioni."});
  const claim=exercise({codice:"GK-UA-033",categoria:"Uscite alte e palle aeree",nome:"Punizione laterale in area",descrizione:"Battuta laterale in area con traffico."});
  assert.deepEqual([foot,footTwo,duel,duelTwo,claim].map(value=>classifyTacticalFamily(value)),["FOOTWORK","FOOTWORK","ONE_V_ONE","ONE_V_ONE","HIGH_CLAIM"]);
  assert.deepEqual([foot,duel,claim].map(value=>resolveTacticalTemplate(value)),["tecnica_piede","uno_contro_uno","uscita_alta"]);
  assert.equal(classifyTacticalFamily(exercise({categoria:"Tema libero",nome:"Challenge libera",descrizione:"Circuito personalizzabile multi-obiettivo senza fondamentale dominante."})),"GENERIC");
});

test("semantic gap fix: BALL_A e BALL_B hanno SOURCE_A e SOURCE_B indipendenti",()=>{
  for(const value of [exercise({codice:"RAP-004",nome:"Reazione su deviazione",descrizione:"Intervento reattivo dopo una deviazione ravvicinata."}),exercise({codice:"GK-ROT-040",nome:"Sequenza gara con ostacolo e seconda palla",categoria:"Reattività con ostacoli e tuffi",sottocategoria:"Sequenza gara",descrizione:"Una breve attivazione precede una conclusione reale o una seconda azione.",schema_step_2:"Esecuzione del compito motorio/ostacolo.",schema_step_4:"Stimolo o conclusione."})]){
    const item=createTacticalCatalogAudit(value),balls=item.diagram.elements.filter(element=>element.type==="ball"),owners=item.diagram.elements.filter(element=>/Tiratore|Servitore B|Appoggio/.test(element.role??""));
    assert.equal(balls.length,2);assert.ok(owners.length>=2);assert.ok(balls.every(ball=>item.diagram.actions.some(action=>action.fromElementId===ball.id)));assert.notEqual(item.status,"NEEDS_REVIEW");
  }
});

test("semantic gap fix: ownership inattiva, origine 2vs1 e transizione derivata sono coerenti",()=>{
  const mirror=createTacticalCatalogAudit(exercise({codice:"GK-TL-019",nome:"Sequenza specchio tra due portieri",categoria:"Tema libero",obiettivo:"Riprodurre rapidamente i movimenti del compagno e concludere con un gesto tecnico.",descrizione:"Esercizio specchio con stimoli variabili e gesto tecnico finale non definito."}));assert.equal(mirror.diagram.elements.filter(element=>element.type==="ball").length,0);assert.notEqual(mirror.status,"NEEDS_REVIEW");
  const duel=createTacticalCatalogAudit(exercise({codice:"GK-CA-035",categoria:"Tecnica 1v1 - copertura angoli",nome:"2vs1: scarico laterale",descrizione:"Situazione con attaccante libero: leggere palla, porta, velocità e possibili soluzioni."})),activeBall=duel.diagram.elements.find(element=>element.type==="ball");assert.equal(duel.family,"ONE_V_ONE");assert.ok(activeBall&&duel.diagram.actions.some(action=>action.fromElementId===activeBall.id));
  const derived=createTacticalCatalogAudit(exercise({codice:"GK-MS-041",categoria:"Match Simulation",nome:"Corner in traffico → respinta → seconda palla",descrizione:"Corner in traffico, respinta e seconda azione sulla palla derivata.",schema_step_3:"Prima azione tecnica.",schema_step_4:"Recupero e sviluppo successivo.",schema_step_5:"Seconda azione."}));assert.equal(derived.diagram.elements.filter(element=>element.type==="ball").length,1);assert.deepEqual(derived.diagram.actions.slice(0,3).map(action=>action.type),["tiro","recupero","movimento"]);assert.notEqual(derived.status,"NEEDS_REVIEW");
});

test("semantic gap fix: routing locale GK-TLR-012 elimina la collisione reale",()=>{const value=exercise({codice:"GK-TLR-012",categoria:"Tuffi laterali e reattività",sottocategoria:"Tuffo + spostamento",nome:"Alternanza destra-sinistra su servizio dichiarato",descrizione:"Il preparatore dichiara il lato. Il portiere interviene, torna al centro e riceve sul lato opposto.",schema_step_2:"Primo servizio e tuffo.",schema_step_3:"Recupero e ritorno al centro.",schema_step_4:"Secondo servizio sul lato opposto."}),item=createTacticalCatalogAudit(value);assert.equal(diagnoseTacticalCollisions(value,item.diagram).some(collision=>collision.category==="REAL_COLLISION"),false);assert.notEqual(item.status,"NEEDS_REVIEW");});

test("semantic gap fix: famiglie stabili non degradano a NEEDS_REVIEW",()=>{const cases=["Seconda palla con appoggio","1v1 con attaccante libero","Tecnica di piede con ricezione e trasmissione","Doppio intervento","Parata su tiro","Posizionamento porta","Cross laterale","Uscita alta","Tuffo laterale","Reattività al colore"];for(const nome of cases){const item=createTacticalCatalogAudit(exercise({nome,descrizione:nome}));assert.notEqual(item.status,"NEEDS_REVIEW",`${nome} non deve regredire`);}const match=createTacticalCatalogAudit(exercise({nome:"Match Simulation con seconda palla",descrizione:"Il tiratore conclude, recupero e seconda palla servita dall'appoggio."}));assert.notEqual(match.status,"NEEDS_REVIEW");});
