import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import type { Exercise, TacticalDiagram, TacticalDiagramAction } from "../lib/types.ts";
import { addDiagramAction, addDiagramElement, chooseTacticalViewType, createEmptyTacticalDiagram, duplicateDiagramElement, generateTacticalDiagram, getActionAnnotationLayout, getTacticalFieldGeometry, moveDiagramElement, normalizeGeneratedActions, normalizeTacticalDiagram, optimizeTacticalDiagramLayout, removeDiagramItem, resolveTacticalTemplate } from "../lib/tactical-diagram.ts";

const baseExercise: Exercise = {
  id: "exercise-1", codice: "GK-TEST-001", nome: "Presa frontale", category_id: 1, subcategory_id: 1,
  categoria: "Tecnica presa", sottocategoria: "Presa alta", fase: "Analitico", obiettivo: "Tecnica di presa",
  descrizione: "Il tiratore passa e conclude", durata_min: 10, portieri_min: 1, portieri_max: 2, intensita: "Media",
  difficolta: 2, materiale: "Palloni, coni", variante: null, coaching_points: "Mani avanti", errori_comuni: "Mani rigide",
  schema_step_1: "Passaggio del tiratore", schema_step_2: "Presa e recupero al centro", schema_step_3: null, schema_step_4: null,
  schema_step_5: null, schema_step_6: null, scenario_gara: null, numero_azioni: null, schema_url: null, foto_url: null, attivo: true,
};
const exercise = (patch: Partial<Exercise> = {}) => ({ ...baseExercise, ...patch });
const source = (file: string) => readFileSync(new URL(file, import.meta.url), "utf8");

test("1. generazione automatica produce un JSON completo", () => { const value = generateTacticalDiagram(baseExercise); assert.ok(value.elements.length); assert.ok(value.actions.length); assert.equal(value.version, 1); });
test("2. schema salvato è normalizzabile", () => assert.deepEqual(normalizeTacticalDiagram(generateTacticalDiagram(baseExercise))?.version, 1));
test("3. refresh conserva il JSON senza rigenerarlo", () => { const value = JSON.parse(JSON.stringify(generateTacticalDiagram(baseExercise))); assert.deepEqual(normalizeTacticalDiagram(value), value); });
test("4. drag limita le coordinate al canvas", () => { const value = addDiagramElement(createEmptyTacticalDiagram(), "goalkeeper"); const moved = moveDiagramElement(value, value.elements[0].id, 120, -8); assert.equal(moved.elements[0].x, 98); assert.equal(moved.elements[0].y, 2); });
test("5. touch usa Pointer Events", () => assert.match(source("../app/components/exercise-tactical-board.tsx"), /onPointerDown/));
test("6. frecce di precisione sono disponibili", () => assert.match(source("../app/components/tactical-diagram-editor.tsx"), /ArrowUp/));
test("7. keyboard arrows spostano l’elemento", () => assert.match(source("../app/components/tactical-diagram-editor.tsx"), /ArrowRight/));
test("8. duplicazione crea un id distinto", () => { const value = addDiagramElement(createEmptyTacticalDiagram(), "ball"); const next = duplicateDiagramElement(value, value.elements[0].id); assert.equal(next.elements.length, 2); assert.notEqual(next.elements[0].id, next.elements[1].id); });
test("9. eliminazione rimuove elemento e azioni collegate", () => { const value = addDiagramElement(createEmptyTacticalDiagram(), "player"); assert.equal(removeDiagramItem(value, value.elements[0].id).elements.length, 0); });
test("10. rotazione è una proprietà del modello", () => assert.equal(addDiagramElement(createEmptyTacticalDiagram(), "goalkeeper").elements[0].rotation, 0));
test("11. aggiunta pallone", () => assert.equal(addDiagramElement(createEmptyTacticalDiagram(), "ball").elements[0].type, "ball"));
test("12. aggiunta giocatore", () => assert.equal(addDiagramElement(createEmptyTacticalDiagram(), "player").elements[0].type, "player"));
test("13. passaggio", () => assert.equal(addDiagramAction(createEmptyTacticalDiagram(), "passaggio").actions[0].type, "passaggio"));
test("14. tiro", () => assert.equal(addDiagramAction(createEmptyTacticalDiagram(), "tiro").actions[0].type, "tiro"));
test("15. cross usa template laterale", () => assert.equal(resolveTacticalTemplate(exercise({ nome: "Cross da sinistra" })), "cross"));
test("16. tuffo usa template dedicato", () => assert.equal(resolveTacticalTemplate(exercise({ nome: "Tuffo laterale" })), "tuffo_laterale"));
test("17. sequenza numerata parte da uno", () => assert.equal(addDiagramAction(createEmptyTacticalDiagram(), "tiro").actions[0].sequence, 1));
test("18. undo è presente", () => assert.match(source("../app/components/tactical-diagram-editor.tsx"), /setCursor\(value => Math\.max/));
test("19. redo è presente", () => assert.match(source("../app/components/tactical-diagram-editor.tsx"), /setCursor\(value => Math\.min/));
test("20. reset/rigenerazione non salva immediatamente", () => assert.match(source("../app/components/tactical-diagram-editor.tsx"), /Rigenera/));
test("21. responsive usa viewBox e aspect ratio", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /viewBox="0 0 100 100"/); assert.match(board, /aspectRatio/); });
test("22. generazione massiva ha avanzamento", () => assert.match(source("../app/keeper-app.tsx"), /onProgress\(index \+ 1/));
test("23. generazione massiva non sovrascrive", () => assert.match(source("../app/keeper-app.tsx"), /\.is\("tactical_diagram", null\)/));
test("24. migration non modifica RLS", () => { const sql = source("../supabase/migrations/0027_exercise_tactical_diagrams.sql"); assert.doesNotMatch(sql, /create policy|drop policy|disable row level/i); });
test("25. generazione massiva è catalog-admin", () => assert.match(source("../app/keeper-app.tsx"), /!catalogAdmin/));
test("26. catalogo usa ExerciseTacticalBoard", () => assert.match(source("../app/components/exercise-card.tsx"), /ExerciseTacticalBoard/));
test("27. sedute usano ExerciseTacticalBoard", () => assert.match(source("../app/components/session-exercise-card.tsx"), /ExerciseTacticalBoard/));
test("coordinate del JSON sono percentuali", () => { const value: TacticalDiagram = generateTacticalDiagram(baseExercise); for (const item of value.elements) assert.ok(item.x >= 0 && item.x <= 100 && item.y >= 0 && item.y <= 100); });
test("il solo campo materiale non aggiunge coni", () => assert.equal(generateTacticalDiagram(baseExercise).elements.filter(item => item.type === "cone").length, 0));
test("regola tiratore assegna il ruolo senza duplicati", () => assert.equal(generateTacticalDiagram(exercise({ descrizione: "Il tiratore serve il tiratore che conclude", schema_step_1: "Il tiratore effettua il tiro" })).elements.filter(item => item.role?.toLowerCase() === "tiratore").length, 1));
test("cronologia drag mantiene il cursore entro le versioni disponibili", () => { const editor = source("../app/components/tactical-diagram-editor.tsx"); assert.match(editor, /Math\.min\(cursor, current\.length - 1\)/); assert.match(editor, /setCursor\(updated\.length - 1\)/); });
test("esercizio per tre portieri mostra un solo GK attivo", () => { const diagram = generateTacticalDiagram(exercise({ portieri_min: 3, portieri_max: 3 })); assert.equal(diagram.elements.filter(item => item.type === "goalkeeper").length, 1); });
test("secondo GK esplicitamente attivo mostra due goalkeeper", () => { const diagram = generateTacticalDiagram(exercise({ portieri_min: 3, portieri_max: 3, schema_step_2: "Il secondo portiere interviene sulla seconda conclusione" })); assert.equal(diagram.elements.filter(item => item.type === "goalkeeper").length, 2); });
test("sei coni elencati ma non usati non compaiono", () => { const diagram = generateTacticalDiagram(exercise({ materiale: "6 coni, palloni", descrizione: "Il servitore passa la palla al portiere", schema_step_1: "Presa frontale", schema_step_2: null })); assert.equal(diagram.elements.filter(item => item.type === "cone").length, 0); });
test("tiro laterale sposta e orienta il GK verso il lato palla", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tiro laterale da sinistra", descrizione: "Il tiratore conclude da sinistra" })); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); assert.ok(goalkeeper); assert.ok(goalkeeper.x < 50); assert.notEqual(goalkeeper.rotation, 0); });
test("1 contro 1 porta il GK in posizione avanzata", () => { const diagram = generateTacticalDiagram(exercise({ nome: "1 contro 1 frontale", descrizione: "L’attaccante conduce verso la porta" })); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); assert.ok(goalkeeper && goalkeeper.y < 65); });
test("cross posiziona il servitore largo", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Cross da sinistra", descrizione: "Il servitore effettua un cross" })); const servant = diagram.elements.find(item => item.role === "Servitore"); assert.ok(servant && servant.x < 20); });
test("badge di sequenza è calcolato sul percorso dell’azione", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /action-sequence-badge/); assert.match(board, /getActionAnnotationLayout/); assert.doesNotMatch(board, /cx=\{item\.endX\} cy=\{item\.endY\} r="3\.2"/); });
test("template reattività conserva i coni funzionali", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Reattività su stimolo", descrizione: "Reazione a stimolo visivo", materiale: "Palloni" })); assert.ok(diagram.elements.some(item => item.type === "cone")); });
test("auto-layout: tiratore, pallone e GK non risultano sovrapposti", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale", descrizione: "Il tiratore conclude centralmente e il GK esegue il tuffo" })); const actors = diagram.elements.filter(item => ["goalkeeper", "attacker", "ball"].includes(item.type)); for (let left = 0; left < actors.length; left += 1) for (let right = left + 1; right < actors.length; right += 1) assert.ok(Math.hypot(actors[left].x - actors[right].x, actors[left].y - actors[right].y) >= 5); });
test("auto-layout: badge sequenza evita GK e giocatori", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale", descrizione: "Il tiratore conclude e il GK esegue il tuffo" })); for (const action of diagram.actions) { const annotation = getActionAnnotationLayout(action, diagram.elements); for (const item of diagram.elements.filter(element => ["goalkeeper", "attacker", "player", "coach"].includes(element.type))) assert.ok(Math.hypot(annotation.badgeX - item.x, annotation.badgeY - item.y) > 4); } });
test("auto-layout: label Tiro resta vicina alla propria traiettoria", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale", descrizione: "Il tiratore conclude" })); const shot = diagram.actions.find(item => item.type === "tiro"); assert.ok(shot); const annotation = getActionAnnotationLayout(shot, diagram.elements); const midpoint = { x: (shot.startX + shot.endX) / 2, y: (shot.startY + shot.endY) / 2 }; assert.ok(Math.hypot(annotation.labelX - midpoint.x, annotation.labelY - midpoint.y) < 14); });
test("auto-layout: label Tuffo resta vicina alla traiettoria GK", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale", descrizione: "Il GK esegue il tuffo" })); const dive = diagram.actions.find(item => item.type === "tuffo"); assert.ok(dive); const annotation = getActionAnnotationLayout(dive, diagram.elements); assert.ok(Math.hypot(annotation.labelX - (dive.startX + dive.endX) / 2, annotation.labelY - (dive.startY + dive.endY) / 2) < 16); });
test("auto-layout: il tuffo parte dal GK senza duplicarlo", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale", descrizione: "Il GK esegue un tuffo" })); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); const dive = diagram.actions.find(item => item.type === "tuffo"); assert.ok(goalkeeper && dive); assert.equal(dive.fromElementId, goalkeeper.id); assert.ok(Math.hypot(dive.startX - goalkeeper.x, dive.startY - goalkeeper.y) < 2); assert.equal(diagram.elements.filter(item => item.type === "goalkeeper").length, 1); });
test("auto-layout: il pallone non viene coperto dalle label", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale", descrizione: "Il tiratore conclude" })); const ball = diagram.elements.find(item => item.type === "ball"); assert.ok(ball); for (const action of diagram.actions) { const annotation = getActionAnnotationLayout(action, diagram.elements); assert.ok(Math.hypot(annotation.labelX - ball.x, annotation.labelY - ball.y) > 4); } });
test("auto-layout: cross da destra mantiene il servitore largo", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Cross da destra", descrizione: "Il servitore effettua il cross da destra" })); const servant = diagram.elements.find(item => item.role === "Servitore"); assert.ok(servant && servant.x > 80); });
test("auto-layout: uno schema semplice utilizza l’altezza disponibile", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Presa frontale", descrizione: "Il servitore passa al GK" })); const ys = diagram.elements.map(item => item.y); assert.ok(Math.max(...ys) - Math.min(...ys) > 30); });
test("auto-layout: schema complesso resta nella safe area", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Match Simulation seconda palla", descrizione: "Il tiratore conclude, l’appoggio serve la seconda palla, il secondo portiere interviene, usando coni, sagoma, ostacolo e porticina" })); for (const item of diagram.elements) { assert.ok(item.x >= 6 && item.x <= 94); assert.ok(item.y >= 6 && item.y <= 94); } for (const action of diagram.actions) { assert.ok(action.startX >= 6 && action.startX <= 94 && action.endX >= 6 && action.endX <= 94); assert.ok(action.startY >= 6 && action.startY <= 94 && action.endY >= 6 && action.endY <= 94); } });
test("auto-layout: porta di background e pallone leggibile rispettano la vista", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale", descrizione: "Il tiratore conclude" })); assert.equal(diagram.elements.some(item => item.type === "goal"), false); assert.ok((diagram.elements.find(item => item.type === "ball")?.scale ?? 0) >= 1.24); assert.match(source("../app/components/exercise-tactical-board.tsx"), /primary-goal-background/); });
test("auto-layout: uno schema manuale non viene modificato", () => { const diagram = generateTacticalDiagram(baseExercise); assert.equal(optimizeTacticalDiagramLayout(diagram, "manual"), diagram); assert.equal(optimizeTacticalDiagramLayout(diagram, "automatic_edited"), diagram); });

test("rifinitura 1: porta principale allineata alla linea di fondo", () => { const field = getTacticalFieldGeometry("front_goal"); assert.equal(field.goalLineY, 94); assert.ok(field.goalDepthY < field.goalLineY); const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /className="goal-frame"/); assert.match(board, /field\.goalLineY/); });
test("rifinitura 2: area di porta parte dalla stessa linea di fondo", () => { const field = getTacticalFieldGeometry("penalty_area"); assert.equal(field.goalLineY, 94); assert.ok(field.goalAreaTop < field.goalLineY); const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /goalAreaLeft.*goalLineY.*goalAreaTop.*goalAreaRight.*goalLineY/); });
test("rifinitura 3: la porta regolamentare non è un elemento automatico duplicato", () => { const diagram = generateTacticalDiagram(baseExercise); assert.equal(diagram.elements.filter(item => item.type === "goal").length, 0); assert.match(source("../app/components/exercise-tactical-board.tsx"), /primary-goal-background/); });
test("rifinitura 4: tuffo ha origine nel GK", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale", descrizione: "Il portiere si tuffa" })); const dive = diagram.actions.find(item => item.type === "tuffo"); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); assert.ok(dive && goalkeeper); assert.equal(dive.fromElementId, goalkeeper.id); assert.ok(Math.hypot(dive.startX - goalkeeper.x, dive.startY - goalkeeper.y) < 2); });
test("rifinitura 5: tiro ha origine dal pallone o dal tiratore", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Parata su tiro", descrizione: "Il tiratore conclude" })); const shot = diagram.actions.find(item => item.type === "tiro"); const ball = diagram.elements.find(item => item.type === "ball"); const shooter = diagram.elements.find(item => item.role === "Tiratore"); assert.ok(shot && ball && shooter); assert.ok(shot.fromElementId === ball.id || shot.fromElementId === shooter.id); assert.ok(Math.min(Math.hypot(shot.startX - ball.x, shot.startY - ball.y), Math.hypot(shot.startX - shooter.x, shot.startY - shooter.y)) < 3); });
test("rifinitura 6: due Tiro semanticamente duplicati diventano uno", () => { const shots: TacticalDiagramAction[] = [{ id: "shot-1", type: "tiro", startX: 40, startY: 30, endX: 50, endY: 70, sequence: 1, fromElementId: "ball", toElementId: "gk" }, { id: "shot-2", type: "tiro", startX: 42, startY: 32, endX: 51, endY: 69, sequence: 2, fromElementId: "ball", toElementId: "gk" }]; assert.equal(normalizeGeneratedActions(shots).length, 1); });
test("rifinitura 7: badge rispetta la zona di esclusione del GK", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale" })); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); assert.ok(goalkeeper); for (const item of diagram.actions) { const annotation = getActionAnnotationLayout(item, diagram.elements); assert.ok(Math.hypot(annotation.badgeX - goalkeeper.x, annotation.badgeY - goalkeeper.y) > 7); } });
test("rifinitura 8: label rispetta la zona di esclusione del GK", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo su tiro centrale" })); const goalkeeper = diagram.elements.find(item => item.type === "goalkeeper"); assert.ok(goalkeeper); for (const item of diagram.actions) { const annotation = getActionAnnotationLayout(item, diagram.elements); assert.ok(Math.hypot(annotation.labelX - goalkeeper.x, annotation.labelY - goalkeeper.y) > 7); } });
test("rifinitura 9: label non copre il pallone", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Parata su tiro centrale" })); const ball = diagram.elements.find(item => item.type === "ball"); assert.ok(ball); for (const item of diagram.actions) { const annotation = getActionAnnotationLayout(item, diagram.elements); assert.ok(Math.hypot(annotation.labelX - ball.x, annotation.labelY - ball.y) > 5); } });
test("rifinitura 10: schema semplice usa spazio verticale e orizzontale", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Presa frontale", descrizione: "Il servitore passa al portiere" })); const xs = diagram.elements.map(item => item.x); const ys = diagram.elements.map(item => item.y); assert.ok(Math.max(...ys) - Math.min(...ys) > 30); assert.ok(Math.max(...xs) - Math.min(...xs) > 10); });
test("rifinitura 11: schema complesso resta nella safe area", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Match Simulation seconda palla", descrizione: "Tiratore, appoggio, secondo portiere, coni, sagoma, ostacolo e porticina" })); assert.ok(diagram.elements.every(item => item.x >= 6 && item.x <= 94 && item.y >= 6 && item.y <= 94)); assert.ok(diagram.actions.every(item => [item.startX, item.startY, item.endX, item.endY].every(value => value >= 6 && value <= 94))); });
test("rifinitura 12: cross usa la vista larga dell’area", () => assert.equal(chooseTacticalViewType(exercise({ nome: "Cross da destra" })), "penalty_area"));
test("rifinitura 13: 1vs1 usa una vista ravvicinata", () => assert.equal(chooseTacticalViewType(exercise({ nome: "1 contro 1 frontale" })), "front_goal"));
test("rifinitura 14: tecnica di piede usa metà campo", () => assert.equal(chooseTacticalViewType(exercise({ nome: "Tecnica di piede e costruzione" })), "half_pitch"));
test("rifinitura 15: manual resta identico per riferimento", () => { const diagram = generateTacticalDiagram(baseExercise); assert.equal(optimizeTacticalDiagramLayout(diagram, "manual"), diagram); });
test("rifinitura 16: automatic_edited resta identico per riferimento", () => { const diagram = generateTacticalDiagram(baseExercise); assert.equal(optimizeTacticalDiagramLayout(diagram, "automatic_edited"), diagram); });

test("rendering essenziale: le label azioni sono nascoste per default", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /showActionLabels = false/); assert.match(board, /showLabel && item\.label/); });
test("rendering essenziale: le preview non attivano label azioni", () => { const card = source("../app/components/exercise-card.tsx"); const session = source("../app/components/session-exercise-card.tsx"); assert.doesNotMatch(card, /showActionLabels/); assert.doesNotMatch(session, /showActionLabels/); });
test("rendering essenziale: badge numerici restano visibili", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /action-sequence-badge/); assert.match(board, />\{item\.sequence\}<\/text>/); });
test("rendering essenziale: GK e sole etichette brevi restano leggibili", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /shortLabel\.length <= 3/); const diagram = generateTacticalDiagram(baseExercise); assert.equal(diagram.elements.find(item => item.type === "goalkeeper")?.label, "GK"); });
test("rendering essenziale: dettaglio mostra la sequenza testuale esterna", () => { const card = source("../app/components/exercise-card.tsx"); assert.match(card, /manual-procedure/); assert.match(card, /schema_step_1/); assert.match(card, /<ol>/); });
test("rendering essenziale: action type e label restano nel JSON", () => { const diagram = generateTacticalDiagram(exercise({ nome: "Tuffo laterale", descrizione: "Il tiratore conclude e il portiere si tuffa" })); const dive = diagram.actions.find(item => item.type === "tuffo"); assert.ok(dive); assert.equal(dive.type, "tuffo"); assert.equal(dive.label, "Tuffo"); assert.equal(normalizeTacticalDiagram(JSON.parse(JSON.stringify(diagram)))?.actions.find(item => item.id === dive.id)?.label, "Tuffo"); });
test("rendering essenziale: editor conserva tipo label e sequenza", () => { const editor = source("../app/components/tactical-diagram-editor.tsx"); assert.match(editor, /selectedAction\.type/); assert.match(editor, /selectedAction\.label/); assert.match(editor, /selectedAction\.sequence/); });
test("rendering essenziale: tooltip discreto usa sequenza e label", () => { const board = source("../app/components/exercise-tactical-board.tsx"); assert.match(board, /const tooltip = `\$\{item\.sequence\} · \$\{item\.label/); assert.match(board, /<title>\{tooltip\}<\/title>/); });

test("Tactical Board V2: JSON V1 resta compatibile e V2 è il default", () => { const wrapper = source("../app/components/exercise-tactical-board.tsx"); assert.match(wrapper, /rendererVersion === "v1"/); assert.match(wrapper, /<TacticalBoardV2/); assert.equal(normalizeTacticalDiagram(generateTacticalDiagram(baseExercise))?.version, 1); });
test("Tactical Board V2: coordinate e azioni non vengono mutate dal renderer", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); assert.match(renderer, /const renderY = \(value: number\) => 100 - value/); assert.doesNotMatch(renderer, /diagram\.elements\.(push|splice)|diagram\.actions\.(push|splice)/); assert.match(renderer, /item\.startX/); assert.match(renderer, /renderY\(item\.startY\)/); });
test("Tactical Board V2: porta e area sono sul lato superiore", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); assert.match(renderer, /goalLineY: 12/); assert.match(renderer, /goalDepthY: 5/); assert.match(renderer, /v2-primary-goal/); assert.match(renderer, /v2-goal-area/); });
test("Tactical Board V2: simboli professionali coprono tutti gli elementi", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); for (const component of ["TacticalGoalkeeper", "TacticalAttacker", "TacticalPlayer", "TacticalCoach", "TacticalBall", "TacticalCone", "TacticalMannequin", "TacticalHurdle", "TacticalMiniGoal", "TacticalMarker"]) assert.match(renderer, new RegExp(`function ${component}`)); assert.match(renderer, /v2-ball/); assert.match(renderer, /v2-goalkeeper/); });
test("Tactical Board V2: azioni usano palette e stili funzionali", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); assert.match(renderer, /action\.type === "tiro"/); assert.match(renderer, /action\.type === "tuffo"/); assert.match(renderer, /action\.type === "passaggio" \|\| action\.type === "cross"/); assert.match(renderer, /action\.type === "conduzione"/); assert.match(renderer, /strokeDasharray=\{appearance\.dash\}/); });
test("Tactical Board V2: badge sequenza e label brevi restano leggibili", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); assert.match(renderer, /function TacticalSequenceBadge/); assert.match(renderer, /v2-element-label/); assert.match(renderer, /explicit\.length <= 3/); assert.doesNotMatch(renderer, /showActionLabels = true/); });
test("Tactical Board V2: ghost deriva dalle azioni senza aggiungere JSON", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); assert.match(renderer, /function TacticalGhosts/); assert.match(renderer, /x: item\.endX, y: item\.endY/); assert.match(renderer, /ghost \? \.28 : 1/); assert.match(renderer, /diagram\.elements\.length > 7/); });
test("Tactical Board V2: preview compatta riduce ghost rete e ombre", () => { const renderer = source("../app/components/tactical-board-v2.tsx"); const css = source("../app/globals.css"); assert.match(renderer, /compact-board\|session-board/); assert.match(renderer, /!compact &&/); assert.match(css, /is-compact \.v2-ghost-positions\{display:none\}/); });
test("Tactical Board V2: editor confronta V1 e V2 con lo stesso JSON", () => { const editor = source("../app/components/tactical-diagram-editor.tsx"); assert.match(editor, /rendererVersion="v1"/); assert.match(editor, /rendererVersion="v2"/); assert.match(editor, /diagram=\{diagram\}/); assert.match(editor, /localhost/); });
test("Tactical Board V2: confronto copre quindici tipologie automatiche", () => { const cases: Partial<Exercise>[] = [
  { nome: "Tuffo laterale" }, { nome: "Reattività su stimolo" }, { nome: "Tiro frontale" }, { nome: "Presa su passaggio", descrizione: "Il preparatore passa al portiere" }, { nome: "Cross da sinistra" }, { nome: "Uscita alta" }, { nome: "Uscita bassa" }, { nome: "1 contro 1" }, { nome: "Tecnica di piede" }, { nome: "Seconda palla" }, { nome: "Reattività con coni", descrizione: "Slalom tra coni" }, { nome: "Parata con sagoma", descrizione: "La sagoma crea disturbo" }, { nome: "Tuffo con ostacolo", descrizione: "Supera un ostacolo e interviene" }, { nome: "Presa semplice" }, { nome: "Match Simulation complesso", descrizione: "Tiratore, appoggio, coni, sagoma e ostacolo" },
  ]; for (const patch of cases) { const diagram = generateTacticalDiagram(exercise(patch)); assert.equal(diagram.version, 1); assert.ok(diagram.elements.length > 0); assert.ok(diagram.actions.length > 0); } });
test("Tactical Board V2: responsive resta disponibile su catalogo seduta campo ed editor", () => { const css = source("../app/globals.css"); assert.match(css, /@media\(max-width:780px\)/); assert.match(source("../app/components/exercise-card.tsx"), /ExerciseTacticalBoard/); assert.match(source("../app/components/session-exercise-card.tsx"), /ExerciseTacticalBoard/); assert.match(source("../app/components/session-field-mode.tsx"), /ExerciseTacticalBoard/); assert.match(source("../app/components/tactical-diagram-editor.tsx"), /ExerciseTacticalBoard/); });
