import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { classifyTacticalFamilyHealth, createLegacyTacticalCatalogAudit, createTacticalAuditDiagnostic, createTacticalCatalogAudit, diagnoseTacticalCollisions, selectCatalogAuditSample, summarizeTacticalAudit, summarizeTacticalWarningCauses } from "../lib/tactical-catalog-audit.ts";
import type { TacticalDiagram } from "../lib/types.ts";
import type { Exercise } from "../lib/types.ts";

const exercise=(index:number,patch:Partial<Exercise>={}):Exercise=>({id:`audit-${index}`,codice:`GK-AUD-${String(index).padStart(3,"0")}`,nome:`Esercizio ${index}`,category_id:1,subcategory_id:1,categoria:index%2?"Tecnica":"Situazionale",sottocategoria:"Test",fase:"Analitico",obiettivo:"Audit",descrizione:"Presa frontale",durata_min:10,portieri_min:1,portieri_max:2,intensita:"Media",difficolta:2,materiale:"Palloni",variante:null,coaching_points:"",errori_comuni:"",schema_step_1:null,schema_step_2:null,schema_step_3:null,schema_step_4:null,schema_step_5:null,schema_step_6:null,scenario_gara:null,numero_azioni:null,schema_url:null,foto_url:null,attivo:true,...patch});
const source=(path:string)=>readFileSync(new URL(path,import.meta.url),"utf8");

test("audit catalogo: seleziona al massimo trenta esercizi reali e diversifica",()=>{const records=Array.from({length:45},(_,index)=>exercise(index+1,index%6===0?{nome:"Cross",descrizione:"Cross con uscita alta"}:index%5===0?{nome:"Seconda palla",descrizione:"Il tiratore conclude e l'appoggio serve la seconda palla"}:index%4===0?{nome:"Slalom",descrizione:"Slalom tra 5 cinesini"}:{})),sample=selectCatalogAuditSample(records,30);assert.equal(sample.length,30);assert.ok(new Set(sample.map(item=>item.nome)).size>2);assert.ok(new Set(sample.map(item=>item.categoria)).size>1);});
test("audit catalogo: quality score e validazioni sono solo calcolati in memoria",()=>{const item=createTacticalCatalogAudit(exercise(1,{nome:"Cross",descrizione:"Il servitore effettua un cross"}));assert.ok(item.qualityScore>=0&&item.qualityScore<=100);assert.ok(["VALID","VALID_WITH_WARNINGS","NEEDS_REVIEW"].includes(item.status));assert.ok(item.diagram.elements.length>0);});
test("audit catalogo: preview manuale è marcata e non sovrascritta",()=>{const original=exercise(2,{diagram_source:"manual"}),item=createTacticalCatalogAudit(original);assert.equal(item.alternativePreview,true);assert.equal(original.tactical_diagram,undefined);});
test("audit catalogo: statistiche sommano stati famiglie ed equipment",()=>{const items=[createTacticalCatalogAudit(exercise(1,{nome:"Cross",descrizione:"Cross da sinistra"})),createTacticalCatalogAudit(exercise(2,{nome:"Slalom",descrizione:"Slalom tra 5 cinesini"}))],summary=summarizeTacticalAudit(items);assert.equal(summary.total,2);assert.equal(summary.valid+summary.warnings+summary.review,2);assert.ok(summary.families.length>=1);assert.ok(summary.equipment.some(row=>row.tag==="CINESINI"&&row.total===1));});
test("audit catalogo: equipment dichiarato inutilizzato resta INFO e non abbassa quality",()=>{const clean=createTacticalCatalogAudit(exercise(1,{nome:"Cross",descrizione:"Il preparatore effettua un cross",materiale:"Palloni"})),withStock=createTacticalCatalogAudit(exercise(2,{nome:"Cross",descrizione:"Il preparatore effettua un cross",materiale:"10 palloni, 8 coni, 2 sagome"}));assert.equal(withStock.status,clean.status);assert.equal(withStock.qualityScore,clean.qualityScore);assert.equal(withStock.warnings.length,clean.warnings.length);assert.ok(withStock.infos.length>clean.infos.length);});
test("audit catalogo: riepilogo separa pattern reali e informazioni",()=>{const item=createTacticalCatalogAudit(exercise(1,{materiale:"8 coni",descrizione:"Presa frontale"})),summary=summarizeTacticalAudit([item]);assert.equal(summary.patterns.some(([reason])=>/Coni.*dichiarati/i.test(reason)),false);assert.ok(summary.infoPatterns.some(([reason])=>/Coni.*dichiarati/i.test(reason)));});
test("regression gate: MATCH_SIMULATION, DIVE e HIGH_CLAIM restano baseline valide",()=>{
  const baseline:Exercise[]=[
    exercise(101,{nome:"Match Simulation seconda palla",categoria:"Match Simulation",descrizione:"Il tiratore conclude, il portiere recupera e un appoggio serve la seconda palla."}),
    exercise(102,{nome:"Match Simulation transizione",categoria:"Match Simulation",descrizione:"Scenario aperto: il tiratore conclude, il portiere recupera e un compagno serve la seconda palla."}),
    exercise(103,{nome:"Sequenza gara seconda palla",categoria:"Match Simulation",descrizione:"Sequenza gara con tiro, recupero e seconda palla servita dall'appoggio."}),
    exercise(104,{nome:"Tuffo laterale destro",categoria:"Tuffi laterali",descrizione:"Il tiratore conclude lateralmente e il portiere esegue un tuffo."}),
    exercise(105,{nome:"Tuffo laterale sinistro",categoria:"Tuffi laterali",descrizione:"Il tiratore conclude sul lato sinistro e il portiere esegue un tuffo."}),
    exercise(106,{nome:"Parata ravvicinata",categoria:"Parate",descrizione:"Il tiratore conclude da distanza ravvicinata e il portiere interviene."}),
    exercise(107,{nome:"Uscita alta su cross",categoria:"Uscite alte",descrizione:"Il servitore effettua un cross e il portiere interviene in presa alta."}),
    exercise(108,{nome:"Uscita alta su palla aerea",categoria:"Uscite alte",descrizione:"Il servitore gioca una palla alta e il portiere interviene in uscita alta."}),
  ];
  const audited=baseline.map(createTacticalCatalogAudit),byFamily=(family:string)=>audited.filter(item=>item.family===family);
  assert.deepEqual(byFamily("MATCH_SIMULATION").map(item=>item.status),["VALID","VALID","VALID"]);
  assert.deepEqual(byFamily("DIVE").map(item=>item.status),["VALID","VALID","VALID"]);
  assert.deepEqual(byFamily("HIGH_CLAIM").map(item=>item.status),["VALID","VALID"]);
});
test("diagnostic view: espone pipeline, action sources e origine palla mancante",()=>{const item=createTacticalCatalogAudit(exercise(1,{nome:"Seconda palla",descrizione:"Il tiratore conclude e l'appoggio serve la seconda palla",materiale:"10 palloni"})),diagnostic=createTacticalAuditDiagnostic(item);assert.equal(diagnostic.expectedBallOrigins,2);assert.ok(diagnostic.generatedActions.every(action=>action.confidence>=0&&action.confidence<=1));assert.ok(diagnostic.pipelineStage.length>0);assert.equal(diagnostic.validation.status,item.status);});
test("diagnostic view: distingue intersezioni attese e interferenze visive",()=>{const diagram:TacticalDiagram={version:1,canvas:{viewType:"penalty_area",widthRatio:16,heightRatio:10},elements:[{id:"gk",type:"goalkeeper",x:50,y:30,rotation:0,scale:1,role:"GK"},{id:"cone",type:"cone",x:50,y:50,rotation:0,scale:1,role:"Cono"},{id:"ball",type:"ball",x:50,y:80,rotation:0,scale:1,role:"Palla"}],actions:[{id:"shot",type:"tiro",fromElementId:"ball",toElementId:"gk",startX:50,startY:80,endX:50,endY:30,sequence:1}]},collisions=diagnoseTacticalCollisions(exercise(1,{descrizione:"Il tiratore effettua un tiro"}),diagram),visual=collisions.filter(item=>item.category==="VISUAL_INTERFERENCE"),expected=collisions.filter(item=>item.category==="EXPECTED_INTERSECTION");assert.equal(visual.length,1);assert.equal(visual[0].elementId,"cone");assert.equal(visual[0].severity,"MAJOR");assert.equal(expected.length,2);});
test("multi-phase: seconda palla indipendente usa due palloni senza inventare un secondo servitore",()=>{const item=createTacticalCatalogAudit(exercise(201,{nome:"Doppio intervento + seconda palla",descrizione:"Il tiratore serve una prima conclusione, recupero e seconda palla.",materiale:"8 palloni"})),balls=item.diagram.elements.filter(value=>value.type==="ball"),servers=item.diagram.elements.filter(value=>value.type==="coach"||value.type==="attacker"||value.type==="player");assert.equal(item.family,"DOUBLE_SAVE");assert.equal(balls.length,2);assert.equal(servers.length,1);assert.equal(item.relationValidation.valid,true);});
test("multi-phase: palla vagante resta derivata dalla prima e non inventa BALL_B",()=>{const item=createTacticalCatalogAudit(exercise(202,{nome:"Prima parata + palla vagante",descrizione:"Dopo la prima parata il portiere recupera sulla palla vagante.",materiale:"8 palloni"})),balls=item.diagram.elements.filter(value=>value.type==="ball");assert.equal(item.family,"SECOND_BALL");assert.equal(balls.length,1);assert.equal(item.diagram.actions.length,3);assert.equal(item.relationValidation.valid,true);});
test("multi-phase: REACTION separa stimolo e movimento senza trasformare muoversi in over",()=>{const item=createTacticalCatalogAudit(exercise(203,{nome:"Stimolo colore avanti stop",descrizione:"Al comando colore il portiere deve muoversi, reagire e recuperare."}));assert.equal(item.family,"REACTION");assert.equal(item.diagram.elements.some(value=>value.type==="hurdle"),false);assert.equal(item.diagram.actions[0].type,"movimento");assert.equal(item.status==="NEEDS_REVIEW",false);});
test("collision taxonomy: due palloni distinti sovrapposti sono una REAL_COLLISION",()=>{const diagram:TacticalDiagram={version:1,canvas:{viewType:"penalty_area",widthRatio:16,heightRatio:10},elements:[{id:"ball-a",type:"ball",x:50,y:50,rotation:0,scale:1},{id:"ball-b",type:"ball",x:50,y:50,rotation:0,scale:1}],actions:[]},collisions=diagnoseTacticalCollisions(exercise(204),diagram);assert.equal(collisions.length,1);assert.equal(collisions[0].category,"REAL_COLLISION");assert.equal(collisions[0].kind,"ELEMENT_ELEMENT");});
test("regression gate: nessun caso precedentemente VALID diventa NEEDS_REVIEW",()=>{const cases=[exercise(205,{nome:"Seconda palla con appoggio",descrizione:"Il tiratore conclude, recupero e seconda palla servita dall'appoggio."}),exercise(206,{nome:"Doppio intervento",descrizione:"Il tiratore serve due palloni con recupero tra primo e secondo intervento."}),exercise(207,{nome:"Stimolo colore",descrizione:"Al segnale colore il portiere reagisce e si muove a destra o sinistra."})];for(const value of cases){const before=createLegacyTacticalCatalogAudit(value),after=createTacticalCatalogAudit(value);if(before.status==="VALID")assert.notEqual(after.status,"NEEDS_REVIEW");}});
test("multi-phase: schemi manual e automatic_edited non ricevono la nuova composizione",()=>{for(const source of ["manual","automatic_edited"] as const){const value=exercise(208,{nome:"Seconda palla",descrizione:"Prima conclusione, recupero e seconda palla.",diagram_source:source}),before=createLegacyTacticalCatalogAudit(value),after=createTacticalCatalogAudit(value);assert.deepEqual(after.diagram,before.diagram);}});
test("diagnostic view: family health deriva dai dati e warning raggruppati per causa",()=>{assert.equal(classifyTacticalFamilyHealth({total:3,valid:3,warnings:0,review:0}),"STABLE");assert.equal(classifyTacticalFamilyHealth({total:3,valid:1,warnings:2,review:0}),"ATTENTION");assert.equal(classifyTacticalFamilyHealth({total:3,valid:2,warnings:0,review:1}),"CRITICAL");const warning=createTacticalCatalogAudit(exercise(1,{nome:"Tema",descrizione:"Presa frontale"}));warning.status="VALID_WITH_WARNINGS";warning.warnings=["1 collisioni tra actions ed elementi non coinvolti"];assert.equal(summarizeTacticalWarningCauses([warning])[0].cause,"COLLISION");});
test("diagnostic view: pagina DEV offre i tre toggle senza modificare renderer",()=>{const page=source("../app/dev/tactical-catalog-audit/page.tsx"),renderer=source("../app/components/tactical-board-v2-refined.tsx");assert.match(page,/DIAGNOSTIC VIEW/);assert.match(page,/SHOW DIAGNOSTICS/);assert.match(page,/SHOW COLLISIONS/);assert.match(page,/SHOW ACTION SOURCES/);assert.doesNotMatch(renderer,/diagnostic-collision-overlay/);});
test("marker tecnici: production hidden e debug esplicito",()=>{const renderer=source("../app/components/tactical-board-v2-refined.tsx"),css=source("../app/globals.css"),comparison=source("../app/dev/tactical-technical-markers/page.tsx");assert.match(renderer,/showTechnicalMarkers=false/);assert.match(renderer,/v2r-technical-markers/);assert.match(css,/\.v2r-technical-markers\{display:none\}/);assert.match(css,/\.show-technical-markers \.v2r-technical-markers\{display:block\}/);assert.match(comparison,/WITHOUT TECHNICAL MARKERS/);});
test("badge chiari: numero usa contrasto scuro e non viene scambiato per marker",()=>{const renderer=source("../app/components/tactical-board-v2-refined.tsx");assert.match(renderer,/const light=\[/);assert.match(renderer,/fill=\{light\?"#101914":"#fff"\}/);});
