import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { classifyTacticalFamilyHealth, createLegacyTacticalCatalogAudit, createTacticalAuditDiagnostic, createTacticalCatalogAudit, diagnoseTacticalCollisions, selectCatalogAuditSample, summarizeTacticalAudit, summarizeTacticalWarningCauses } from "../lib/tactical-catalog-audit.ts";
import { createLargeCatalogAuditReport, DEFAULT_LARGE_AUDIT_SEED, selectLargeCatalogAuditSample } from "../lib/tactical-large-audit.ts";
import { createFullCatalogAuditReport, createFullCatalogAuditResult, fullAuditExportRows, selectRandomValidForHumanReview } from "../lib/tactical-full-audit.ts";
import { createSemanticGapAuditReport } from "../lib/tactical-semantic-gap-audit.ts";
import { createCatalogBackup, createCatalogWriteBatches, createCatalogWriteDryRun, createCatalogWriteLog, decideCatalogWrite, type CatalogWriteExercise } from "../lib/tactical-catalog-write-plan.ts";
import type { TacticalDiagram } from "../lib/types.ts";
import type { Exercise } from "../lib/types.ts";

const exercise=(index:number,patch:Partial<Exercise>={}):Exercise=>({id:`audit-${index}`,codice:`GK-AUD-${String(index).padStart(3,"0")}`,nome:`Esercizio ${index}`,category_id:1,subcategory_id:1,categoria:index%2?"Tecnica":"Situazionale",sottocategoria:"Test",fase:"Analitico",obiettivo:"Audit",descrizione:"Presa frontale",durata_min:10,portieri_min:1,portieri_max:2,intensita:"Media",difficolta:2,materiale:"Palloni",variante:null,coaching_points:"",errori_comuni:"",schema_step_1:null,schema_step_2:null,schema_step_3:null,schema_step_4:null,schema_step_5:null,schema_step_6:null,scenario_gara:null,numero_azioni:null,attivo:true,...patch});
const source=(path:string)=>readFileSync(new URL(path,import.meta.url),"utf8");

test("audit catalogo: seleziona al massimo trenta esercizi reali e diversifica",()=>{const records=Array.from({length:45},(_,index)=>exercise(index+1,index%6===0?{nome:"Cross",descrizione:"Cross con uscita alta"}:index%5===0?{nome:"Seconda palla",descrizione:"Il tiratore conclude e l'appoggio serve la seconda palla"}:index%4===0?{nome:"Slalom",descrizione:"Slalom tra 5 cinesini"}:{})),sample=selectCatalogAuditSample(records,30);assert.equal(sample.length,30);assert.ok(new Set(sample.map(item=>item.nome)).size>2);assert.ok(new Set(sample.map(item=>item.categoria)).size>1);});
test("audit catalogo: quality score e validazioni sono solo calcolati in memoria",()=>{const item=createTacticalCatalogAudit(exercise(1,{nome:"Cross",descrizione:"Il servitore effettua un cross"}));assert.ok(item.qualityScore>=0&&item.qualityScore<=100);assert.ok(["VALID","VALID_WITH_WARNINGS","NEEDS_REVIEW"].includes(item.status));assert.ok(item.diagram.elements.length>0);});
test("audit catalogo: preview manuale è marcata e non sovrascritta",()=>{const original=exercise(2,{diagram_source:"manual"}),item=createTacticalCatalogAudit(original);assert.equal(item.alternativePreview,true);assert.equal(original.tactical_diagram,undefined);});
test("audit catalogo: statistiche sommano stati famiglie ed equipment",()=>{const items=[createTacticalCatalogAudit(exercise(1,{nome:"Cross",descrizione:"Cross da sinistra"})),createTacticalCatalogAudit(exercise(2,{nome:"Slalom",descrizione:"Slalom tra 5 cinesini"}))],summary=summarizeTacticalAudit(items);assert.equal(summary.total,2);assert.equal(summary.valid+summary.warnings+summary.review,2);assert.ok(summary.families.length>=1);assert.ok(summary.equipment.some(row=>row.tag==="CINESINI"&&row.total===1));});
test("audit catalogo: equipment dichiarato inutilizzato resta INFO e non abbassa quality",()=>{const clean=createTacticalCatalogAudit(exercise(1,{nome:"Cross",descrizione:"Il preparatore effettua un cross",materiale:"Palloni"})),withStock=createTacticalCatalogAudit(exercise(2,{nome:"Cross",descrizione:"Il preparatore effettua un cross",materiale:"10 palloni, 8 coni, 2 sagome"}));assert.equal(withStock.status,clean.status);assert.equal(withStock.qualityScore,clean.qualityScore);assert.equal(withStock.warnings.length,clean.warnings.length);assert.ok(withStock.infos.length>clean.infos.length);});
test("audit catalogo: riepilogo separa pattern reali e informazioni",()=>{const item=createTacticalCatalogAudit(exercise(1,{materiale:"8 coni",descrizione:"Presa frontale"})),summary=summarizeTacticalAudit([item]);assert.equal(summary.patterns.some(([reason])=>/Coni.*dichiarati/i.test(reason)),false);assert.ok(summary.infoPatterns.some(([reason])=>/Coni.*dichiarati/i.test(reason)));});
test("regression gate: MATCH_SIMULATION, DIVE e HIGH_CLAIM restano baseline valide",()=>{
  const baseline:Exercise[]=[
    exercise(101,{nome:"Match Simulation seconda palla",categoria:"Match Simulation",descrizione:"Il tiratore conclude, il portiere recupera e un appoggio serve la seconda palla."}),
    exercise(102,{nome:"Match Simulation transizione",categoria:"Match Simulation",descrizione:"Scenario aperto: il tiratore conclude, il portiere recupera e un compagno serve la seconda palla."}),
    exercise(103,{nome:"Sequenza gara seconda palla",categoria:"Match Simulation",descrizione:"Sequenza gara con tiro, recupero e seconda palla servita dall'appoggio."}),
    exercise(104,{nome:"Tuffo laterale destro",categoria:"Tuffi laterali",descrizione:"Il tiratore conclude lateralmente e il portiere esegue un tuffo."}),
    exercise(105,{nome:"Tuffo laterale sinistro",categoria:"Tuffi laterali",descrizione:"Il tiratore conclude sul lato sinistro e il portiere esegue un tuffo."}),
    exercise(106,{nome:"Parata ravvicinata",categoria:"Parate",descrizione:"Il tiratore conclude da distanza ravvicinata e il portiere interviene."}),
    exercise(107,{nome:"Uscita alta su cross",categoria:"Uscite alte",descrizione:"Il servitore effettua un cross e il portiere interviene in presa alta."}),
    exercise(108,{nome:"Uscita alta su palla aerea",categoria:"Uscite alte",descrizione:"Il servitore gioca una palla alta e il portiere interviene in uscita alta."}),
  ];
  const audited=baseline.map(createTacticalCatalogAudit),byFamily=(family:string)=>audited.filter(item=>item.family===family);
  assert.deepEqual(byFamily("MATCH_SIMULATION").map(item=>item.status),["VALID","VALID","VALID"]);
  assert.deepEqual(byFamily("DIVE").map(item=>item.status),["VALID","VALID","VALID"]);
  assert.deepEqual(byFamily("HIGH_CLAIM").map(item=>item.status),["VALID","VALID"]);
});
test("diagnostic view: espone pipeline, action sources e origine palla mancante",()=>{const item=createTacticalCatalogAudit(exercise(1,{nome:"Seconda palla",descrizione:"Il tiratore conclude e l'appoggio serve la seconda palla",materiale:"10 palloni"})),diagnostic=createTacticalAuditDiagnostic(item);assert.equal(diagnostic.expectedBallOrigins,2);assert.ok(diagnostic.generatedActions.every(action=>action.confidence>=0&&action.confidence<=1));assert.ok(diagnostic.pipelineStage.length>0);assert.equal(diagnostic.validation.status,item.status);});
test("diagnostic view: distingue intersezioni attese e interferenze visive",()=>{const diagram:TacticalDiagram={version:1,canvas:{viewType:"penalty_area",widthRatio:16,heightRatio:10},elements:[{id:"gk",type:"goalkeeper",x:50,y:30,rotation:0,scale:1,role:"GK"},{id:"cone",type:"cone",x:50,y:50,rotation:0,scale:1,role:"Cono"},{id:"ball",type:"ball",x:50,y:80,rotation:0,scale:1,role:"Palla"}],actions:[{id:"shot",type:"tiro",fromElementId:"ball",toElementId:"gk",startX:50,startY:80,endX:50,endY:30,sequence:1}]},collisions=diagnoseTacticalCollisions(exercise(1,{descrizione:"Il tiratore effettua un tiro"}),diagram),visual=collisions.filter(item=>item.category==="VISUAL_INTERFERENCE"),expected=collisions.filter(item=>item.category==="EXPECTED_INTERSECTION");assert.equal(visual.length,1);assert.equal(visual[0].elementId,"cone");assert.equal(visual[0].severity,"MAJOR");assert.equal(expected.length,2);});
test("multi-phase: seconda palla indipendente usa due palloni senza inventare un secondo servitore",()=>{const item=createTacticalCatalogAudit(exercise(201,{nome:"Doppio intervento + seconda palla",descrizione:"Il tiratore serve una prima conclusione, recupero e seconda palla.",materiale:"8 palloni"})),balls=item.diagram.elements.filter(value=>value.type==="ball"),servers=item.diagram.elements.filter(value=>value.type==="coach"||value.type==="attacker"||value.type==="player");assert.equal(item.family,"DOUBLE_SAVE");assert.equal(balls.length,2);assert.equal(servers.length,1);assert.equal(item.relationValidation.valid,true);});
test("multi-phase: palla vagante resta derivata dalla prima e non inventa BALL_B",()=>{const item=createTacticalCatalogAudit(exercise(202,{nome:"Prima parata + palla vagante",descrizione:"Dopo la prima parata il portiere recupera sulla palla vagante.",materiale:"8 palloni"})),balls=item.diagram.elements.filter(value=>value.type==="ball");assert.equal(item.family,"SECOND_BALL");assert.equal(balls.length,1);assert.equal(item.diagram.actions.length,3);assert.equal(item.relationValidation.valid,true);});
test("multi-phase: REACTION separa stimolo e movimento senza trasformare muoversi in over",()=>{const item=createTacticalCatalogAudit(exercise(203,{nome:"Stimolo colore avanti stop",descrizione:"Al comando colore il portiere deve muoversi, reagire e recuperare."}));assert.equal(item.family,"REACTION");assert.equal(item.diagram.elements.some(value=>value.type==="hurdle"),false);assert.equal(item.diagram.actions[0].type,"movimento");assert.equal(item.status==="NEEDS_REVIEW",false);});
test("collision taxonomy: due palloni distinti sovrapposti sono una REAL_COLLISION",()=>{const diagram:TacticalDiagram={version:1,canvas:{viewType:"penalty_area",widthRatio:16,heightRatio:10},elements:[{id:"ball-a",type:"ball",x:50,y:50,rotation:0,scale:1},{id:"ball-b",type:"ball",x:50,y:50,rotation:0,scale:1}],actions:[]},collisions=diagnoseTacticalCollisions(exercise(204),diagram);assert.equal(collisions.length,1);assert.equal(collisions[0].category,"REAL_COLLISION");assert.equal(collisions[0].kind,"ELEMENT_ELEMENT");});
test("regression gate: nessun caso precedentemente VALID diventa NEEDS_REVIEW",()=>{const cases=[exercise(205,{nome:"Seconda palla con appoggio",descrizione:"Il tiratore conclude, recupero e seconda palla servita dall'appoggio."}),exercise(206,{nome:"Doppio intervento",descrizione:"Il tiratore serve due palloni con recupero tra primo e secondo intervento."}),exercise(207,{nome:"Stimolo colore",descrizione:"Al segnale colore il portiere reagisce e si muove a destra o sinistra."})];for(const value of cases){const before=createLegacyTacticalCatalogAudit(value),after=createTacticalCatalogAudit(value);if(before.status==="VALID")assert.notEqual(after.status,"NEEDS_REVIEW");}});
test("multi-phase: schemi manual e automatic_edited non ricevono la nuova composizione",()=>{for(const source of ["manual","automatic_edited"] as const){const value=exercise(208,{nome:"Seconda palla",descrizione:"Prima conclusione, recupero e seconda palla.",diagram_source:source}),before=createLegacyTacticalCatalogAudit(value),after=createTacticalCatalogAudit(value);assert.deepEqual(after.diagram,before.diagram);}});
test("diagnostic view: family health deriva dai dati e warning raggruppati per causa",()=>{assert.equal(classifyTacticalFamilyHealth({total:3,valid:3,warnings:0,review:0}),"STABLE");assert.equal(classifyTacticalFamilyHealth({total:3,valid:1,warnings:2,review:0}),"ATTENTION");assert.equal(classifyTacticalFamilyHealth({total:3,valid:2,warnings:0,review:1}),"CRITICAL");const warning=createTacticalCatalogAudit(exercise(1,{nome:"Tema",descrizione:"Presa frontale"}));warning.status="VALID_WITH_WARNINGS";warning.warnings=["1 collisioni tra actions ed elementi non coinvolti"];assert.equal(summarizeTacticalWarningCauses([warning])[0].cause,"COLLISION");});
test("diagnostic view: pagina DEV offre i tre toggle senza modificare renderer",()=>{const page=source("../app/dev/tactical-catalog-audit/page.tsx"),renderer=source("../app/components/tactical-board-v2-refined.tsx");assert.match(page,/DIAGNOSTIC VIEW/);assert.match(page,/SHOW DIAGNOSTICS/);assert.match(page,/SHOW COLLISIONS/);assert.match(page,/SHOW ACTION SOURCES/);assert.doesNotMatch(renderer,/diagnostic-collision-overlay/);});
test("marker tecnici: production hidden e debug esplicito",()=>{const renderer=source("../app/components/tactical-board-v2-refined.tsx"),css=source("../app/globals.css"),comparison=source("../app/dev/tactical-technical-markers/page.tsx");assert.match(renderer,/showTechnicalMarkers=false/);assert.match(renderer,/v2r-technical-markers/);assert.match(css,/\.v2r-technical-markers\{display:none\}/);assert.match(css,/\.show-technical-markers \.v2r-technical-markers\{display:block\}/);assert.match(comparison,/WITHOUT TECHNICAL MARKERS/);});
test("badge chiari: numero usa contrasto scuro e non viene scambiato per marker",()=>{const renderer=source("../app/components/tactical-board-v2-refined.tsx");assert.match(renderer,/const light=\[/);assert.match(renderer,/fill=\{light\?"#101914":"#fff"\}/);});
test("large audit: campione stratificato di 150 esercizi è riproducibile con seed",()=>{const records=Array.from({length:180},(_,index)=>exercise(index+1,index%6===0?{categoria:"Uscite alte",sottocategoria:"Cross",nome:`Cross ${index}`,descrizione:"Cross con uscita alta",materiale:"Palloni, coni"}:index%5===0?{categoria:"Situazionale",nome:`Seconda palla ${index}`,descrizione:"Conclusione, recupero e seconda palla",materiale:"Palloni"}:index%4===0?{categoria:"Tecnica podalica",nome:`Passaggio ${index}`,descrizione:"Passaggio in una delle due porticine laterali",materiale:"Palloni, 2 porticine"}:{categoria:"Tecnica presa",nome:`Presa ${index}`})),first=selectLargeCatalogAuditSample(records,DEFAULT_LARGE_AUDIT_SEED),again=selectLargeCatalogAuditSample(records,DEFAULT_LARGE_AUDIT_SEED),other=selectLargeCatalogAuditSample(records,"2026-08-LARGE-02");assert.equal(first.length,150);assert.deepEqual(first.map(item=>item.codice),again.map(item=>item.codice));assert.notDeepEqual(first.map(item=>item.codice),other.map(item=>item.codice));assert.ok(new Set(first.map(item=>item.categoria)).size>=4);});
test("large audit: se il catalogo è inferiore a 150 analizza tutti gli esercizi",()=>{const records=Array.from({length:42},(_,index)=>exercise(index+1)),sample=selectLargeCatalogAuditSample(records);assert.equal(sample.length,42);assert.deepEqual(sample.map(item=>item.codice),records.map(item=>item.codice).sort());});
test("large audit: report aggrega stati, famiglie, complessità, equipment e collisioni",()=>{const records=[exercise(301,{nome:"Cross",descrizione:"Cross da sinistra",materiale:"Palloni"}),exercise(302,{nome:"Slalom",descrizione:"Slalom tra 5 cinesini",materiale:"5 cinesini"}),exercise(303,{nome:"Seconda palla",descrizione:"Conclusione, recupero e seconda palla",materiale:"Palloni"})],items=records.map(createTacticalCatalogAudit),report=createLargeCatalogAuditReport(records.length,items);assert.equal(report.analyzed,3);assert.equal(report.summary.valid+report.summary.warnings+report.summary.review,3);assert.equal(report.percentages.valid+report.percentages.warning+report.percentages.review,100);assert.equal(report.complexity.reduce((sum,row)=>sum+row.tested,0),3);assert.ok(report.families.length>=2);assert.ok(report.equipment.some(row=>row.tag==="CINESINI"&&row.recognized===1));assert.ok(report.semanticCoverage>=0&&report.semanticCoverage<=100);});
test("large audit: non modifica esercizi o tactical_diagram e seleziona validi deterministici",()=>{const diagram:TacticalDiagram={version:1,canvas:{viewType:"penalty_area",widthRatio:16,heightRatio:10},elements:[],actions:[]},records=Array.from({length:24},(_,index)=>exercise(index+401,{tactical_diagram:diagram})),snapshot=JSON.stringify(records),items=records.map(createTacticalCatalogAudit),first=createLargeCatalogAuditReport(records.length,items,"seed-fixed"),second=createLargeCatalogAuditReport(records.length,items,"seed-fixed");assert.equal(JSON.stringify(records),snapshot);assert.deepEqual(first.randomValid.map(item=>item.exercise.codice),second.randomValid.map(item=>item.exercise.codice));});
test("large audit: pagina DEV espone seed, KPI e campioni di ispezione",()=>{const page=source("../app/dev/tactical-catalog-audit/page.tsx");assert.match(page,/LARGE SAMPLE AUDIT/);assert.match(page,/AUDIT SEED/);assert.match(page,/TOP 20 WORST CASES/);assert.match(page,/20 RANDOM VALID/);assert.match(page,/Nessun diagramma viene salvato/);});
test("semantic gap audit: unisce Generic, Review e Medium senza duplicati",()=>{const items=[createTacticalCatalogAudit(exercise(501,{nome:"Tema libero",descrizione:"Circuito libero con compito variabile e soluzione scelta dal preparatore."})),createTacticalCatalogAudit(exercise(502,{nome:"Seconda palla",descrizione:"Prima conclusione, recupero e seconda palla servita dall'appoggio."})),createTacticalCatalogAudit(exercise(503,{nome:"Presa frontale",descrizione:"Presa frontale semplice."}))];items[1].status="NEEDS_REVIEW";items[1].errors=["Seconda origine di palla non materializzata"];const report=createSemanticGapAuditReport(items);assert.equal(report.target.length,new Set(report.target.map(value=>value.item.exercise.codice)).size);assert.ok(report.generic.length>=1);assert.ok(report.reviews.length>=1);assert.ok(report.target.some(value=>value.item.exercise.codice===items[1].exercise.codice));});
test("semantic gap audit: distingue mapping recuperato e tema realmente ambiguo",()=>{const mapped=createTacticalCatalogAudit(exercise(510,{categoria:"Tecnica 1v1 - copertura angoli",nome:"Scarico laterale",descrizione:"L'attaccante scarica lateralmente e il portiere riallinea la posizione."})),ambiguous=createTacticalCatalogAudit(exercise(511,{categoria:"Tema libero",nome:"Scenario scelto",descrizione:"Scenario scelto dal preparatore con compito variabile e soluzione libera per il gruppo."})),report=createSemanticGapAuditReport([mapped,ambiguous]);assert.equal(mapped.family,"ONE_V_ONE");assert.equal(report.generic.some(value=>value.item.exercise.codice===mapped.exercise.codice),false);assert.equal(report.generic.find(value=>value.item.exercise.codice===ambiguous.exercise.codice)?.generic?.recoverable,false);assert.equal(report.potentialCoverage,50);});
test("semantic gap audit: espone root cause, pipeline e proposta minima dei review",()=>{const item=createTacticalCatalogAudit(exercise(520,{nome:"Seconda palla",descrizione:"Conclusione, recupero e seconda palla."}));item.status="NEEDS_REVIEW";item.errors=["Le due fasi richiedono origini di palla distinte: attesi 2 ball"];const review=createSemanticGapAuditReport([item]).reviews[0];assert.match(review.diagnostic.rootCause,/origine di palla/i);assert.ok(review.diagnostic.pipelineStage.length>0);assert.equal(review.diagnostic.severity,"CRITICAL");assert.match(review.minimalFix,/BALL_A.*BALL_B/i);});
test("semantic gap audit: estrae wording solo dai testi reali e non muta i diagrammi",()=>{const records=[exercise(530,{nome:"Cambio ruolo portiere servente",descrizione:"Cambio ruolo portiere servente con soluzione libera."}),exercise(531,{nome:"Cambio ruolo portiere attaccante",descrizione:"Cambio ruolo portiere attaccante con soluzione libera."})],snapshot=JSON.stringify(records),report=createSemanticGapAuditReport(records.map(createTacticalCatalogAudit));assert.equal(JSON.stringify(records),snapshot);assert.ok(report.wording.some(row=>row.phrase.includes("cambio ruolo")));});

test("full catalog audit: analizza il 100% senza seed e senza mutare gli esercizi",()=>{const records=[exercise(601,{nome:"Cross",descrizione:"Cross da sinistra",materiale:"Palloni"}),exercise(602,{nome:"Tecnica di piede",descrizione:"Ricezione orientata e passaggio nella porticina",materiale:"Palloni, porticina"}),exercise(603,{nome:"Tema libero",descrizione:"Scenario personalizzabile scelto dal preparatore."})],before=JSON.stringify(records),report=createFullCatalogAuditReport(records);assert.equal(report.catalogSize,3);assert.equal(report.analyzed+report.notAnalyzed,3);assert.equal(report.results.length,3);assert.equal(JSON.stringify(records),before);assert.equal(report.durationMs>=0,true);assert.equal(report.semantic.specific+report.semantic.generic+report.semantic.unknown,report.analyzed);});

test("full catalog audit: generation error resta distinto da needs review",()=>{const value=exercise(610),broken={...value} as Exercise;Object.defineProperty(broken,"nome",{get(){throw new Error("boom pipeline");}});const result=createFullCatalogAuditResult(broken);assert.equal(result.status,"GENERATION_ERROR");assert.equal(result.kind,"GENERATION_ERROR");if(result.kind==="GENERATION_ERROR")assert.match(result.generationErrors[0],/boom pipeline/);});

test("full catalog audit: aggrega integrità, collisioni, equipment e complessità",()=>{const records=[exercise(620,{nome:"Seconda palla",descrizione:"Prima conclusione, recupero e seconda palla servita dall'appoggio.",materiale:"8 palloni"}),exercise(621,{nome:"Slalom",descrizione:"Slalom tra 5 cinesini e passaggio nella porticina.",materiale:"5 cinesini, 1 porticina, palloni"})],report=createFullCatalogAuditReport(records);assert.equal(report.complexity.reduce((sum,row)=>sum+row.total,0),2);assert.equal(report.families.reduce((sum,row)=>sum+row.total,0),2);assert.ok(report.equipment.some(row=>row.type==="marker"&&row.required>0));assert.equal(report.collisions.real.percentage>=0,true);assert.equal(report.successCriteria.integrity,report.analyzed===report.catalogSize);});

test("full catalog audit: export completo e random human review distribuito",()=>{const records=Array.from({length:40},(_,index)=>exercise(700+index,{nome:index%2?"Cross laterale":"Parata su tiro",descrizione:index%2?"Il preparatore effettua un cross laterale.":"Il tiratore conclude in porta."})),report=createFullCatalogAuditReport(records),rows=fullAuditExportRows(report),first=selectRandomValidForHumanReview(report,"set-a",30),second=selectRandomValidForHumanReview(report,"set-a",30);assert.equal(rows.length,40);assert.deepEqual(first.map(item=>item.exercise.codice),second.map(item=>item.exercise.codice));assert.ok(first.length<=30);assert.ok(rows.every(row=>"ball_integrity" in row&&"out_of_bounds" in row));});

type RemediationBaselineRow={code:string;family:string;status:string;quality:number;complexity:"LOW"|"MEDIUM"|"HIGH";real_collisions:number;visual_interferences:number;review_reasons:string[];ball_integrity:Record<string,number|unknown[]>;multi_phase_integrity:Record<string,number|boolean|unknown[]>;exercise_input:Exercise;diagram_snapshot:TacticalDiagram};
const finalNineBaseline=JSON.parse(source("./fixtures/tactical-final-9-baseline.json")) as {rows:RemediationBaselineRow[]},fullBaseline=JSON.parse(source("./fixtures/tactical-full-audit-baseline-468.json")) as {rows:RemediationBaselineRow[]},baselineByCode=new Map(finalNineBaseline.rows.map(row=>[row.code,row]));
const derivedMatchCodes=["GK-MS-005","GK-MS-012","GK-MS-016","GK-MS-019","GK-MS-021","GK-MS-029","GK-MS-047"];

for(const code of derivedMatchCodes)test(`final remediation ${code}: collega la respinta come previous action output`,()=>{const before=baselineByCode.get(code);assert.ok(before);assert.match(before.review_reasons.join(" "),/deriva dalla prima palla/i);const after=createFullCatalogAuditResult(before.exercise_input);assert.equal(after.kind,"SUCCESS");if(after.kind!=="SUCCESS")return;const ordered=after.audit.diagram.actions.slice().sort((a,b)=>a.sequence-b.sequence),first=ordered[0],transition=ordered.find(action=>action.type==="recupero"),second=ordered.find(action=>action.sequence>(transition?.sequence??1)&&action.type==="movimento");assert.equal(after.audit.diagram.elements.filter(element=>element.type==="ball").length,1);assert.equal(after.audit.diagram.elements.some(element=>element.role==="Appoggio"),false);assert.ok(first&&transition&&second);assert.equal(Math.hypot(second.startX-first.endX,second.startY-first.endY)<=18,true);assert.equal(after.ballIntegrity.unconnectedDerivedBall,0);assert.equal(after.ballIntegrity.ballWithoutSource,0);});

for(const code of ["GK-MS-021","GK-MS-029","GK-MS-047"])test(`final remediation ${code}: rimuove la collisione locale reale`,()=>{const before=baselineByCode.get(code);assert.ok(before);assert.equal(before.real_collisions,1);const after=createFullCatalogAuditResult(before.exercise_input);assert.equal(after.kind,"SUCCESS");if(after.kind==="SUCCESS")assert.equal(after.collisions.some(collision=>collision.category==="REAL_COLLISION"),false);});

test("final remediation GK-TLR-028: la variante opzionale non inventa BALL_B e mantiene il secondo stimolo",()=>{const before=baselineByCode.get("GK-TLR-028");assert.ok(before);assert.match(before.review_reasons.join(" "),/origini di palla distinte/i);const after=createFullCatalogAuditResult(before.exercise_input);assert.equal(after.kind,"SUCCESS");if(after.kind!=="SUCCESS")return;assert.equal(after.audit.diagram.elements.filter(element=>element.type==="ball").length,1);assert.deepEqual(after.audit.diagram.actions.map(action=>action.type),["tiro","tuffo","recupero","movimento"]);assert.equal(after.multiPhaseIntegrity.transitionMissing,0);assert.equal(after.ballIntegrity.missingSecondBall,0);});

test("final remediation GK-TLR-040: usa una sola palla, previous output e riallineamento",()=>{const before=baselineByCode.get("GK-TLR-040");assert.ok(before);assert.match(before.review_reasons.join(" "),/origini di palla distinte/i);const after=createFullCatalogAuditResult(before.exercise_input);assert.equal(after.kind,"SUCCESS");if(after.kind!=="SUCCESS")return;const actions=after.audit.diagram.actions.slice().sort((a,b)=>a.sequence-b.sequence);assert.deepEqual(actions.map(action=>action.type),["passaggio","movimento","tiro","tuffo"]);assert.equal(after.audit.diagram.elements.filter(element=>element.type==="ball").length,1);assert.equal(Math.hypot(actions[2].startX-actions[0].endX,actions[2].startY-actions[0].endY),0);assert.equal(after.ballIntegrity.ballWithoutSource,0);assert.equal(after.ballIntegrity.missingSecondBall,0);assert.equal(after.inactiveParticipantsRendered,0);});

test("final remediation: independent source e derived source restano semanticamente distinti",()=>{const independent=createFullCatalogAuditResult(exercise(900,{nome:"Seconda palla da appoggio",descrizione:"Il tiratore conclude, recupero e seconda palla servita dall'appoggio."})),derived=createFullCatalogAuditResult(exercise(901,{nome:"Respinta e palla vagante",descrizione:"Il tiratore conclude, il portiere respinge, recupera e interviene sulla palla vagante."}));assert.equal(independent.kind,"SUCCESS");assert.equal(derived.kind,"SUCCESS");if(independent.kind!=="SUCCESS"||derived.kind!=="SUCCESS")return;assert.equal(independent.audit.diagram.elements.filter(element=>element.type==="ball").length,2);assert.equal(new Set(independent.audit.diagram.elements.filter(element=>element.type==="ball").map(ball=>ball.role)).size,2);assert.equal(derived.audit.diagram.elements.filter(element=>element.type==="ball").length,1);assert.equal(derived.audit.diagram.actions.some(action=>/derivata/i.test(action.label??"")),true);});

test("final remediation full regression: i 459 non target conservano la baseline",()=>{const targetCodes=new Set([...derivedMatchCodes,"GK-TLR-028","GK-TLR-040"]),exercises=fullBaseline.rows.map(row=>row.exercise_input),after=createFullCatalogAuditReport(exercises),afterByCode=new Map(after.results.map(row=>[row.exercise.codice,row]));for(const before of fullBaseline.rows.filter(row=>!targetCodes.has(row.code))){const current=afterByCode.get(before.code);assert.ok(current,`Manca ${before.code}`);assert.equal(current.family,before.family,`${before.code} family`);assert.equal(current.status,before.status,`${before.code} status`);assert.equal(current.quality,before.quality,`${before.code} quality`);assert.equal(current.complexity,before.complexity,`${before.code} complexity`);if(current.kind==="SUCCESS"){assert.equal(current.collisions.filter(collision=>collision.category==="REAL_COLLISION").length,before.real_collisions,`${before.code} real collisions`);assert.equal(current.collisions.filter(collision=>collision.category==="VISUAL_INTERFERENCE").length,before.visual_interferences,`${before.code} visual interferences`);const{issues:_ballIssues,...currentBall}=current.ballIntegrity,{issues:_multiIssues,...currentMulti}=current.multiPhaseIntegrity,{issues:_beforeBallIssues,...beforeBall}=before.ball_integrity,{issues:_beforeMultiIssues,...beforeMulti}=before.multi_phase_integrity;assert.deepEqual(currentBall,beforeBall,`${before.code} ball integrity`);assert.deepEqual(currentMulti,beforeMulti,`${before.code} multi-phase integrity`);}}assert.equal(after.status.generationError,0);assert.equal(after.status.review,0);assert.equal(after.collisions.real.total,0);assert.equal(after.layout.outOfBoundsElements,0);assert.equal(after.participants.inactiveParticipantsRendered,0);assert.equal(after.semantic.coverage,94.2);assert.ok(after.quality>=98.3);assert.equal(after.successes.filter(item=>item.complexity==="LOW"&&item.status==="NEEDS_REVIEW").length,0);assert.equal(after.successes.filter(item=>item.complexity==="HIGH"&&item.status==="NEEDS_REVIEW").length,0);assert.equal(after.successes.filter(item=>item.family==="GENERIC").length,27);});
test("semantic gap audit: pagina DEV contiene le quattro sezioni e le opportunità",()=>{const page=source("../app/dev/tactical-catalog-audit/page.tsx"),component=source("../app/dev/tactical-catalog-audit/semantic-gap-audit.tsx");assert.match(page,/SEMANTIC GAP AUDIT/);assert.match(component,/A\. GENERIC\/UNKNOWN DIAGNOSTIC/);assert.match(component,/B\. NEEDS REVIEW DIAGNOSTIC/);assert.match(component,/C\. MEDIUM COMPLEXITY ANALYSIS/);assert.match(component,/D\. WORDING GAPS/);assert.match(component,/TOP FIX OPPORTUNITIES/);assert.match(component,/REGRESSION SAFETY/);});

test("catalog write dry-run: manual è sempre protetto anche con proposta quality 100",()=>{const value=exercise(950,{diagram_source:"manual",tactical_diagram:{version:1,canvas:{viewType:"front_goal",widthRatio:16,heightRatio:10},elements:[],actions:[]}}),decision=decideCatalogWrite(value);assert.equal(decision.action,"SKIP_MANUAL");assert.equal(decision.proposedDiagram,null);assert.equal(decision.newSource,null);});
test("catalog write dry-run: automatic_edited è sempre protetto",()=>{const value=exercise(951,{diagram_source:"automatic_edited",tactical_diagram:{version:1,canvas:{viewType:"front_goal",widthRatio:16,heightRatio:10},elements:[],actions:[]}}),decision=decideCatalogWrite(value);assert.equal(decision.action,"SKIP_AUTOMATIC_EDITED");assert.equal(decision.proposedDiagram,null);});
test("catalog write dry-run: diagramma mancante produce WRITE_NEW senza scrivere",()=>{const decision=decideCatalogWrite(exercise(952,{tactical_diagram:null,diagram_source:null}));assert.equal(decision.action,"WRITE_NEW");assert.equal(decision.newSource,"automatic");assert.ok(decision.proposedDiagram);assert.equal(decision.blockers.length,0);});
test("catalog write dry-run: automatico identico al frozen produce NO_CHANGE",()=>{const value=exercise(953),first=decideCatalogWrite(value);assert.equal(first.action,"WRITE_NEW");const second=decideCatalogWrite({...value,tactical_diagram:first.proposedDiagram,diagram_source:"automatic"});assert.equal(second.action,"NO_CHANGE");assert.equal(second.newSource,null);});
test("catalog write dry-run: automatico divergente viene mantenuto senza ipotesi sulla versione",()=>{const value=exercise(954,{diagram_source:"automatic",tactical_diagram:{version:1,canvas:{viewType:"full_pitch",widthRatio:16,heightRatio:10},elements:[],actions:[]}}),decision=decideCatalogWrite(value);assert.equal(decision.action,"KEEP_EXISTING_AUTOMATIC");assert.match(decision.reason,/versione precedente non distinguibile/i);});
test("catalog write dry-run: rigenerazione automatico richiede strategia esplicita",()=>{const value=exercise(955,{diagram_source:"automatic",tactical_diagram:{version:1,canvas:{viewType:"full_pitch",widthRatio:16,heightRatio:10},elements:[],actions:[]}}),decision=decideCatalogWrite(value,{automaticStrategy:"regenerate-divergent"});assert.equal(decision.action,"REGENERATE_AUTOMATIC");assert.equal(decision.newSource,"automatic");});
test("catalog write dry-run: stato anomalo è WRITE_BLOCKED",()=>{const value={...exercise(956),diagram_source:"legacy_unknown"} as CatalogWriteExercise,decision=decideCatalogWrite(value);assert.equal(decision.action,"WRITE_BLOCKED");assert.deepEqual(decision.blockers,["ANOMALOUS_DIAGRAM_SOURCE"]);});
test("catalog write dry-run: batch planning usa 20-50 record e log pending",()=>{const decisions=Array.from({length:53},(_,index)=>decideCatalogWrite(exercise(1000+index))),batches=createCatalogWriteBatches(decisions,25),log=createCatalogWriteLog(decisions);assert.deepEqual(batches.map(batch=>batch.size),[25,25,3]);assert.equal(log.length,53);assert.ok(log.every(row=>row.status==="PENDING"&&row.timestamp==="SET_AT_EXECUTION"));assert.throws(()=>createCatalogWriteBatches(decisions,10),/20 e 50/);});
test("catalog write dry-run: seconda esecuzione simulata è idempotente",()=>{const records=Array.from({length:4},(_,index)=>exercise(1100+index)),first=createCatalogWriteDryRun(records),simulated=first.decisions.map(item=>({...item.exercise,tactical_diagram:item.proposedDiagram,diagram_source:"automatic"} as Exercise)),second=createCatalogWriteDryRun(simulated);assert.equal(first.counts.WRITE_NEW,4);assert.equal(second.counts.NO_CHANGE,4);assert.equal(second.counts.WRITE_NEW,0);});
test("catalog write dry-run: il round-trip JSONB che omette undefined resta idempotente",()=>{const value=exercise(1200),first=decideCatalogWrite(value),persisted=JSON.parse(JSON.stringify(first.proposedDiagram));const second=decideCatalogWrite({...value,tactical_diagram:persisted,diagram_source:"automatic"});assert.equal(second.action,"NO_CHANGE");});
test("catalog write dry-run: UI non espone alcuna scrittura attiva",()=>{const component=source("../app/dev/tactical-catalog-audit/catalog-write-dry-run.tsx"),planner=source("../lib/tactical-catalog-write-plan.ts");assert.match(component,/EXECUTE WRITE · DISABLED/);assert.doesNotMatch(component,/\.update\(|\.insert\(|\.upsert\(/);assert.doesNotMatch(planner,/\.update\(|\.insert\(|\.upsert\(/);});
