import { classifyTacticalFamilyHealth, createTacticalAuditDiagnostic, type TacticalAuditItem, type TacticalDiagnosticSeverity, type TacticalFamilyHealth } from "./tactical-catalog-audit.ts";
import { classifyAuditComplexity, type TacticalComplexity } from "./tactical-large-audit.ts";
import type { SemanticTacticalFamily } from "./tactical-diagram.ts";

export type GenericRootCause="A"|"B"|"C"|"D"|"E"|"F";
export const GENERIC_ROOT_CAUSE_LABELS:Record<GenericRootCause,string>={
  A:"Famiglia esistente, wording non riconosciuto",
  B:"Combinazione di due famiglie esistenti",
  C:"Famiglia realmente mancante (proposta diagnostica)",
  D:"Descrizione troppo generica o ambigua",
  E:"Dati insufficienti",
  F:"Mapping categoria/sottocategoria non riconosciuto",
};

type PhraseRule={family:Exclude<SemanticTacticalFamily,"GENERIC">;pattern:RegExp};
const phraseRules:PhraseRule[]=[
  {family:"DOUBLE_SAVE",pattern:/\b(?:doppio intervento|due interventi|secondo intervento|doppia parata)\b/i},
  {family:"SECOND_BALL",pattern:/\b(?:seconda palla|secondo pallone|seconda giocata|ribattuta|riattacco|palla sporca|palla vagante)\b/i},
  {family:"MATCH_SIMULATION",pattern:/\b(?:match simulation|sequenza gara|scenario aperto|situazione di gara)\b/i},
  {family:"DIVE",pattern:/\b(?:tuffo|caduta laterale|parata laterale|deviazione)\b/i},
  {family:"CROSS",pattern:/\b(?:cross|traversone|palla attraversante|cut-back)\b/i},
  {family:"HIGH_CLAIM",pattern:/\b(?:uscita alta|presa aerea|palla alta)\b/i},
  {family:"LOW_CLAIM",pattern:/\b(?:uscita bassa|attacco palla bassa)\b/i},
  {family:"ONE_V_ONE",pattern:/\b(?:1v1|1\s*(?:vs|contro)\s*1|uno contro uno|duello)\b/i},
  {family:"FOOTWORK",pattern:/\b(?:gioco di piede|tecnica di piede|passaggio|trasmissione|ricezione|rilancio|rinvio|retropassaggio|costruzione)\b/i},
  {family:"POSITIONING",pattern:/\b(?:posizionamento|riallineamento|allineamento|copertura porta|set position|riferimenti con porta)\b/i},
  {family:"REACTION",pattern:/\b(?:reattività|reazione|stimolo|segnale|comando|scelta casuale|cambio direzione|contro movimento)\b/i},
  {family:"SHOT_SAVE",pattern:/\b(?:tiro|conclusione|parata|presa|blocco|respinta)\b/i},
];
const categoryRules:PhraseRule[]=[
  {family:"ONE_V_ONE",pattern:/1v1|uno contro uno|uscite basse/i},{family:"FOOTWORK",pattern:/tecnica di piede/i},{family:"POSITIONING",pattern:/posizionamento/i},{family:"DIVE",pattern:/tuffi laterali/i},{family:"HIGH_CLAIM",pattern:/uscite alte/i},{family:"REACTION",pattern:/reattività/i},{family:"MATCH_SIMULATION",pattern:/match simulation/i},{family:"SHOT_SAVE",pattern:/parate ravvicinate|tecnica presa/i},
];
const stopWords=new Set("della delle dello degli dalla dalle nello nella negli nelle alla alle allo agli anche come dopo prima secondo verso portiere portieri pallone palla esercizio esegue effettua viene deve della sulla sulle sul con una uno due tre quattro cinque sei il lo la gli le un al ai da di del per tra fra che si e o a in".split(" "));

function fullText(item:TacticalAuditItem){const exercise=item.exercise;return[exercise.nome,exercise.categoria,exercise.sottocategoria,exercise.obiettivo,exercise.descrizione,exercise.schema_step_1,exercise.schema_step_2,exercise.schema_step_3,exercise.schema_step_4,exercise.schema_step_5,exercise.schema_step_6,exercise.scenario_gara].filter(Boolean).join(" · ");}
function steps(item:TacticalAuditItem){return[item.exercise.schema_step_1,item.exercise.schema_step_2,item.exercise.schema_step_3,item.exercise.schema_step_4,item.exercise.schema_step_5,item.exercise.schema_step_6].filter((value):value is string=>Boolean(value));}
function unique<T>(values:T[]){return[...new Set(values)];}
function matchedRules(text:string,rules=phraseRules){return rules.flatMap(rule=>{const match=text.match(rule.pattern);return match?[{family:rule.family,phrase:match[0]}]:[];});}
function tokens(value:string){return(value.toLocaleLowerCase("it").match(/[a-zà-ÿ0-9]+/gi)??[]).filter(word=>word.length>=4&&!stopWords.has(word));}
function ngrams(value:string){const words=tokens(value),output:string[]=[];for(const size of [2,3])for(let index=0;index<=words.length-size;index+=1)output.push(words.slice(index,index+size).join(" "));return output;}
function phraseFrequency(items:TacticalAuditItem[]){const counts=new Map<string,number>();for(const item of items)for(const phrase of new Set(ngrams([item.exercise.nome,item.exercise.descrizione,...steps(item)].filter(Boolean).join(" "))))counts.set(phrase,(counts.get(phrase)??0)+1);return counts;}
function unrecognizedPhrases(item:TacticalAuditItem,frequency:Map<string,number>,recognized:string[]){const excluded=recognized.map(value=>value.toLocaleLowerCase("it")),candidates=unique(ngrams([item.exercise.nome,item.exercise.descrizione,...steps(item)].filter(Boolean).join(" "))).filter(phrase=>!excluded.some(value=>phrase.includes(value)||value.includes(phrase))).sort((left,right)=>(frequency.get(right)??0)-(frequency.get(left)??0)||right.split(" ").length-left.split(" ").length);return candidates.filter(phrase=>(frequency.get(phrase)??0)>=2).slice(0,6).concat(candidates.filter(phrase=>(frequency.get(phrase)??0)<2).slice(0,Math.max(0,3-candidates.filter(value=>(frequency.get(value)??0)>=2).length))).slice(0,6);}

function genericCause(item:TacticalAuditItem,suggestions:SemanticTacticalFamily[],unknown:string[],frequency:Map<string,number>):{cause:GenericRootCause;recoverable:boolean;recommendation:string}{
  const text=fullText(item),categoryHint=matchedRules(`${item.exercise.categoria} ${item.exercise.sottocategoria}`,categoryRules).map(value=>value.family),contentLength=[item.exercise.descrizione,...steps(item)].filter(Boolean).join(" ").length,ambiguous=/tema libero|soluzione libera|scenario scelto|compito variabile|gesto finale libero|circuito|partita a tema|challenge|mini-gara/i.test(text);
  if(contentLength<70)return{cause:"E",recoverable:false,recommendation:"TRUE GENERIC / AMBIGUOUS: completare prima i dati tecnici."};
  if(categoryHint.length)return{cause:"F",recoverable:true,recommendation:`EXTEND EXISTING FAMILY: normalizzare il mapping verso ${unique(categoryHint).join(" + ")}.`};
  if(suggestions.length>=2)return{cause:"B",recoverable:true,recommendation:`EXTEND EXISTING FAMILY: composizione diagnostica ${suggestions.join(" + ")}, senza creare nuove famiglie.`};
  if(suggestions.length===1)return{cause:"A",recoverable:true,recommendation:`EXTEND EXISTING FAMILY: ampliare in futuro i sinonimi di ${suggestions[0]}.`};
  if(ambiguous)return{cause:"D",recoverable:false,recommendation:"TRUE GENERIC / AMBIGUOUS: il tema non identifica un fondamentale dominante."};
  if(unknown.some(phrase=>(frequency.get(phrase)??0)>=2))return{cause:"C",recoverable:false,recommendation:"POSSIBLE MISSING FAMILY: pattern ricorrente nel campione, da verificare prima di proporre una nuova famiglia."};
  return{cause:"D",recoverable:false,recommendation:"TRUE GENERIC / AMBIGUOUS: nessun pattern ricorrente giustifica una nuova famiglia."};
}

function minimalFix(item:TacticalAuditItem,diagnostic:ReturnType<typeof createTacticalAuditDiagnostic>){const reason=[...item.errors,...item.warnings,diagnostic.rootCause].join(" ");if(/ownership|propria origine|palla senza/i.test(reason))return"Collegare diagnosticamente la palla attiva al servitore/origine già descritto, senza cambiare la sequenza.";if(/origini di palla distinte|seconda origine|attesi 2 ball|1 ball/i.test(reason))return"Rappresentare BALL_A e BALL_B e collegarle alle rispettive fasi/origini dichiarate.";if(/transizione|derivata/i.test(reason))return"Esplicitare il collegamento PHASE_1 → TRANSITION → PHASE_2 sulla stessa palla derivata.";if(/collisione critica|collisioni reali/i.test(reason))return"Separare localmente gli elementi realmente sovrapposti mantenendo invariati attori e semantica.";if(item.family==="GENERIC")return"Estendere solo il riconoscimento del wording verso una famiglia esistente.";return diagnostic.possibleCorrection.replace(/^Proposta:\s*/i,"");}

export type SemanticGapCase=ReturnType<typeof createGapCase>;
function createGapCase(item:TacticalAuditItem,frequency:Map<string,number>){const diagnostic=createTacticalAuditDiagnostic(item),text=fullText(item),matches=matchedRules(text),suggestedFamilies=unique(matches.map(value=>value.family)),recognized=unique(matches.filter(value=>item.family==="GENERIC"||value.family===item.family).map(value=>value.phrase)),unknown=unrecognizedPhrases(item,frequency,recognized),generic=item.family==="GENERIC"?genericCause(item,suggestedFamilies,unknown,frequency):null;return{item,complexity:classifyAuditComplexity(item),description:item.exercise.descrizione,steps:steps(item),semanticConfidence:item.semanticValidation.confidence,recognizedPhrases:recognized,unrecognizedPhrases:unknown,suggestedFamilies,generic,diagnostic,minimalFix:minimalFix(item,diagnostic)};}

function mediumMetrics(cases:SemanticGapCase[]){const aggregate=(values:SemanticGapCase[])=>({count:values.length,averageActions:values.length?Math.round(values.reduce((sum,value)=>sum+value.diagnostic.generatedActions.length,0)/values.length*10)/10:0,averagePhases:values.length?Math.round(values.reduce((sum,value)=>sum+(value.diagnostic.multiPhasePlan?.phases.length??1),0)/values.length*10)/10:0,averageRequiredEquipment:values.length?Math.round(values.reduce((sum,value)=>sum+value.diagnostic.requiredEquipment.reduce((total,row)=>total+row.required,0),0)/values.length*10)/10:0,averageBallOrigins:values.length?Math.round(values.reduce((sum,value)=>sum+value.diagnostic.ballOrigins.length,0)/values.length*10)/10:0,averageParticipants:values.length?Math.round(values.reduce((sum,value)=>sum+value.diagnostic.activeParticipants.length,0)/values.length*10)/10:0,transitionActions:values.reduce((sum,value)=>sum+value.diagnostic.generatedActions.filter(action=>/RECUPERO|MOVIMENTO/.test(action.type)).length,0)});const successful=cases.filter(value=>value.item.status!=="NEEDS_REVIEW"),failed=cases.filter(value=>value.item.status==="NEEDS_REVIEW"),patterns=[{label:"Origini palla mancanti/non collegate",codes:failed.filter(value=>value.diagnostic.ballOrigins.length<value.diagnostic.expectedBallOrigins||value.diagnostic.ballOrigins.some(ball=>ball.status==="UNLINKED")).map(value=>value.item.exercise.codice)},{label:"Composizione multi-phase",codes:failed.filter(value=>Boolean(value.diagnostic.multiPhasePlan)).map(value=>value.item.exercise.codice)},{label:"Transizione non riconoscibile",codes:failed.filter(value=>/transizione|derivata/i.test(`${value.diagnostic.rootCause} ${value.item.errors.join(" ")}`)).map(value=>value.item.exercise.codice)},{label:"Collisione reale/interferenza critica",codes:failed.filter(value=>value.diagnostic.layout.collisions.some(collision=>collision.category==="REAL_COLLISION")).map(value=>value.item.exercise.codice)},{label:"Combinazione di famiglie",codes:failed.filter(value=>value.suggestedFamilies.length>=2).map(value=>value.item.exercise.codice)}].filter(pattern=>pattern.codes.length);return{successful,failed,successfulMetrics:aggregate(successful),failedMetrics:aggregate(failed),patterns};}

export function createSemanticGapAuditReport(items:TacticalAuditItem[]){
  const genericItems=items.filter(item=>item.family==="GENERIC"),frequency=phraseFrequency(genericItems),allCases=items.map(item=>createGapCase(item,frequency)),generic=allCases.filter(value=>value.item.family==="GENERIC"),reviews=allCases.filter(value=>value.item.status==="NEEDS_REVIEW"),medium=allCases.filter(value=>value.complexity==="MEDIUM"),target=allCases.filter(value=>value.item.family==="GENERIC"||value.item.status==="NEEDS_REVIEW"||value.complexity==="MEDIUM"),recoverable=generic.filter(value=>value.generic?.recoverable),trueGeneric=generic.filter(value=>!value.generic?.recoverable),causeCounts=(Object.keys(GENERIC_ROOT_CAUSE_LABELS) as GenericRootCause[]).map(cause=>({cause,label:GENERIC_ROOT_CAUSE_LABELS[cause],count:generic.filter(value=>value.generic?.cause===cause).length,codes:generic.filter(value=>value.generic?.cause===cause).map(value=>value.item.exercise.codice)})),specific=items.length-generic.length,potentialCoverage=items.length?Math.round((specific+recoverable.length)/items.length*1000)/10:0;
  const wording=Object.entries(target.flatMap(value=>value.unrecognizedPhrases.map(phrase=>({phrase,code:value.item.exercise.codice}))).reduce<Record<string,{count:number;codes:Set<string>}>>((output,value)=>{const row=output[value.phrase]??={count:0,codes:new Set<string>()};row.count+=1;row.codes.add(value.code);return output;},{})).map(([phrase,row])=>({phrase,count:row.count,codes:[...row.codes]})).sort((left,right)=>right.count-left.count||left.phrase.localeCompare(right.phrase)).slice(0,30);
  const familyRows=Object.entries(items.reduce<Record<string,{total:number;valid:number;warnings:number;review:number}>>((output,item)=>{const row=output[item.family]??={total:0,valid:0,warnings:0,review:0};row.total+=1;if(item.status==="VALID")row.valid+=1;else if(item.status==="VALID_WITH_WARNINGS")row.warnings+=1;else row.review+=1;return output;},{})).map(([family,row])=>({family,...row,health:classifyTacticalFamilyHealth(row)})),stableFamilies=familyRows.filter(row=>row.health==="STABLE");
  const opportunities=[{rootCause:"Wording di famiglie esistenti non riconosciuto",cases:recoverable.filter(value=>value.generic?.cause==="A"||value.generic?.cause==="F"),risk:"MEDIO",difficulty:"BASSA"},{rootCause:"Combinazioni di famiglie esistenti",cases:recoverable.filter(value=>value.generic?.cause==="B"),risk:"ALTO",difficulty:"MEDIA"},{rootCause:"Origini e ownership multi-ball",cases:reviews.filter(value=>/palla|ball|origine|ownership/i.test(`${value.diagnostic.rootCause} ${value.item.errors.join(" ")}`)),risk:"ALTO",difficulty:"MEDIA"},{rootCause:"Transizione della seconda azione",cases:reviews.filter(value=>/transizione|derivata/i.test(`${value.diagnostic.rootCause} ${value.item.errors.join(" ")}`)),risk:"ALTO",difficulty:"MEDIA"},{rootCause:"Collisione reale locale",cases:reviews.filter(value=>value.diagnostic.layout.collisions.some(collision=>collision.category==="REAL_COLLISION")),risk:"MEDIO",difficulty:"BASSA"}].filter(value=>value.cases.length).map(value=>({...value,codes:unique(value.cases.map(item=>item.item.exercise.codice)),families:unique(value.cases.flatMap(item=>item.item.family==="GENERIC"&&item.suggestedFamilies.length?item.suggestedFamilies:[item.item.family])),coverageRecovery:value.cases.filter(item=>item.generic?.recoverable).length})).sort((left,right)=>right.codes.length-left.codes.length);
  return{total:items.length,target,generic,reviews,medium,mediumAnalysis:mediumMetrics(medium),recoverable,trueGeneric,potentialCoverage,causeCounts,wording,stableFamilies,opportunities};
}

export function severityLabel(value:TacticalDiagnosticSeverity){return value;}
export function complexityLabel(value:TacticalComplexity){return`${value} COMPLEXITY`;}
