import { AuthGate } from "../../auth-gate";
import { ExerciseTacticalBoard } from "../../components/exercise-tactical-board";
import { generateTacticalDiagram } from "../../../lib/tactical-diagram";
import type { Exercise } from "../../../lib/types";

const base:Exercise={id:"marker-dev",codice:"DEV",nome:"Test",category_id:1,subcategory_id:1,categoria:"Tecnica",sottocategoria:"Test",fase:"Analitico",obiettivo:"Confronto renderer",descrizione:"",durata_min:10,portieri_min:1,portieri_max:2,intensita:"Media",difficolta:2,materiale:"Palloni",variante:null,coaching_points:"",errori_comuni:"",schema_step_1:null,schema_step_2:null,schema_step_3:null,schema_step_4:null,schema_step_5:null,schema_step_6:null,scenario_gara:null,numero_azioni:null,attivo:true};
const cases:Array<[string,Partial<Exercise>]>=[["Tuffo laterale",{nome:"Tuffo laterale",descrizione:"Il tiratore conclude e il GK esegue un tuffo laterale"}],["Cross",{nome:"Cross da sinistra",descrizione:"Il servitore effettua un cross e il GK interviene"}],["Tecnica di piede",{nome:"Tecnica di piede",descrizione:"Il GK effettua un passaggio al compagno"}],["Doppio intervento",{nome:"Doppio intervento",descrizione:"Il tiratore conclude, il GK recupera ed esegue il secondo intervento"}],["Seconda palla",{nome:"Seconda palla",descrizione:"Il tiratore conclude e l'appoggio serve la seconda palla"}],["Setup complesso",{nome:"Tecnica di piede con percorso e target",descrizione:"Il GK parte tra due coni, esegue uno slalom tra 4 cinesini e passa nella porticina",materiale:"Palloni, 2 coni, 4 cinesini, 1 porticina"}]];

function MarkerComparison(){return <main className="tactical-composition-page"><header><span className="eyebrow">Development comparison</span><h1>Technical markers visibility</h1><p>Stesso identico JSON. A sinistra gli anchor tecnici visibili per diagnosi; a destra il renderer production senza circoli tecnici non numerati.</p></header><div className="tactical-composition-list">{cases.map(([label,patch])=>{const diagram=generateTacticalDiagram({...base,...patch});return <section key={label} className="tactical-composition-case"><h2>{label}</h2><div className="tactical-composition-grid"><article><strong>CURRENT · DEBUG ANCHORS</strong><ExerciseTacticalBoard diagram={diagram} rendererVersion="v2-final" showTechnicalMarkers/></article><article><strong>WITHOUT TECHNICAL MARKERS · PRODUCTION</strong><ExerciseTacticalBoard diagram={diagram} rendererVersion="v2-final"/></article></div></section>;})}</div></main>;}
export default function Page(){return <AuthGate><MarkerComparison/></AuthGate>;}
