import { EXERCISE_SELECTION_CONFIG } from "./exercise-config.ts";
import { getExerciseCandidates, scoreExercise, scoreExerciseCandidates, selectExercisesForBlock, type ExerciseSelectionInput } from "./exercise-selection.ts";
import type { EditableExerciseSelection, EditableGeneratedSession, Exercise, GeneratedExerciseSelection, ScoredExerciseCandidate, SessionExerciseSource } from "../types.ts";
const editable=(item:GeneratedExerciseSelection,source:SessionExerciseSource="generated"):EditableExerciseSelection=>({...item,locked:false,source,variants:[]});
export function makeEditableSession(result:{seed:string;selections:GeneratedExerciseSelection[];debug:Record<number,ScoredExerciseCandidate[]>;net_minutes:number;transition_minutes:number;total_minutes:number}):EditableGeneratedSession{return{...result,selections:result.selections.map(x=>editable(x))};}
function recalc(current:EditableGeneratedSession,selections:EditableExerciseSelection[]):EditableGeneratedSession{const net=selections.reduce((s,x)=>s+x.planned_duration_minutes,0);return{...current,selections,net_minutes:net,total_minutes:net+current.transition_minutes};}
export function regenerateBlock(input:ExerciseSelectionInput,current:EditableGeneratedSession,blockOrder:number,index:number):EditableGeneratedSession{
 const block=input.blocks.find(b=>b.ordine===blockOrder);if(!block)return current;
 const locked=current.selections.filter(x=>x.block_order===blockOrder&&x.locked);const outside=current.selections.filter(x=>x.block_order!==blockOrder);const used=[...outside,...locked];
 const max=(EXERCISE_SELECTION_CONFIG.exercisesPerBlock[blockOrder]??[1,1])[1];if(locked.length>=max)return current;
 const lockedMinutes=locked.reduce((s,x)=>s+x.planned_duration_minutes,0);const adjusted={...block,durata_target:Math.max((block.transition_minutes??2)+5,block.durata_target-lockedMinutes)};
 const generated=selectExercisesForBlock(adjusted,{...input,seed:`${input.seed}:block:${blockOrder}:regen:${index}`},used);const replacements=generated.selections.map(x=>editable(x,"regenerated"));
 const selections=[...outside,...locked,...replacements].sort((a,b)=>a.block_order-b.block_order||a.block_position-b.block_position).map((x,_i,all)=>({...x,block_position:all.filter(y=>y.block_order===x.block_order).indexOf(x)}));return recalc(current,selections);
}
export function regenerateSession(input:ExerciseSelectionInput,current:EditableGeneratedSession,index:number):EditableGeneratedSession{let result=current;for(const block of input.blocks)result=regenerateBlock({...input,seed:`${input.seed}:session:${index}`},result,block.ordine,index);return result;}
export function getReplacementCandidates(input:ExerciseSelectionInput,current:EditableGeneratedSession,target:EditableExerciseSelection,filters?:{sameCategory?:boolean;notRecent?:boolean;similarDuration?:boolean;easier?:boolean;harder?:boolean}){const block=input.blocks.find(b=>b.ordine===target.block_order);if(!block)return[];const selected=current.selections.filter(x=>x!==target);let ranked:ScoredExerciseCandidate[]=[];for(let level=0;level<=5&&!ranked.length;level++)ranked=scoreExerciseCandidates(getExerciseCandidates(input,block,level).filter(e=>e.id!==target.exercise.id&&!selected.some(x=>x.exercise.id===e.id)),block,input,level,selected);return ranked.filter(x=>!filters?.sameCategory||x.exercise.category_id===target.exercise.category_id).filter(x=>!filters?.notRecent||(x.usage.days_since_last_use??99)>14).filter(x=>!filters?.similarDuration||Math.abs(x.exercise.durata_min-target.planned_duration_minutes)<=5).filter(x=>!filters?.easier||x.exercise.difficolta<target.exercise.difficolta).filter(x=>!filters?.harder||x.exercise.difficolta>target.exercise.difficolta).slice(0,5);}
export function scoreManualExercise(input:ExerciseSelectionInput,current:EditableGeneratedSession,exercise:Exercise,blockOrder:number){const block=input.blocks.find(b=>b.ordine===blockOrder)!;return scoreExercise(exercise,block,input,5,current.selections);}
