"use client";

import { useMemo, useState } from "react";
import { ExerciseTacticalBoard } from "../../components/exercise-tactical-board";
import { createCatalogBackup, createCatalogWriteBatches, createCatalogWriteDryRun, createCatalogWriteLog, createCatalogWritePayloads, type CatalogWriteAction } from "../../../lib/tactical-catalog-write-plan";
import type { Exercise } from "../../../lib/types";
import styles from "./catalog-write-dry-run.module.css";

const actionOrder:CatalogWriteAction[]=["WRITE_NEW","REGENERATE_AUTOMATIC","KEEP_EXISTING_AUTOMATIC","SKIP_MANUAL","SKIP_AUTOMATIC_EDITED","WRITE_BLOCKED","NO_CHANGE"];
function download(name:string,payload:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"})),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);}

export function CatalogWriteDryRun({records}:{records:Exercise[]}){
  const[detailFilter,setDetailFilter]=useState<CatalogWriteAction|"ALL">("ALL"),report=useMemo(()=>createCatalogWriteDryRun(records),[records]),backup=useMemo(()=>createCatalogBackup(report.decisions),[report.decisions]),batches=useMemo(()=>createCatalogWriteBatches(report.decisions,25),[report.decisions]),payloads=useMemo(()=>createCatalogWritePayloads(report.decisions),[report.decisions]),log=useMemo(()=>createCatalogWriteLog(report.decisions),[report.decisions]);
  const previews=useMemo(()=>[...report.decisions.filter(item=>item.action==="WRITE_NEW").slice(0,20),...report.decisions.filter(item=>item.action==="REGENERATE_AUTOMATIC")],[report.decisions]),details=detailFilter==="ALL"?report.decisions:report.decisions.filter(item=>item.action===detailFilter),anomalies=Object.entries(report.database.anomalous),warningRecords=report.decisions.filter(item=>item.warnings.length>0).length;
  const exportBackup=()=>download("tactical-catalog-prewrite-backup.json",{created_at:new Date().toISOString(),dry_run:true,record_count:backup.length,records:backup});
  const exportPlan=()=>download("tactical-catalog-write-plan.json",{created_at:new Date().toISOString(),dry_run:true,frozen_baseline:report.frozenBaseline,database:report.database,counts:report.counts,warning_records:warningRecords,automatic_comparison:report.automaticComparison,execution_policy:{enabled:false,batch_size:25,continue_after_record_error:true,atomic_fields:["tactical_diagram","diagram_source","diagram_updated_at"],partial_record_updates:false,timestamp_assigned_at_execution:true},batch_count:batches.length,batches,write_log:log,decisions:report.decisions.map(item=>({exercise_id:item.exercise.id,code:item.exercise.codice,title:item.exercise.nome,current_diagram_source:item.currentSource,current_tactical_diagram_present:Boolean(item.currentDiagram),proposed_action:item.action,new_diagram_source:item.newSource,quality:item.quality,status:item.status,warnings:item.warnings,blockers:item.blockers,reason:item.reason}))});
  return <section className={styles.dashboard}>
    <section className={styles.freeze}><div><b>PREPARE CATALOG WRITE · DRY RUN ONLY</b><span>Baseline frozen: {report.frozenBaseline} · nessuna chiamata INSERT/UPDATE</span></div><strong>WRITE DISABLED</strong></section>
    <section className={styles.status}><h2>DATABASE STATUS</h2><div><Metric label="TOTAL" value={report.database.total}/><Metric label="DIAGRAM NULL" value={report.database.diagramNull}/><Metric label="DIAGRAM PRESENT" value={report.database.diagramPresent}/><Metric label="SOURCE NULL" value={report.database.sourceNull}/><Metric label="AUTOMATIC" value={report.database.automatic}/><Metric label="MANUAL" value={report.database.manual}/><Metric label="AUTOMATIC EDITED" value={report.database.automaticEdited}/></div>{anomalies.length>0&&<p className={styles.blocked}>Valori anomali: {anomalies.map(([key,value])=>`${key} (${value})`).join(" · ")}</p>}</section>
    <section className={styles.status}><h2>DRY RUN</h2><div>{actionOrder.map(action=><Metric key={action} label={action.replaceAll("_"," ")} value={report.counts[action]}/>)}</div><p className={styles.blocked}>Diagrammi scrivibili con warning non bloccanti registrati: <b>{warningRecords}</b></p></section>
    <section className={styles.guard}><div><h3>PROTECTION</h3><p>Manual protetti: <b>{report.counts.SKIP_MANUAL}</b></p><p>Automatic edited protetti: <b>{report.counts.SKIP_AUTOMATIC_EDITED}</b></p></div><div><h3>AUTOMATIC VERSION CHECK</h3><p>Match strutturale frozen: <b>{report.automaticComparison.exactFrozenMatch}</b></p><p>Divergenti/versione non certa: <b>{report.automaticComparison.divergentUnknownVersion}</b></p><small>Nessun metadata aggiunto al JSON frozen. Gli automatici divergenti restano invariati finché non viene autorizzata una strategia.</small></div><div><h3>WRITE PLAN</h3><p>Record scrivibili: <b>{payloads.length}</b></p><p>Batch: <b>{batches.length}</b> · dimensione massima <b>25</b></p><small>La futura operazione aggiornerà atomicamente diagramma, origine e timestamp per singolo record.</small></div></section>
    <section className={styles.actions}><button type="button" onClick={exportBackup}>EXPORT BACKUP JSON · {backup.length}</button><button type="button" onClick={exportPlan}>EXPORT WRITE PLAN · {batches.length} BATCH</button><button type="button" disabled title="La scrittura reale richiede una conferma separata">EXECUTE WRITE · DISABLED</button></section>
    <section><h2>PREVIEW · 20 WRITE NEW + ALL REGENERATE</h2><div className={styles.previews}>{previews.map(item=><article key={item.exercise.id}><header><div><b>{item.exercise.codice}</b><h3>{item.exercise.nome}</h3></div><span>{item.action}</span></header><div className={styles.compare}><section><h4>CURRENT</h4>{item.currentDiagram?<ExerciseTacticalBoard diagram={item.currentDiagram} rendererVersion="v2-final"/>:<div className={styles.empty}>NO CURRENT DIAGRAM</div>}</section><section><h4>PROPOSED</h4>{item.proposedDiagram?<ExerciseTacticalBoard diagram={item.proposedDiagram} rendererVersion="v2-final"/>:<div className={styles.empty}>NO PROPOSED DIAGRAM</div>}</section></div><footer><span>{item.status} · quality {item.quality}</span><small>{item.reason}</small></footer></article>)}</div></section>
    <section className={styles.details}><header><div><h2>RECORD DETAIL</h2><p>{details.length} record · nessuna modifica remota</p></div><label>AZIONE<select value={detailFilter} onChange={event=>setDetailFilter(event.target.value as CatalogWriteAction|"ALL")}><option value="ALL">Tutte</option>{actionOrder.map(action=><option key={action}>{action}</option>)}</select></label></header><div className={styles.table}><b>CODE / TITLE</b><b>CURRENT</b><b>PROPOSED</b><b>QUALITY</b><b>STATUS</b><b>WARNINGS / REASON</b>{details.map(item=><div key={item.exercise.id}><span><strong>{item.exercise.codice}</strong><small>{item.exercise.nome}</small></span><span>{item.currentSource??"NULL"} · {item.currentDiagram?"PRESENT":"NULL"}</span><span>{item.action}<small>source: {item.newSource??"—"}</small></span><span>{item.quality||"—"}</span><span>{item.status}</span><span>{item.warnings.length?item.warnings.join(" · "):"Nessun warning"}<small>{item.reason}</small></span></div>)}</div></section>
  </section>;
}

function Metric({label,value}:{label:string;value:number}){return <span><small>{label}</small><strong>{value}</strong></span>;}
