"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ExerciseTacticalBoard } from "../../components/exercise-tactical-board";
import { createFullCatalogAuditReport, fullAuditExportRows, selectRandomValidForHumanReview, type FullAuditReport, type FullAuditResult, type FullAuditStatus, type FullAuditSuccess } from "../../../lib/tactical-full-audit";
import type { Exercise } from "../../../lib/types";
import styles from "./full-catalog-audit.module.css";
import { FinalNineRemediation } from "./final-nine-remediation";
import { CatalogWriteDryRun } from "./catalog-write-dry-run";

type GalleryFilter="ALL"|FullAuditStatus|"GENERIC"|"UNKNOWN"|"REAL_COLLISION"|"VISUAL_INTERFERENCE"|"LOW"|"MEDIUM"|"HIGH";
type GallerySort="WORST"|"QUALITY_ASC"|"QUALITY_DESC"|"CODE"|"CATEGORY"|"FAMILY"|"STATUS";
const statusRank:Record<FullAuditStatus,number>={GENERATION_ERROR:0,NEEDS_REVIEW:1,VALID_WITH_WARNINGS:2,VALID:3};
const equipmentLabels:Record<string,string>={cone:"CONES",marker:"FLAT MARKERS / CINESINI",mini_goal:"MINI GOALS",mannequin:"MANNEQUINS",hurdle:"HURDLES",ball:"BALLS"};

function download(name:string,type:string,content:string){const url=URL.createObjectURL(new Blob([content],{type})),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);}
function csvValue(value:unknown){const text=typeof value==="string"?value:JSON.stringify(value??"");return`"${text.replaceAll('"','""')}"`;}
function exportJson(report:FullAuditReport){download("tactical-full-catalog-audit.json","application/json",JSON.stringify({generated_at:new Date().toISOString(),non_destructive:true,summary:{catalog:report.catalogSize,analyzed:report.analyzed,not_analyzed:report.notAnalyzed,status:report.status,quality:report.quality,semantic:report.semantic,collisions:report.collisions,ball_integrity:report.ballIntegrity,participants:report.participants,equipment:report.equipment,layout:report.layout,duration_ms:report.durationMs},exercises:fullAuditExportRows(report)},null,2));}
function exportCsv(report:FullAuditReport){const rows=fullAuditExportRows(report),headers=Object.keys(rows[0]??{}),content=[headers.join(","),...rows.map(row=>headers.map(key=>csvValue(row[key as keyof typeof row])).join(","))].join("\n");download("tactical-full-catalog-audit.csv","text/csv;charset=utf-8",content);}

function Kpi({label,value,detail,tone}:{label:string;value:string|number;detail?:string;tone?:"ok"|"warn"|"bad"}){return <div className={`${styles.kpi} ${tone?styles[tone]:""}`}><b>{label}</b><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
function Status({value}:{value:FullAuditStatus}){return <span className={`${styles.status} ${styles[`status_${value}`]}`}>{value.replaceAll("_"," ")}</span>;}

function LazyBoard({item}:{item:FullAuditSuccess}){
  const ref=useRef<HTMLDivElement>(null),[visible,setVisible]=useState(false);
  useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){setVisible(true);observer.disconnect();}},{rootMargin:"240px"});observer.observe(node);return()=>observer.disconnect();},[]);
  return <div ref={ref} className={styles.boardPlaceholder}>{visible?<ExerciseTacticalBoard diagram={item.audit.diagram} rendererVersion="v2-final" className="audit-board"/>:<span>Preview in attesa</span>}</div>;
}

function CaseCard({result,large=false}:{result:FullAuditResult;large?:boolean}){
  const issues=result.kind==="SUCCESS"?result.rootCauses:result.generationErrors;
  return <article className={`${styles.caseCard} ${large?styles.large:""}`}><header><div><b>{result.exercise.codice}</b><h3>{result.exercise.nome}</h3><p>{result.exercise.categoria} · {result.family}</p></div><strong>{result.quality}</strong></header><div className={styles.badges}><Status value={result.status}/><span>{result.complexity}</span></div>{result.kind==="SUCCESS"?<LazyBoard item={result}/>:<div className={styles.generationFailure}>Diagramma non generato</div>}{issues.length>0&&<ul>{issues.slice(0,large?8:3).map((issue,index)=><li key={`${issue}-${index}`}>{issue}</li>)}</ul>}</article>;
}

function FamilyTable({report}:{report:FullAuditReport}){return <section className={styles.panel}><h2>FAMILY HEALTH</h2><div className={styles.table}><b>FAMILY</b><b>TOTAL</b><b>VALID</b><b>WARNING</b><b>REVIEW</b><b>GEN ERROR</b><b>QUALITY</b><b>HEALTH</b>{report.families.map(row=><div key={row.family}><span>{row.family}</span><span>{row.total}</span><span>{row.valid}</span><span>{row.warning}</span><span>{row.review}</span><span>{row.generationError}</span><span>{row.averageQuality}</span><strong className={styles[`health_${row.health}`]}>{row.health}</strong></div>)}</div></section>}

function IntegrityPanels({report}:{report:FullAuditReport}){
  return <div className={styles.panelGrid}>
    <section className={styles.panel}><h2>COMPLEXITY</h2>{report.complexity.map(row=><p key={row.level}><b>{row.level}</b><span>{row.total} total · {row.valid} valid · {row.warning} warning · {row.review} review · {row.generationError} error · quality {row.averageQuality} · real collision {row.realCollisions}</span></p>)}</section>
    <section className={styles.panel}><h2>COLLISIONS</h2><p><b>EXPECTED INTERSECTION</b><span>{report.collisions.expected.total} · {report.collisions.expected.exercises} esercizi · {report.collisions.expected.percentage}%</span></p><p><b>VISUAL INTERFERENCE</b><span>{report.collisions.visual.total} · {report.collisions.visual.exercises} esercizi · {report.collisions.visual.percentage}%</span></p><p><b>REAL COLLISION</b><span>{report.collisions.real.total} · {report.collisions.real.exercises} esercizi · {report.collisions.real.percentage}%</span></p></section>
    <section className={styles.panel}><h2>BALL INTEGRITY</h2>{Object.entries(report.ballIntegrity).map(([key,value])=><p key={key}><b>{key.replaceAll(/([A-Z])/g," $1").toUpperCase()}</b><span>{value}</span></p>)}</section>
    <section className={styles.panel}><h2>MULTI-PHASE INTEGRITY</h2>{Object.entries(report.multiPhase).map(([key,value])=><p key={key}><b>{key.replaceAll(/([A-Z])/g," $1").toUpperCase()}</b><span>{value}</span></p>)}</section>
    <section className={styles.panel}><h2>PARTICIPANTS</h2><p><b>INACTIVE PARTICIPANT RENDERED</b><span>{report.participants.inactiveParticipantsRendered} · {report.participants.exercises} esercizi</span></p><h2>TECHNICAL MARKERS</h2><p><b>VISIBLE IN PRODUCTION</b><span>{report.layout.technicalMarkersVisible}</span></p></section>
    <section className={`${styles.panel} ${styles.wide}`}><h2>EQUIPMENT INTEGRITY</h2><div className={`${styles.table} ${styles.equipmentTable}`}><b>TYPE</b><b>DECLARED</b><b>REQUIRED</b><b>RENDERED</b><b>MISSING</b><b>RELATION ERROR</b>{report.equipment.map(row=><div key={row.type}><span>{equipmentLabels[row.type]??row.type}</span><span>{row.declared}</span><span>{row.required}</span><span>{row.rendered}</span><span>{row.missingRequired}</span><span>{row.relationErrors}</span></div>)}</div></section>
    <section className={styles.panel}><h2>LAYOUT</h2>{Object.entries(report.layout).filter(([key])=>key!=="technicalMarkersVisible").map(([key,value])=><p key={key}><b>{key.replaceAll(/([A-Z])/g," $1").toUpperCase()}</b><span>{value}</span></p>)}</section>
  </div>;
}

function RealCollisionCases({report}:{report:FullAuditReport}){const rows=report.successes.filter(item=>item.collisions.some(collision=>collision.category==="REAL_COLLISION"));if(!rows.length)return <section className={styles.emptySuccess}><strong>ZERO REAL COLLISIONS</strong><span>Nessuna collisione reale rilevata nel catalogo completo.</span></section>;return <section><h2>REAL COLLISIONS · individual cases</h2><div className={styles.largeCases}>{rows.map(item=><article key={item.exercise.id} className={styles.collisionCase}><CaseCard result={item} large/><div>{item.collisions.filter(collision=>collision.category==="REAL_COLLISION").map((collision,index)=><p key={`${collision.actionId}-${collision.elementId}-${index}`}><b>{collision.severity}</b> · action {collision.actionId??"—"} · element {collision.elementLabel} · {collision.reason}</p>)}</div></article>)}</div></section>}

function Gallery({report}:{report:FullAuditReport}){
  const[filter,setFilter]=useState<GalleryFilter>("ALL"),[family,setFamily]=useState("ALL"),[sort,setSort]=useState<GallerySort>("WORST"),[page,setPage]=useState(1),pageSize=48;
  const families=useMemo(()=>[...new Set(report.results.map(item=>item.family))].sort(),[report.results]);
  const filtered=useMemo(()=>report.results.filter(item=>family==="ALL"||item.family===family).filter(item=>{if(filter==="ALL")return true;if(["VALID","VALID_WITH_WARNINGS","NEEDS_REVIEW","GENERATION_ERROR"].includes(filter))return item.status===filter;if(filter==="GENERIC"||filter==="UNKNOWN")return item.semanticKind===filter;if(filter==="LOW"||filter==="MEDIUM"||filter==="HIGH")return item.complexity===filter;if(item.kind!=="SUCCESS")return false;return item.collisions.some(collision=>collision.category===filter);}).sort((a,b)=>{if(sort==="QUALITY_ASC")return a.quality-b.quality;if(sort==="QUALITY_DESC")return b.quality-a.quality;if(sort==="CODE")return a.exercise.codice.localeCompare(b.exercise.codice);if(sort==="CATEGORY")return a.exercise.categoria.localeCompare(b.exercise.categoria)||a.exercise.codice.localeCompare(b.exercise.codice);if(sort==="FAMILY")return a.family.localeCompare(b.family)||a.exercise.codice.localeCompare(b.exercise.codice);if(sort==="STATUS")return statusRank[a.status]-statusRank[b.status]||a.quality-b.quality;return statusRank[a.status]-statusRank[b.status]||a.quality-b.quality;}),[report.results,filter,family,sort]);
  useEffect(()=>setPage(1),[filter,family,sort]);const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),shown=filtered.slice((page-1)*pageSize,page*pageSize);
  const filters:Array<[string,GalleryFilter]>=[["ALL","ALL"],["VALID","VALID"],["WARNING","VALID_WITH_WARNINGS"],["NEEDS REVIEW","NEEDS_REVIEW"],["GENERATION ERROR","GENERATION_ERROR"],["GENERIC","GENERIC"],["UNKNOWN","UNKNOWN"],["REAL COLLISION","REAL_COLLISION"],["VISUAL INTERFERENCE","VISUAL_INTERFERENCE"],["LOW COMPLEXITY","LOW"],["MEDIUM COMPLEXITY","MEDIUM"],["HIGH COMPLEXITY","HIGH"]];
  return <section className={styles.gallery}><header><div><h2>FULL CATALOG GALLERY</h2><p>{filtered.length} esercizi · pagina {page}/{pages} · preview lazy, massimo {pageSize} per pagina</p></div><div><label>Famiglia<select value={family} onChange={event=>setFamily(event.target.value)}><option value="ALL">Tutte</option>{families.map(value=><option key={value}>{value}</option>)}</select></label><label>Ordina<select value={sort} onChange={event=>setSort(event.target.value as GallerySort)}><option value="WORST">Peggiori prima</option><option value="QUALITY_ASC">Quality crescente</option><option value="QUALITY_DESC">Quality decrescente</option><option value="CODE">Codice</option><option value="CATEGORY">Categoria</option><option value="FAMILY">Famiglia</option><option value="STATUS">Status</option></select></label></div></header><div className={styles.filterRow}>{filters.map(([label,value])=><button type="button" key={value} className={filter===value?styles.active:""} onClick={()=>setFilter(value)}>{label}</button>)}</div><div className={styles.galleryGrid}>{shown.map(result=><CaseCard key={result.exercise.id} result={result}/>)}</div><div className={styles.pagination}><button type="button" disabled={page===1} onClick={()=>setPage(value=>Math.max(1,value-1))}>← Precedente</button><span>Pagina {page} di {pages}</span><button type="button" disabled={page===pages} onClick={()=>setPage(value=>Math.min(pages,value+1))}>Successiva →</button></div></section>;
}

function HumanReview({report}:{report:FullAuditReport}){const[nonce,setNonce]=useState("initial"),items=useMemo(()=>selectRandomValidForHumanReview(report,nonce,30),[report,nonce]);return <section><header className={styles.sectionHeading}><div><h2>RANDOM HUMAN REVIEW</h2><p>30 VALID distribuiti tra famiglie e categorie.</p></div><button type="button" onClick={()=>setNonce(`${Date.now()}:${Math.random()}`)}>NEW RANDOM SET</button></header><div className={styles.reviewGrid}>{items.map(item=><CaseCard key={item.exercise.id} result={item}/>)}</div></section>}

export function FullCatalogAudit({records}:{records:Exercise[]}){
  const report=useMemo(()=>createFullCatalogAuditReport(records),[records]),[prepareWrite,setPrepareWrite]=useState(false);
  return <section className={styles.dashboard}><section className={styles.integrityBanner}><div><b>FULL CATALOG AUDIT</b><span>100% del catalogo · nessun campionamento · nessun seed · nessun salvataggio</span></div><strong>{report.analyzed===report.catalogSize?"INTEGRITY OK":"INTEGRITY CHECK"}</strong></section>
    <textarea data-testid="full-audit-baseline-json" hidden readOnly value={JSON.stringify({summary:{catalogSize:report.catalogSize,analyzed:report.analyzed,notAnalyzed:report.notAnalyzed,status:report.status,quality:report.quality,semantic:report.semantic,collisions:report.collisions,ballIntegrity:report.ballIntegrity,multiPhase:report.multiPhase,participants:report.participants,equipment:report.equipment,layout:report.layout},rows:fullAuditExportRows(report)})}/>
    <section className={styles.kpis}><Kpi label="TOTAL CATALOG" value={report.catalogSize}/><Kpi label="ANALYZED" value={report.analyzed} tone={report.analyzed===report.catalogSize?"ok":"bad"}/><Kpi label="NOT ANALYZED" value={report.notAnalyzed} tone={report.notAnalyzed?"bad":"ok"}/><Kpi label="VALID" value={report.status.valid}/><Kpi label="VALID WITH WARNINGS" value={report.status.warning}/><Kpi label="NEEDS REVIEW" value={report.status.review} tone={report.status.review?"warn":"ok"}/><Kpi label="GENERATION ERRORS" value={report.status.generationError} tone={report.status.generationError?"bad":"ok"}/><Kpi label="QUALITY MEDIA" value={`${report.quality}/100`}/><Kpi label="SEMANTIC COVERAGE" value={`${report.semantic.coverage}%`} detail={`${report.semantic.specific} specific · ${report.semantic.generic} generic · ${report.semantic.unknown} unknown`}/><Kpi label="REAL COLLISIONS" value={report.collisions.real.total} detail={`${report.collisions.real.exercises} esercizi · ${report.collisions.real.percentage}%`} tone={report.collisions.real.total?"bad":"ok"}/><Kpi label="VISUAL INTERFERENCES" value={report.collisions.visual.total}/><Kpi label="EXPECTED INTERSECTIONS" value={report.collisions.expected.total}/></section>
    <section className={styles.actions}><p>Audit completato in <b>{report.durationMs} ms</b>. I tactical_diagram sono stati generati solo in memoria.</p><button type="button" onClick={()=>exportJson(report)}>EXPORT FULL AUDIT JSON</button><button type="button" onClick={()=>exportCsv(report)}>EXPORT FULL AUDIT CSV</button><button type="button" onClick={()=>setPrepareWrite(value=>!value)}>{prepareWrite?"CLOSE WRITE DRY RUN":"PREPARE CATALOG WRITE"}</button></section>
    <section className={styles.criteria}><h2>SUCCESS CRITERIA · valutazione non correttiva</h2>{Object.entries(report.successCriteria).map(([key,value])=><span key={key} className={value?styles.pass:styles.check}>{key.replaceAll(/([A-Z])/g," $1").toUpperCase()} · {value?"PASS":"CHECK"}</span>)}</section>
    {prepareWrite&&<CatalogWriteDryRun records={records}/>} 
    <FinalNineRemediation/><FamilyTable report={report}/><IntegrityPanels report={report}/><RealCollisionCases report={report}/>
    {report.failures.length>0&&<section><h2>GENERATION ERRORS</h2><div className={styles.largeCases}>{report.failures.map(item=><CaseCard key={item.exercise.id} result={item} large/>)}</div></section>}
    <section><h2>TOP 30 WORST CASES</h2><div className={styles.worstGrid}>{report.worstCases.map(result=><CaseCard key={result.exercise.id} result={result} large/>)}</div></section>
    <HumanReview report={report}/><Gallery report={report}/>
  </section>;
}
