"use client";

import { useEffect, useMemo, useState } from "react";
import { AuthGate } from "../../auth-gate";
import { ExerciseTacticalBoard } from "../../components/exercise-tactical-board";
import { supabase } from "../../../lib/supabase";
import { auditTags, createTacticalCatalogAudit, selectCatalogAuditSample, summarizeTacticalAudit, type TacticalAuditItem, type TacticalAuditStatus } from "../../../lib/tactical-catalog-audit";
import type { CatalogPhase, Exercise } from "../../../lib/types";

type RecordValue=Record<string,unknown>;
const asText=(value:unknown,fallback="")=>typeof value==="string"?value:fallback;
const asNumber=(value:unknown,fallback=0)=>typeof value==="number"?value:Number(value)||fallback;
function normalizeExercise(record:RecordValue):Exercise{const category=(record.category??{})as RecordValue,subcategory=(record.subcategory??{})as RecordValue;return{...record,id:asText(record.id),codice:asText(record.codice),nome:asText(record.nome),category_id:asNumber(record.category_id),subcategory_id:asNumber(record.subcategory_id),categoria:asText(record.categoria,asText(category.nome)),sottocategoria:asText(record.sottocategoria,asText(subcategory.nome)),fase:asText(record.fase,"Analitico")as CatalogPhase,obiettivo:asText(record.obiettivo),descrizione:asText(record.descrizione),durata_min:asNumber(record.durata_min),portieri_min:asNumber(record.portieri_min,1),portieri_max:asNumber(record.portieri_max,1),intensita:asText(record.intensita,"Media")as Exercise["intensita"],difficolta:asNumber(record.difficolta,1)as Exercise["difficolta"],materiale:asText(record.materiale),variante:record.variante?asText(record.variante):null,coaching_points:asText(record.coaching_points),errori_comuni:asText(record.errori_comuni),schema_step_1:record.schema_step_1?asText(record.schema_step_1):null,schema_step_2:record.schema_step_2?asText(record.schema_step_2):null,schema_step_3:record.schema_step_3?asText(record.schema_step_3):null,schema_step_4:record.schema_step_4?asText(record.schema_step_4):null,schema_step_5:record.schema_step_5?asText(record.schema_step_5):null,schema_step_6:record.schema_step_6?asText(record.schema_step_6):null,scenario_gara:record.scenario_gara?asText(record.scenario_gara):null,numero_azioni:record.numero_azioni?asText(record.numero_azioni):null,schema_url:record.schema_url?asText(record.schema_url):null,foto_url:record.foto_url?asText(record.foto_url):null,tactical_diagram:(record.tactical_diagram??null)as Exercise["tactical_diagram"],diagram_source:(record.diagram_source??null)as Exercise["diagram_source"],attivo:record.attivo!==false};}

const statusOptions:Array<[string,TacticalAuditStatus|"ALL"]>=[["TUTTI","ALL"],["SOLO NEEDS REVIEW","NEEDS_REVIEW"],["SOLO WARNING","VALID_WITH_WARNINGS"],["SOLO VALID","VALID"]];
const quickFilters=["TUTTI","CONI","CINESINI","PORTICINE","SAGOME","OSTACOLI","MULTI-BALL","ONE_V_ONE","CROSS","POSITIONING"];
function Flag({valid,label}:{valid:boolean;label:string}){return <span className={`audit-flag ${valid?"is-valid":"is-warning"}`}>{label}: {valid?"VALID":"CHECK"}</span>;}

function AuditCard({item}:{item:TacticalAuditItem}){const[open,setOpen]=useState(false),steps=[item.exercise.descrizione,item.exercise.schema_step_1,item.exercise.schema_step_2].filter(Boolean).join(" · ");return <article className="audit-card"><header><div><span>{item.exercise.codice}</span><h2>{item.exercise.nome}</h2><p>{item.exercise.categoria} · {item.exercise.sottocategoria}</p></div><div className="audit-score"><strong>{item.qualityScore}</strong><small>/100</small></div></header><div className="audit-badges"><span className={`setup-status is-${item.status.toLowerCase()}`}>{item.status}</span><span>{item.family}</span>{item.alternativePreview&&<span>AUTOMATIC PREVIEW — NOT SAVED</span>}</div><p className="audit-description">{steps||"Svolgimento non disponibile"}</p><div className="audit-validation-grid"><Flag valid={item.semanticValidation.valid} label="SEMANTIC"/><Flag valid={item.equipmentValidation.valid} label="EQUIPMENT"/><Flag valid={item.relationValidation.valid} label="RELATION"/><Flag valid={item.layoutValidation.valid} label={`LAYOUT ${item.layoutValidation.density}`}/></div><div className="audit-debug-grid"><section><b>MATERIALI ORIGINALI</b><p>{item.equipmentValidation.original}</p><b>INTERPRETATI</b><p>{item.equipmentValidation.interpreted.join(" · ")||"Nessun equipment funzionale"}</p><b>RAPPRESENTATI</b><p>{item.equipmentValidation.represented.join(" · ")||"Nessuno"}</p></section><section><b>PARTECIPANTI</b><p>{item.participants.declared} → {item.participants.displayed}</p><b>ACTIONS</b><ol>{item.actions.map(action=><li key={action}>{action}</li>)}</ol></section></div>{item.reasons.length>0&&<div className="audit-reasons"><b>MOTIVI</b><ul>{item.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></div>}<button type="button" className="secondary" onClick={()=>setOpen(value=>!value)}>{open?"Nascondi schema":"Apri preview in memoria"}</button>{open&&<ExerciseTacticalBoard diagram={item.diagram} rendererVersion="v2-final" className="audit-board"/>}</article>;}

function AuditPage(){const[records,setRecords]=useState<Exercise[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[status,setStatus]=useState<TacticalAuditStatus|"ALL">("ALL"),[quick,setQuick]=useState("TUTTI"),[category,setCategory]=useState("ALL"),[family,setFamily]=useState("ALL"),[sort,setSort]=useState("quality");
  useEffect(()=>{let active=true;async function load(){if(!supabase){setError("Supabase non configurato");setLoading(false);return;}const result=await supabase.from("exercises").select("*, category:exercise_categories(id,nome,attivo), subcategory:exercise_subcategories(id,category_id,nome,fase,attivo)").eq("attivo",true).order("codice");if(!active)return;if(result.error)setError(result.error.message);else setRecords((result.data??[]).map(item=>normalizeExercise(item as RecordValue)));setLoading(false);}void load();return()=>{active=false;};},[]);
  const sample=useMemo(()=>selectCatalogAuditSample(records,30),[records]),items=useMemo(()=>sample.map(createTacticalCatalogAudit),[sample]),summary=useMemo(()=>summarizeTacticalAudit(items),[items]),categories=useMemo(()=>[...new Set(items.map(item=>item.exercise.categoria))].sort(),[items]),families=useMemo(()=>[...new Set(items.map(item=>item.family))].sort(),[items]);
  const filtered=useMemo(()=>items.filter(item=>status==="ALL"||item.status===status).filter(item=>category==="ALL"||item.exercise.categoria===category).filter(item=>family==="ALL"||item.family===family).filter(item=>quick==="TUTTI"||(["ONE_V_ONE","CROSS","POSITIONING"].includes(quick)?item.family===quick:auditTags(item.exercise).includes(quick))).sort((a,b)=>sort==="quality"?a.qualityScore-b.qualityScore:a.exercise.codice.localeCompare(b.exercise.codice)),[items,status,category,family,quick,sort]);
  const exportJson=()=>{const payload=items.map(item=>({codice:item.exercise.codice,nome:item.exercise.nome,categoria:item.exercise.categoria,famiglia:item.family,status:item.status,quality_score:item.qualityScore,warnings:item.reasons})),url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"})),anchor=document.createElement("a");anchor.href=url;anchor.download="tactical-catalog-audit.json";anchor.click();URL.revokeObjectURL(url);};
  if(loading)return <main className="catalog-audit-page"><p>Caricamento del campione reale…</p></main>;if(error)return <main className="catalog-audit-page"><p>Audit non disponibile: {error}</p></main>;
  return <main className="catalog-audit-page"><header><span className="eyebrow">Development audit · preview only</span><h1>Tactical Catalog Audit</h1><p>Campione diversificato di esercizi reali. Nessun diagramma viene salvato.</p></header><section className="audit-kpis"><div><b>ESERCIZI ANALIZZATI</b><strong>{summary.total}</strong></div><div><b>VALID</b><strong>{summary.valid}</strong></div><div><b>VALID WITH WARNINGS</b><strong>{summary.warnings}</strong></div><div><b>NEEDS REVIEW</b><strong>{summary.review}</strong></div><div><b>QUALITY MEDIA</b><strong>{summary.quality}/100</strong></div></section><section className="audit-summary"><div><h2>Statistiche per famiglia</h2>{summary.families.map(([name,row])=><p key={name}><b>{name}</b>: {row.total} test · {row.valid} valid · {row.warnings} warning · {row.review} review</p>)}</div><div><h2>Equipment riconosciuto</h2>{summary.equipment.map(row=><p key={row.tag}><b>{row.tag}</b>: {row.total} · problematici {row.problematic}</p>)}</div><div><h2>Error patterns</h2>{summary.patterns.slice(0,8).map(([reason,count])=><p key={reason}>{reason}: <b>{count}</b></p>)}</div></section><section className="audit-toolbar"><div className="audit-quick">{statusOptions.map(([label,value])=><button type="button" key={value} className={status===value?"active":""} onClick={()=>setStatus(value)}>{label}</button>)}</div><div className="audit-quick">{quickFilters.map(value=><button type="button" key={value} className={quick===value?"active":""} onClick={()=>setQuick(value)}>{value}</button>)}</div><label>Categoria<select value={category} onChange={event=>setCategory(event.target.value)}><option value="ALL">Tutte</option>{categories.map(value=><option key={value}>{value}</option>)}</select></label><label>Famiglia<select value={family} onChange={event=>setFamily(event.target.value)}><option value="ALL">Tutte</option>{families.map(value=><option key={value}>{value}</option>)}</select></label><label>Ordina<select value={sort} onChange={event=>setSort(event.target.value)}><option value="quality">Quality score crescente</option><option value="code">Codice</option></select></label><button type="button" onClick={exportJson}>EXPORT AUDIT JSON</button></section><p className="audit-result-count">Mostrati {filtered.length} di {items.length} · casi peggiori per primi</p><section className="audit-list">{filtered.map(item=><AuditCard key={item.exercise.id} item={item}/>)}</section></main>;}

export default function Page(){return <AuthGate><AuditPage/></AuthGate>;}
