"use client";

import { useMemo } from "react";
import { createSemanticGapAuditReport, GENERIC_ROOT_CAUSE_LABELS, complexityLabel, type SemanticGapCase } from "../../../lib/tactical-semantic-gap-audit";
import type { TacticalAuditItem } from "../../../lib/tactical-catalog-audit";
import styles from "./semantic-gap-audit.module.css";

function List({values,empty="Nessuno"}:{values:string[];empty?:string}){return values.length?<ul>{values.map(value=><li key={value}>{value}</li>)}</ul>:<p className={styles.muted}>{empty}</p>;}
function RequiredEquipment({value}:{value:SemanticGapCase}){return value.diagnostic.requiredEquipment.length?<ul>{value.diagnostic.requiredEquipment.map(row=><li key={row.type}>{row.type}: required {row.required}, rendered {row.rendered}</li>)}</ul>:<p className={styles.muted}>Nessun equipment semanticamente required</p>;}
function GapCaseCard({value,review=false}:{value:SemanticGapCase;review?:boolean}){const exercise=value.item.exercise;return <article className={styles.caseCard}><header><div><b>{exercise.codice}</b><h3>{exercise.nome}</h3><p>{exercise.categoria} · {exercise.sottocategoria}</p></div><div className={styles.score}><strong>{value.item.qualityScore}</strong><small>{complexityLabel(value.complexity)}</small><span>{value.item.status}</span></div></header><div className={styles.caseGrid}><section><h4>DESCRIZIONE COMPLETA</h4><p>{value.description||"Non disponibile"}</p><h4>SVOLGIMENTO</h4><List values={value.steps}/><h4>MATERIALI</h4><p>{exercise.materiale||"Non indicati"}</p></section><section><h4>SEMANTIC FAMILY</h4><p><b>{value.item.family}</b> · confidence {value.semanticConfidence}%</p><h4>PHRASES RICONOSCIUTE</h4><List values={value.recognizedPhrases}/><h4>PHRASES NON RICONOSCIUTE</h4><List values={value.unrecognizedPhrases}/>{value.generic&&<><h4>GENERIC ROOT CAUSE</h4><p><b>{value.generic.cause} · {GENERIC_ROOT_CAUSE_LABELS[value.generic.cause]}</b></p><p>{value.generic.recommendation}</p></>}</section><section><h4>EQUIPMENT REQUIRED</h4><RequiredEquipment value={value}/><h4>PARTICIPANTS</h4><p>{value.item.participants.declared} · {value.item.participants.displayed}</p><List values={value.diagnostic.activeParticipants.map(row=>`${row.id} · ${row.type} · ${row.role}`)}/><h4>ACTIONS GENERATE</h4><List values={value.diagnostic.generatedActions.map(action=>`${action.sequence}. ${action.type}: ${action.from} → ${action.to} · confidence ${Math.round(action.confidence*100)}%`)}/></section></div>{review&&<section className={styles.reviewCause}><div><b>ROOT CAUSE</b><p>{value.diagnostic.rootCause}</p></div><div><b>PIPELINE STEP</b><p>{value.diagnostic.pipelineStage}</p></div><div><b>SEVERITY</b><p>{value.diagnostic.severity}</p></div><div><b>MINIMAL FIX PROPOSAL</b><p>{value.minimalFix}</p></div></section>}</article>;}

function MetricRow({title,success,failed}:{title:string;success:number|string;failed:number|string}){return <div><b>{title}</b><span>{success}</span><span>{failed}</span></div>;}

export function SemanticGapAudit({items}:{items:TacticalAuditItem[]}){const report=useMemo(()=>createSemanticGapAuditReport(items),[items]);return <section className={styles.dashboard}><section className={styles.kpis}><div><b>TARGET UNICI</b><strong>{report.target.length}</strong></div><div><b>GENERIC / UNKNOWN</b><strong>{report.generic.length}</strong></div><div><b>RECOVERABLE GENERIC</b><strong>{report.recoverable.length}</strong></div><div><b>TRUE GENERIC</b><strong>{report.trueGeneric.length}</strong></div><div><b>NEEDS REVIEW</b><strong>{report.reviews.length}</strong></div><div><b>MEDIUM COMPLEXITY</b><strong>{report.medium.length}</strong></div><div><b>POTENTIAL COVERAGE</b><strong>{report.potentialCoverage}%</strong></div></section>
  <section className={styles.panel}><h2>A. GENERIC/UNKNOWN DIAGNOSTIC</h2><div className={styles.causeGrid}>{report.causeCounts.map(row=><div key={row.cause}><b>{row.cause}</b><strong>{row.count}</strong><p>{row.label}</p><small>{row.codes.join(" · ")||"—"}</small></div>)}</div><div className={styles.caseList}>{report.generic.map(value=><GapCaseCard key={value.item.exercise.id} value={value}/>)}</div></section>
  <section className={styles.panel}><h2>B. NEEDS REVIEW DIAGNOSTIC</h2><div className={styles.caseList}>{report.reviews.map(value=><GapCaseCard key={value.item.exercise.id} value={value} review/>)}</div></section>
  <section className={styles.panel}><h2>C. MEDIUM COMPLEXITY ANALYSIS</h2><div className={styles.mediumCompare}><div><b>METRICA</b><span>RIUSCITI ({report.mediumAnalysis.successful.length})</span><span>REVIEW ({report.mediumAnalysis.failed.length})</span></div><MetricRow title="Actions medie" success={report.mediumAnalysis.successfulMetrics.averageActions} failed={report.mediumAnalysis.failedMetrics.averageActions}/><MetricRow title="Fasi medie" success={report.mediumAnalysis.successfulMetrics.averagePhases} failed={report.mediumAnalysis.failedMetrics.averagePhases}/><MetricRow title="Equipment required medio" success={report.mediumAnalysis.successfulMetrics.averageRequiredEquipment} failed={report.mediumAnalysis.failedMetrics.averageRequiredEquipment}/><MetricRow title="Origini palla medie" success={report.mediumAnalysis.successfulMetrics.averageBallOrigins} failed={report.mediumAnalysis.failedMetrics.averageBallOrigins}/><MetricRow title="Partecipanti medi" success={report.mediumAnalysis.successfulMetrics.averageParticipants} failed={report.mediumAnalysis.failedMetrics.averageParticipants}/><MetricRow title="Transition actions" success={report.mediumAnalysis.successfulMetrics.transitionActions} failed={report.mediumAnalysis.failedMetrics.transitionActions}/></div><h3>MEDIUM COMPLEXITY FAILURE PATTERNS</h3><div className={styles.patterns}>{report.mediumAnalysis.patterns.map(pattern=><p key={pattern.label}><b>{pattern.label}</b><span>{pattern.codes.join(" · ")}</span></p>)}</div><div className={styles.caseList}>{report.medium.map(value=><GapCaseCard key={value.item.exercise.id} value={value} review={value.item.status==="NEEDS_REVIEW"}/>)}</div></section>
  <section className={styles.panel}><h2>D. WORDING GAPS</h2><p className={styles.intro}>Espressioni estratte esclusivamente dal campione corrente; nessun sinonimo viene applicato al generatore.</p><div className={styles.wording}>{report.wording.map(row=><p key={row.phrase}><b>{row.phrase}</b><span>{row.count} occorrenze · {row.codes.join(" · ")}</span></p>)}</div></section>
  <section className={styles.panel}><h2>TOP FIX OPPORTUNITIES</h2><div className={styles.opportunities}>{report.opportunities.map((row,index)=><article key={row.rootCause}><strong>{index+1}</strong><div><h3>{row.rootCause}</h3><p>Esercizi: {row.codes.join(" · ")}</p><p>Famiglie: {row.families.join(" · ")}</p></div><span>Rischio {row.risk}<br/>Difficoltà {row.difficulty}<br/>Coverage recuperabile +{row.coverageRecovery}</span></article>)}</div><h3>REGRESSION SAFETY · FAMIGLIE STABLE</h3><div className={styles.safety}>{report.stableFamilies.map(row=><p key={row.family}><b>{row.family}</b><span>Proteggere da sinonimi troppo generici, precedenze errate e modifiche trasversali a ownership/transizioni. {row.valid}/{row.total} valid, {row.warnings} warning.</span></p>)}</div></section>
 </section>;}
