-- Standard definitivo Catalogo Esercizi e import prima categoria.
-- Import idempotente: codice è univoco e ON CONFLICT aggiorna senza duplicare.

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='exercises' and column_name='numero_portieri_min') then alter table public.exercises rename column numero_portieri_min to portieri_min; end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='exercises' and column_name='numero_portieri_max') then alter table public.exercises rename column numero_portieri_max to portieri_max; end if;
end $$;

-- Le colonne testuali della prima versione restano disponibili solo per
-- compatibilità storica, ma non devono bloccare nuovi esercizi.
alter table public.exercises alter column legacy_category drop not null;
alter table public.exercises alter column legacy_subcategory drop not null;

alter table public.exercises add column if not exists categoria text;
alter table public.exercises add column if not exists sottocategoria text;
alter table public.exercises add column if not exists fase text;
alter table public.exercises add column if not exists difficolta smallint not null default 1;
alter table public.exercises add column if not exists coaching_points text not null default '';
alter table public.exercises add column if not exists errori_comuni text not null default '';
alter table public.exercises add column if not exists schema_url text;
alter table public.exercises add column if not exists foto_url text;

update public.exercises e set
  categoria = c.nome,
  sottocategoria = s.nome,
  fase = s.fase
from public.exercise_categories c, public.exercise_subcategories s
where e.category_id = c.id and e.subcategory_id = s.id
  and (e.categoria is null or e.sottocategoria is null or e.fase is null);

alter table public.exercises alter column categoria set not null;
alter table public.exercises alter column sottocategoria set not null;
alter table public.exercises alter column fase set not null;
alter table public.exercises drop constraint if exists exercises_difficolta_check;
alter table public.exercises drop constraint if exists exercises_fase_check;
alter table public.exercises add constraint exercises_difficolta_check check (difficolta in (1, 2, 3));
alter table public.exercises add constraint exercises_fase_check check (fase in ('Analitico', 'Disturbo', 'Situazionale'));
create index if not exists exercises_catalog_filters_idx on public.exercises (categoria, sottocategoria, fase, intensita, difficolta, attivo);

insert into public.exercises (
  codice, nome, category_id, subcategory_id, categoria, sottocategoria, fase,
  obiettivo, descrizione, durata_min, portieri_min, portieri_max, intensita,
  difficolta, materiale, variante, coaching_points, errori_comuni,
  schema_url, foto_url, attivo
) values
  ('GK-PRA-001', 'Presa alta frontale in posizione', 1, 1, 'Tecnica presa alta e rasoterra', 'Presa alta analitica', 'Analitico', 'Consolidare forma delle mani, allineamento corpo-palla e assorbimento della presa alta.', 'Portiere in posizione di attesa a 4-5 m dal preparatore. Il preparatore serve palloni con le mani sopra la linea del viso e del capo. Il portiere esegue la presa alta, porta il pallone al petto e restituisce rapidamente.', 8, 1, 4, 'Bassa', 1, '6-8 palloni, 2 coni', 'Alternare palloni leggermente a destra e sinistra senza richiedere tuffo.', 'Gomiti morbidi; mani dietro la palla; pollici orientati; corpo stabile.', 'Mani rigide; arretrare all''impatto; presa davanti al viso senza assorbire.', null, null, true),
  ('GK-PRA-002', 'Presa alta dopo micro-spostamento', 1, 1, 'Tecnica presa alta e rasoterra', 'Presa alta analitica', 'Analitico', 'Associare piccoli aggiustamenti dei piedi alla corretta presa alta.', 'Due coni distanti 2 m. Il portiere parte al centro, riceve un comando dx/sx, effettua 2-3 passi di adattamento verso il cono e torna in linea per una presa alta servita frontalmente.', 10, 1, 4, 'Bassa', 1, '6-8 palloni, 2 coni', 'Il preparatore varia ritmo e altezza del servizio.', 'Restare bassi durante lo spostamento; arrestarsi prima della presa; mani pronte.', 'Incrociare troppo i piedi; ricevere ancora in movimento; baricentro alto.', null, null, true),
  ('GK-PRA-003', 'Presa alta con elevazione monopodalica', 1, 2, 'Tecnica presa alta e rasoterra', 'Presa alta analitica 2', 'Analitico', 'Allenare presa sopra il capo ed elevazione controllata.', 'Il preparatore serve palloni arcuati a 2-3 m. Il portiere avanza, stacca su una gamba, porta il ginocchio opposto in protezione e blocca la palla nel punto più alto possibile.', 10, 1, 3, 'Media', 2, '6 palloni, 3 coni', 'Alternare stacco destro e sinistro secondo lato del servizio.', 'Attaccare il pallone; punto di presa alto; atterraggio equilibrato.', 'Stacco sotto la palla; presa bassa; atterraggio su piedi rigidi.', null, null, true),
  ('GK-PRA-004', 'Presa alta dopo passo incrociato', 1, 2, 'Tecnica presa alta e rasoterra', 'Presa alta analitica 2', 'Analitico', 'Migliorare copertura laterale e timing della presa alta.', 'Il portiere parte centrale. Su indicazione, effettua un passo incrociato e uno di aggiustamento verso destra o sinistra; il preparatore serve alto nella nuova zona di competenza.', 10, 1, 4, 'Media', 2, '6-8 palloni, 4 coni', 'Aumentare progressivamente la distanza laterale.', 'Primo passo deciso; ultimo passo corto; tronco orientato alla palla.', 'Passi troppo lunghi; perdita di frontalità; salto senza equilibrio.', null, null, true),
  ('GK-PRA-005', 'Raccolta rasoterra centrale', 1, 3, 'Tecnica presa alta e rasoterra', 'Presa rasoterra analitica', 'Analitico', 'Curare la tecnica base di raccolta con corpo dietro la palla.', 'Preparatore a 6-8 m. Serve rasoterra centrali a velocità progressiva. Il portiere flette anche e ginocchia, porta mani a terra e raccoglie con il corpo dietro la traiettoria.', 8, 1, 4, 'Bassa', 1, '8 palloni', 'Inserire una breve partenza sul posto prima del servizio.', 'Testa sopra la palla; mani basse; gambe proteggono un eventuale errore.', 'Piegarsi solo con la schiena; gambe divaricate; mani tardive.', null, null, true),
  ('GK-PRA-006', 'Raccolta rasoterra diagonale', 1, 3, 'Tecnica presa alta e rasoterra', 'Presa rasoterra analitica', 'Analitico', 'Allenare adattamento del corpo su palloni bassi leggermente laterali.', 'Il preparatore alterna servizi rasoterra 50-80 cm a destra e sinistra. Il portiere effettua un piccolo passo di allineamento e raccoglie senza cadere.', 10, 1, 4, 'Bassa', 1, '8 palloni, 2 coni', 'Rendere casuale il lato e aumentare leggermente la velocità.', 'Portare il corpo dietro la linea; passo di aggiustamento; presa morbida.', 'Allungare solo le braccia; piedi fermi; ginocchio interno aperto.', null, null, true),
  ('GK-PRA-007', 'Raccolta dopo spostamento laterale', 1, 4, 'Tecnica presa alta e rasoterra', 'Presa rasoterra analitica 2', 'Analitico', 'Integrare footwork e presa rasoterra.', 'Portiere tra due coni. Tocca il cono chiamato dal preparatore, rientra al centro e riceve un tiro rasoterra. Alternare lato e velocità.', 10, 1, 4, 'Media', 2, '8 palloni, 2 coni', 'Il tiro può essere centrale o sul lato opposto al cono toccato.', 'Rientrare con passi brevi; stabilizzarsi; mani già orientate verso terra.', 'Arrivare in ritardo; incrociare i piedi in rientro; raccogliere in corsa.', null, null, true),
  ('GK-PRA-008', 'Raccolta con partenza avanti-indietro', 1, 4, 'Tecnica presa alta e rasoterra', 'Presa rasoterra analitica 2', 'Analitico', 'Migliorare regolazione della distanza prima della presa bassa.', 'Un cono 2 m avanti e uno 1 m dietro. Al comando il portiere tocca uno dei due, ritorna in posizione e affronta un servizio rasoterra.', 10, 1, 4, 'Media', 2, '8 palloni, 3 coni', 'Variare il comando anche durante il movimento.', 'Frenata controllata; postura pronta; primo passo reattivo.', 'Baricentro alto; frenata lunga; mani non pronte.', null, null, true),
  ('GK-PRA-009', 'Presa su rimbalzo frontale controllato', 1, 5, 'Tecnica presa alta e rasoterra', 'Presa con rimbalzo analitica', 'Analitico', 'Imparare a leggere e assorbire il primo rimbalzo.', 'Il preparatore lascia rimbalzare o serve il pallone affinché tocchi terra 2-3 m davanti al portiere. Il portiere segue la traiettoria e blocca dopo il rimbalzo.', 10, 1, 4, 'Bassa', 1, '8 palloni', 'Variare punto di rimbalzo e altezza senza cambiare velocità.', 'Occhi sulla palla fino alla presa; mani morbide; corpo dietro.', 'Anticipare troppo le mani; perdere la traiettoria dopo il rimbalzo.', null, null, true),
  ('GK-PRA-010', 'Rimbalzo medio con presa al tronco', 1, 5, 'Tecnica presa alta e rasoterra', 'Presa con rimbalzo analitica', 'Analitico', 'Allenare lettura di una palla che sale dal terreno verso busto/viso.', 'Da 7-9 m il preparatore calcia palloni con un rimbalzo controllato. Il portiere deve scegliere altezza delle mani e bloccare senza respingere.', 10, 1, 4, 'Media', 2, '8 palloni', 'Alternare palloni che arrivano al petto e sopra le spalle.', 'Aggiustare piedi prima dell''impatto; assorbire verso il corpo.', 'Mani troppo distanti; corpo arretrato; tentare sempre la stessa presa.', null, null, true),
  ('GK-PRA-011', 'Rimbalzo laterale con passo di aggiustamento', 1, 6, 'Tecnica presa alta e rasoterra', 'Presa con rimbalzo analitica 2', 'Analitico', 'Leggere il rimbalzo fuori asse e riallineare il corpo.', 'Il preparatore serve palloni con rimbalzo a destra o sinistra. Il portiere si muove lateralmente mantenendo il corpo dietro la traiettoria e blocca.', 10, 1, 4, 'Media', 2, '8 palloni, 2 coni', 'Aumentare l''ampiezza laterale mantenendo la presa senza tuffo.', 'Piccoli passi; mani seguono il pallone; testa stabile.', 'Incrocio eccessivo; presa laterale al corpo; fissare il punto a terra anziché la palla.', null, null, true),
  ('GK-PRA-012', 'Rimbalzo dopo pre-attivazione piedi', 1, 6, 'Tecnica presa alta e rasoterra', 'Presa con rimbalzo analitica 2', 'Analitico', 'Associare rapidità piedi e controllo della presa su traiettoria sporca.', 'Il portiere esegue 4 tocchi rapidi tra due coni bassi, esce dalla zona e riceve immediatamente un pallone con rimbalzo frontale.', 10, 1, 4, 'Media', 2, '8 palloni, 4 coni bassi', 'Cambiare pattern dei piedi: avanti-indietro o laterale.', 'Terminare l''attivazione in equilibrio; riagganciare subito visivamente la palla.', 'Guardare i piedi troppo a lungo; ricevere sbilanciati; mani rigide.', null, null, true),
  ('GK-PRA-013', 'Presa alta dietro sagoma', 1, 7, 'Tecnica presa alta e rasoterra', 'Presa alta con disturbo', 'Disturbo', 'Mantenere lettura e tecnica con visuale parzialmente coperta.', 'Una sagoma è posta 2 m davanti al portiere. Il preparatore serve palloni alti da dietro la sagoma; il portiere deve leggere tardi la traiettoria e bloccare.', 10, 1, 3, 'Media', 2, '6-8 palloni, 1 sagoma', 'Il preparatore cambia leggermente posizione dietro la sagoma.', 'Testa attiva; primo passo rapido; attaccare il pallone.', 'Spostarsi troppo presto; aspettare la palla; perdere equilibrio.', null, null, true),
  ('GK-PRA-014', 'Presa alta con contatto leggero', 1, 7, 'Tecnica presa alta e rasoterra', 'Presa alta con disturbo', 'Disturbo', 'Stabilizzare la presa in presenza di contatto controllato.', 'Un compagno vicino al portiere crea un contatto leggero con spalla o avambraccio mentre il preparatore serve un pallone alto. Il portiere protegge spazio e palla.', 10, 2, 4, 'Media', 2, '6 palloni, casacca', 'Aumentare gradualmente il timing del disturbo senza contatti pericolosi.', 'Base stabile; comunicazione; presa nel punto più alto possibile.', 'Cercare il contatto anziché la palla; gomiti aperti; atterraggio instabile.', null, null, true),
  ('GK-PRA-015', 'Presa alta con traffico passivo', 1, 8, 'Tecnica presa alta e rasoterra', 'Presa alta con disturbo 2', 'Disturbo', 'Leggere il pallone attraverso giocatori che occupano lo spazio.', 'Due compagni attraversano lentamente la zona davanti al portiere senza contendere la palla. Il preparatore serve alto; il portiere deve muoversi e trovare la linea di presa.', 12, 3, 5, 'Media', 2, '6 palloni, 4 coni, 2 casacche', 'Rendere i movimenti dei compagni meno prevedibili.', 'Scansione prima del servizio; comunicare; decidere una linea netta.', 'Fermarsi dietro al traffico; saltare verticalmente senza avanzare.', null, null, true),
  ('GK-PRA-016', 'Presa alta dopo disturbo visivo dinamico', 1, 8, 'Tecnica presa alta e rasoterra', 'Presa alta con disturbo 2', 'Disturbo', 'Recuperare rapidamente la traiettoria dopo occlusione visiva.', 'Un compagno passa davanti al portiere nel momento del servizio. Il portiere vede la palla solo nella seconda parte della traiettoria e deve bloccarla.', 10, 2, 4, 'Media', 2, '6-8 palloni, 2 coni', 'Variare direzione e velocità del giocatore che oscura.', 'Occhi subito sulla palla appena riappare; piedi attivi; decisione rapida.', 'Arretrare; bloccare i piedi; tentare una presa fuori tempo.', null, null, true),
  ('GK-PRA-017', 'Rasoterra attraverso porticine', 1, 9, 'Tecnica presa alta e rasoterra', 'Presa rasoterra con disturbo', 'Disturbo', 'Allenare presa bassa con visuale e traiettoria limitate.', 'Due porticine di coni creano un corridoio davanti al portiere. Il preparatore calcia rasoterra attraverso una delle due aperture; il portiere legge tardi e raccoglie.', 10, 1, 4, 'Media', 2, '8 palloni, 6 coni', 'Ridurre la larghezza delle porticine o alternare all''ultimo il corridoio.', 'Posizione bassa; piccoli aggiustamenti; corpo dietro alla palla.', 'Fare un grande passo; mani in ritardo; sbilanciarsi lateralmente.', null, null, true),
  ('GK-PRA-018', 'Rasoterra con ostacolo visivo', 1, 9, 'Tecnica presa alta e rasoterra', 'Presa rasoterra con disturbo', 'Disturbo', 'Reagire a un pallone basso visto tardi.', 'Una sagoma centrale copre la visuale. Il preparatore calcia rasoterra a destra o sinistra della sagoma. Il portiere deve uscire dalla linea visiva e raccogliere.', 10, 1, 3, 'Media', 2, '8 palloni, 1 sagoma', 'Il preparatore può variare anche la distanza dalla sagoma.', 'Testa e piedi reattivi; non anticipare il lato; raccogliere con corpo dietro.', 'Indovinare il lato; aprire troppo le gambe; tuffarsi inutilmente.', null, null, true),
  ('GK-PRA-019', 'Rasoterra deviato da porta-coni', 1, 10, 'Tecnica presa alta e rasoterra', 'Presa rasoterra con disturbo 2', 'Disturbo', 'Gestire piccole variazioni di traiettoria prima della presa.', 'Il preparatore indirizza il pallone rasoterra vicino a un cono o mini-ostacolo che può produrre una lieve deviazione. Il portiere deve adattare rapidamente mani e piedi.', 10, 1, 3, 'Media', 2, '8 palloni, 4 coni bassi', 'Usare superfici/ostacoli diversi purché la deviazione resti controllata e sicura.', 'Attendere l''ultimo rimbalzo; mani morbide; corpo compatto.', 'Attaccare il punto previsto invece della palla; irrigidirsi sulle deviazioni.', null, null, true),
  ('GK-PRA-020', 'Rasoterra con pressione di un attaccante passivo', 1, 10, 'Tecnica presa alta e rasoterra', 'Presa rasoterra con disturbo 2', 'Disturbo', 'Proteggere la presa bassa in presenza di un avversario vicino.', 'Il preparatore serve rasoterra; un attaccante parte 2-3 m di lato e accompagna l''azione senza contrasto pieno. Il portiere raccoglie e protegge immediatamente il pallone.', 12, 2, 4, 'Media', 2, '8 palloni, 2 coni, casacca', 'L''attaccante aumenta progressivamente la pressione restando controllato.', 'Arrivare prima sulla linea; corpo tra avversario e palla; chiusura immediata.', 'Esporre la palla; arrivare in ginocchio senza protezione; frenare troppo presto.', null, null, true),
  ('GK-PRA-021', 'Rimbalzo dietro sagoma', 1, 11, 'Tecnica presa alta e rasoterra', 'Presa con rimbalzo con disturbo', 'Disturbo', 'Leggere un rimbalzo visto tardi.', 'Sagoma a 3 m dal portiere. Il preparatore serve un pallone che rimbalza dietro o lateralmente alla sagoma; il portiere deve riacquisire la traiettoria e bloccare.', 10, 1, 3, 'Media', 2, '8 palloni, 1 sagoma', 'Variare altezza del rimbalzo mantenendo controllo.', 'Restare centrati; occhi sulla palla appena visibile; assorbire la presa.', 'Cercare il pallone sporgendosi solo col busto; piedi fermi.', null, null, true),
  ('GK-PRA-022', 'Rimbalzo con compagno in attraversamento', 1, 11, 'Tecnica presa alta e rasoterra', 'Presa con rimbalzo con disturbo', 'Disturbo', 'Gestire occlusione dinamica e rimbalzo.', 'Un compagno attraversa la visuale mentre il preparatore calcia un pallone con un rimbalzo. Il portiere deve adattarsi senza anticipare.', 10, 2, 4, 'Media', 2, '8 palloni, 2 coni', 'Il compagno può cambiare direzione dopo un segnale.', 'Non perdere la postura; leggere dopo l''occlusione; mani all''altezza corretta.', 'Seguire il compagno anziché la palla; abbassarsi troppo presto.', null, null, true),
  ('GK-PRA-023', 'Doppio rimbalzo controllato', 1, 12, 'Tecnica presa alta e rasoterra', 'Presa con rimbalzo con disturbo 2', 'Disturbo', 'Migliorare adattamento a una traiettoria irregolare ma prevedibilmente sicura.', 'Il preparatore serve palloni che effettuano due rimbalzi prima di raggiungere il portiere. Il secondo rimbalzo è variato a destra/sinistra.', 10, 1, 4, 'Media', 2, '8 palloni', 'Ridurre progressivamente il tempo tra secondo rimbalzo e presa.', 'Leggere fino all''ultimo; passi corti; mani rilassate.', 'Decidere troppo presto; irrigidirsi; buttarsi quando è possibile restare in piedi.', null, null, true),
  ('GK-PRA-024', 'Rimbalzo con cambio posizione iniziale', 1, 12, 'Tecnica presa alta e rasoterra', 'Presa con rimbalzo con disturbo 2', 'Disturbo', 'Recuperare posizione prima di una presa su rimbalzo.', 'Il portiere parte leggermente fuori centro. Al segnale rientra sulla linea indicata e riceve un pallone con rimbalzo.', 10, 1, 4, 'Media', 2, '8 palloni, 3 coni', 'Cambiare ogni volta posizione iniziale e punto di rimbalzo.', 'Rientrare orientati verso palla; frenare prima della presa; stabilità.', 'Correre frontalmente senza orientamento; ricevere ancora in movimento.', null, null, true),
  ('GK-PRA-025', 'Cross morbido e uscita in presa', 1, 13, 'Tecnica presa alta e rasoterra', 'Presa alta situazionale', 'Situazionale', 'Trasferire la presa alta a una situazione di cross senza opposizione.', 'Preparatore laterale a 12-18 m. Il portiere parte in posizione gara e affronta cross morbidi nella zona 5-8 m, decidendo traiettoria e punto di presa.', 12, 1, 3, 'Media', 2, '8 palloni, porta', 'Alternare cross da destra e sinistra.', 'Posizione di partenza; lettura; chiamata; attacco del pallone.', 'Partire troppo presto; arretrare sotto il pallone; presa al petto anziché alta.', null, null, true),
  ('GK-PRA-026', 'Presa alta su palla arretrata e nuova traiettoria', 1, 13, 'Tecnica presa alta e rasoterra', 'Presa alta situazionale', 'Situazionale', 'Riposizionarsi prima di una palla alta successiva.', 'Il portiere riceve un passaggio di scarico, restituisce con i piedi e si riposiziona; subito dopo arriva un pallone alto/cross da un secondo servitore.', 12, 2, 4, 'Media', 2, '8 palloni, porta, 2 coni', 'Variare lato del secondo servizio.', 'Transizione rapida; scansione; recupero della posizione prima del cross.', 'Restare fuori posizione dopo il passaggio; guardare il pallone restituito troppo a lungo.', null, null, true),
  ('GK-PRA-027', 'Cross con attaccante passivo', 1, 14, 'Tecnica presa alta e rasoterra', 'Presa alta situazionale 2', 'Situazionale', 'Allenare decisione di uscita alta con presenza reale in area.', 'Un attaccante occupa la zona centrale senza contrastare pienamente. Il cross arriva da fascia; il portiere decide se uscire e bloccare o restare.', 14, 2, 4, 'Media', 3, '8 palloni, porta, casacca', 'Rendere l''attaccante progressivamente attivo sulla traiettoria.', 'Decisione precoce; comunicazione; protezione in volo.', 'Uscita indecisa; contatto non necessario; perdita della linea di porta.', null, null, true),
  ('GK-PRA-028', 'Cross variabile presa o rinuncia', 1, 14, 'Tecnica presa alta e rasoterra', 'Presa alta situazionale 2', 'Situazionale', 'Allenare la scelta, non solo l''esecuzione della presa.', 'Il servitore alterna cross attaccabili e cross troppo lontani. Il portiere deve decidere se intervenire in presa o mantenere posizione, verbalizzando la scelta.', 14, 1, 3, 'Media', 3, '10 palloni, porta', 'Aggiungere un attaccante per aumentare realismo.', 'Leggere velocità e altezza; scelta netta; recupero posizione dopo rinuncia.', 'Uscire su ogni pallone; esitazione; mancato recupero della porta.', null, null, true),
  ('GK-PRA-029', 'Tiro rasoterra dopo passaggio laterale', 1, 15, 'Tecnica presa alta e rasoterra', 'Presa rasoterra situazionale', 'Situazionale', 'Trasferire la raccolta bassa a una semplice sequenza di gioco.', 'Un giocatore passa lateralmente a un compagno che conclude rasoterra da 12-16 m. Il portiere si riposiziona seguendo la palla e raccoglie.', 12, 2, 4, 'Media', 2, '8 palloni, porta, 4 coni', 'Consentire al tiratore di scegliere primo o secondo palo.', 'Muoversi con la palla; set prima del tiro; corpo dietro.', 'Set tardivo; passi incrociati lunghi; anticipare il lato.', null, null, true),
  ('GK-PRA-030', 'Raccolta su cut-back controllato', 1, 15, 'Tecnica presa alta e rasoterra', 'Presa rasoterra situazionale', 'Situazionale', 'Allenare posizione e presa su palla bassa proveniente dal fondo.', 'Servitore vicino alla linea di fondo gioca un passaggio rasoterra arretrato. Un secondo giocatore lascia passare o conclude piano verso il portiere.', 12, 2, 4, 'Media', 2, '8 palloni, porta, 4 coni', 'Alternare palla lasciata e conclusione controllata.', 'Posizione rispetto a palla e porta; mani basse; decisione.', 'Restare sul primo palo; aprire troppo il corpo; mani alte.', null, null, true),
  ('GK-PRA-031', 'Conclusione bassa dopo sovrapposizione', 1, 16, 'Tecnica presa alta e rasoterra', 'Presa rasoterra situazionale 2', 'Situazionale', 'Leggere spostamento della palla e prepararsi al tiro rasoterra.', 'Due giocatori simulano una sovrapposizione laterale. Il portiere segue lo sviluppo e affronta una conclusione bassa dall''interno area.', 14, 2, 5, 'Media', 3, '8 palloni, porta, 6 coni', 'Inserire scelta passaggio/tiro per aumentare decision making.', 'Scansione; micro-aggiustamenti; set sul possibile tiro.', 'Fissarsi sul primo giocatore; arretrare troppo; posizione rigida.', null, null, true),
  ('GK-PRA-032', 'Tiro basso dopo finta di cross', 1, 16, 'Tecnica presa alta e rasoterra', 'Presa rasoterra situazionale 2', 'Situazionale', 'Gestire cambio rapido da possibile cross a tiro rasoterra.', 'Il servitore esterno simula il cross, conduce dentro e calcia basso. Il portiere adegua posizione senza anticipare.', 12, 2, 4, 'Media', 2, '8 palloni, porta, 3 coni', 'Il servitore può realmente crossare una volta ogni 3-4 azioni.', 'Non sbilanciarsi sulla finta; recuperare linea di tiro; set compatto.', 'Aprire il primo palo; anticipare il cross; piedi fermi.', null, null, true),
  ('GK-PRA-033', 'Tiro con rimbalzo dalla media distanza', 1, 17, 'Tecnica presa alta e rasoterra', 'Presa rimbalzo situazionale', 'Situazionale', 'Gestire conclusioni di gara con rimbalzo davanti al portiere.', 'Tiratore a 16-20 m cerca intenzionalmente un tiro che rimbalzi 3-6 m davanti al portiere. Obiettivo del portiere è bloccare quando possibile.', 12, 2, 4, 'Media', 2, '10 palloni, porta', 'Variare angolo e piede del tiratore.', 'Leggere punto di rimbalzo ma seguire la palla; stabilità; mani adattive.', 'Sedersi troppo presto; respingere palloni bloccabili; perdere allineamento.', null, null, true),
  ('GK-PRA-034', 'Rimbalzo dopo deviazione passiva', 1, 17, 'Tecnica presa alta e rasoterra', 'Presa rimbalzo situazionale', 'Situazionale', 'Reagire a una conclusione che cambia leggermente traiettoria.', 'Un giocatore/sagoma davanti al tiratore può deviare leggermente un tiro controllato. Il portiere gestisce rimbalzo o cambio di direzione.', 12, 2, 4, 'Media', 3, '10 palloni, porta, sagoma', 'Usare deviazioni volontarie leggere e sicure.', 'Restare vivi sui piedi; seconda lettura; evitare movimenti anticipati.', 'Caricare il tuffo prima della deviazione; irrigidirsi; perdere il pallone.', null, null, true),
  ('GK-PRA-035', 'Seconda palla dopo presa su rimbalzo', 1, 18, 'Tecnica presa alta e rasoterra', 'Presa rimbalzo situazionale 2', 'Situazionale', 'Collegare presa e rapida transizione successiva.', 'Il portiere affronta un tiro con rimbalzo, blocca e immediatamente distribuisce a un bersaglio laterale indicato dal preparatore.', 14, 1, 4, 'Media', 2, '8 palloni, porta, 2 porticine', 'Il bersaglio viene chiamato solo dopo la presa.', 'Prima sicurezza della presa; poi scansione e distribuzione rapida.', 'Pensare al rilancio prima di aver bloccato; alzarsi senza controllo.', null, null, true),
  ('GK-PRA-036', 'Rimbalzo da zona cieca laterale', 1, 18, 'Tecnica presa alta e rasoterra', 'Presa rimbalzo situazionale 2', 'Situazionale', 'Allenare riallineamento su tiro che arriva da angolo meno leggibile.', 'Il pallone viene giocato lateralmente fuori dal campo visivo centrale e poi concluso con rimbalzo. Il portiere ruota, si riallinea e gestisce la presa.', 14, 2, 4, 'Media', 3, '8 palloni, porta, 4 coni', 'Aggiungere una finta di passaggio prima del tiro.', 'Scansione; orientamento del corpo; set breve e stabile.', 'Ruotare solo il busto; piedi piantati; set troppo largo.', null, null, true)
on conflict (codice) do update set
  nome=excluded.nome,
  category_id=excluded.category_id,
  subcategory_id=excluded.subcategory_id,
  categoria=excluded.categoria,
  sottocategoria=excluded.sottocategoria,
  fase=excluded.fase,
  obiettivo=excluded.obiettivo,
  descrizione=excluded.descrizione,
  durata_min=excluded.durata_min,
  portieri_min=excluded.portieri_min,
  portieri_max=excluded.portieri_max,
  intensita=excluded.intensita,
  difficolta=excluded.difficolta,
  materiale=excluded.materiale,
  variante=excluded.variante,
  coaching_points=excluded.coaching_points,
  errori_comuni=excluded.errori_comuni,
  schema_url=excluded.schema_url,
  foto_url=excluded.foto_url,
  attivo=excluded.attivo;
