-- Sincronizzazione ufficiale GK-PRA-001 -> GK-PRA-036 da foglio "Sync App".
-- Aggiornamento conservativo: nessun INSERT in exercises e nessuna modifica a schema_url/foto_url.

alter table public.exercises add column if not exists schema_step_3 text;
alter table public.exercises add column if not exists schema_step_4 text;
alter table public.exercises add column if not exists schema_step_5 text;

insert into public.exercise_subcategories (id, category_id, nome, fase, attivo) values
  (145, 1, 'Deviazione con intervento attivo', 'Disturbo', true)
on conflict (category_id, nome, fase) do update
set attivo = excluded.attivo, updated_at = now();

-- Arresta la migration se manca anche uno solo dei 36 record o se esistono duplicati.
do $$
declare
  missing_codes text;
begin
  with expected(codice) as (values ('GK-PRA-001'), ('GK-PRA-002'), ('GK-PRA-003'), ('GK-PRA-004'), ('GK-PRA-005'), ('GK-PRA-006'), ('GK-PRA-007'), ('GK-PRA-008'), ('GK-PRA-009'), ('GK-PRA-010'), ('GK-PRA-011'), ('GK-PRA-012'), ('GK-PRA-013'), ('GK-PRA-014'), ('GK-PRA-015'), ('GK-PRA-016'), ('GK-PRA-017'), ('GK-PRA-018'), ('GK-PRA-019'), ('GK-PRA-020'), ('GK-PRA-021'), ('GK-PRA-022'), ('GK-PRA-023'), ('GK-PRA-024'), ('GK-PRA-025'), ('GK-PRA-026'), ('GK-PRA-027'), ('GK-PRA-028'), ('GK-PRA-029'), ('GK-PRA-030'), ('GK-PRA-031'), ('GK-PRA-032'), ('GK-PRA-033'), ('GK-PRA-034'), ('GK-PRA-035'), ('GK-PRA-036'))
  select string_agg(expected.codice, ', ' order by expected.codice)
    into missing_codes
  from expected
  left join public.exercises e on e.codice = expected.codice and e.category_id = 1
  where e.id is null;

  if missing_codes is not null then
    raise exception 'Sincronizzazione annullata. Codici mancanti o fuori categoria: %', missing_codes;
  end if;

  if exists (
    with expected(codice) as (values ('GK-PRA-001'), ('GK-PRA-002'), ('GK-PRA-003'), ('GK-PRA-004'), ('GK-PRA-005'), ('GK-PRA-006'), ('GK-PRA-007'), ('GK-PRA-008'), ('GK-PRA-009'), ('GK-PRA-010'), ('GK-PRA-011'), ('GK-PRA-012'), ('GK-PRA-013'), ('GK-PRA-014'), ('GK-PRA-015'), ('GK-PRA-016'), ('GK-PRA-017'), ('GK-PRA-018'), ('GK-PRA-019'), ('GK-PRA-020'), ('GK-PRA-021'), ('GK-PRA-022'), ('GK-PRA-023'), ('GK-PRA-024'), ('GK-PRA-025'), ('GK-PRA-026'), ('GK-PRA-027'), ('GK-PRA-028'), ('GK-PRA-029'), ('GK-PRA-030'), ('GK-PRA-031'), ('GK-PRA-032'), ('GK-PRA-033'), ('GK-PRA-034'), ('GK-PRA-035'), ('GK-PRA-036'))
    select e.codice
    from public.exercises e join expected on expected.codice = e.codice
    group by e.codice having count(*) <> 1
  ) then
    raise exception 'Sincronizzazione annullata: rilevati codici duplicati.';
  end if;
end $$;

with official (
  codice, nome, sottocategoria, fase, durata_min, portieri_min, portieri_max, intensita, difficolta, materiale, obiettivo, variante, coaching_points, errori_comuni, schema_step_1, schema_step_2, schema_step_3, schema_step_4, schema_step_5
) as (values
  ('GK-PRA-001', 'Presa alta frontale in posizione', 'Presa alta analitica', 'Analitico', 8, 1, 4, 'Bassa', 1, 'Palloni, coni', 'Migliorare tecnica di presa alta, lettura della traiettoria, posizionamento e sicurezza nella presa.', 'Variare lato, altezza e velocità del lancio mantenendo la corretta posizione di attesa.', 'Occhi sempre sulla palla; mani a coppa sopra la testa; pollici vicini; gomiti leggermente flessi; atterraggio in equilibrio.', 'Guardare il pallone tardi; mani non a coppa; gomiti larghi; presa instabile.', 'Lancio alto frontale del pallone da parte del preparatore.', 'Presa alta sopra la testa con entrambe le mani.', null, null, null),
  ('GK-PRA-002', 'Presa alta con elevazione', 'Presa alta analitica', 'Analitico', 10, 1, 4, 'Media', 2, 'Palloni, coni', 'Migliorare elevazione, coordinazione e tecnica di presa alta nel punto più alto.', 'Variare altezza del lancio e gamba di stacco.', 'Attaccare il pallone; spinta decisa; braccia tese verso l''alto; presa sopra la testa; atterraggio equilibrato.', 'Stacco tardivo; presa troppo bassa; braccia piegate; atterraggio rigido.', 'Lancio alto frontale del pallone da parte del preparatore.', 'Elevazione e presa alta sopra la testa.', null, null, null),
  ('GK-PRA-003', 'Presa alta con passaggio dell''allenatore', 'Presa alta con intervento attivo', 'Analitico', 10, 1, 4, 'Media', 2, 'Palloni, coni', 'Migliorare lettura della traiettoria e presa alta su servizio arcuato dell''allenatore.', 'Variare direzione, altezza e punto di partenza del servizio.', 'Posizione pronta; leggere subito il lancio; muovere i piedi prima della presa; mani sicure sul pallone.', 'Piedi fermi; lettura tardiva; presa davanti al viso; perdita di equilibrio.', 'Passaggio/lancio dell''allenatore verso il portiere.', 'Presa alta del portiere sulla traiettoria del pallone.', null, null, null),
  ('GK-PRA-004', 'Presa alta in salto frontale', 'Presa alta analitica', 'Analitico', 10, 1, 2, 'Media', 2, 'Palloni, coni', 'Migliorare coordinazione e tecnica di presa alta in salto frontale.', 'Variare altezza e velocità del lancio; inserire un passo indietro prima del salto.', 'Occhi sul pallone; spinta decisa con le gambe; braccia distese; presa sopra la testa.', 'Guardare il pallone tardi; saltare con poca spinta; bloccare il pallone davanti al viso o al petto.', 'Lancio frontale del pallone da parte del preparatore.', 'Salto verso l''alto e presa alta del pallone sopra la testa.', null, null, null),
  ('GK-PRA-005', 'Presa alta in tuffo laterale da lancio del preparatore', 'Presa alta con intervento attivo', 'Analitico', 10, 1, 2, 'Alta', 3, 'Palloni, coni', 'Migliorare coordinazione nel tuffo laterale e presa alta in sospensione.', 'Variare distanza e direzione del lancio; inserire un leggero rimbalzo prima del tuffo.', 'Spinta decisa con la gamba opposta; braccia tese; presa sopra la testa; pollici vicini; occhi sulla palla.', 'Spingere con la gamba sbagliata; estensione incompleta; mani morbide o presa davanti al viso.', 'Lancio del pallone dal preparatore lateralmente.', 'Tuffo laterale e presa alta con entrambe le mani.', null, null, null),
  ('GK-PRA-006', 'Presa alta in tuffo frontale', 'Presa alta con intervento attivo', 'Analitico', 8, 1, 2, 'Alta', 3, 'Palloni, coni', 'Migliorare reattività, tecnica di presa alta e spinta in elevazione.', 'Variare distanza, potenza e direzione del lancio; alternare lanci tesi e lob.', 'Spinta esplosiva; braccia tese; occhi sul pallone; afferrare sopra la testa; atterrare in equilibrio.', 'Spinta insufficiente; lettura tardiva; braccia piegate; atterraggio sbilanciato.', 'Lancio frontale del pallone da parte del partner.', 'Tuffo frontale e presa alta del pallone con entrambe le mani.', null, null, null),
  ('GK-PRA-007', 'Presa alta su palla arretrata', 'Presa alta con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, coni', 'Migliorare tempo di reazione, coordinazione e presa alta su lanci arretrati.', 'Variare traiettoria e altezza; alternare lanci tesi e lob.', 'Spinta decisa; braccia tese; presa sopra la testa; pollici vicini; occhi sempre sul pallone.', 'Partire in ritardo; spinta debole; braccia piegate; estensione incompleta.', 'Lancio della palla dal preparatore su traiettoria arretrata.', 'Spinta, salto e presa alta della palla sopra la testa.', null, null, null),
  ('GK-PRA-008', 'Presa alta in uscita', 'Presa alta con intervento attivo', 'Disturbo', 8, 1, 1, 'Alta', 3, 'Palloni, coni', 'Migliorare la tempistica dell''uscita alta e la presa sicura del pallone in elevazione.', 'Variare profondità e traiettoria del lancio; inserire rimbalzi prima della presa.', 'Uscita decisa e veloce; braccia tese; presa sopra la testa; ginocchio in spinta; atterraggio equilibrato.', 'Uscire in ritardo; braccia piegate; occhi non fissi sul pallone; piedi disallineati in atterraggio.', 'Lancio alto e profondo del partner verso l''area.', 'Uscita in elevazione e presa alta del pallone con entrambe le mani.', null, null, null),
  ('GK-PRA-009', 'Presa alta in uscita con ostacolo', 'Presa alta con intervento attivo', 'Disturbo', 10, 1, 1, 'Alta', 3, 'Palloni, coni, paletti o ostacoli', 'Migliorare l''uscita in elevazione superando un ostacolo e la presa alta del pallone.', 'Variare altezza e distanza del lancio; inserire più ostacoli; lancio da posizione laterale.', 'Spinta decisa; braccia tese; presa sopra la testa; ginocchio in spinta; atterraggio equilibrato.', 'Uscire in ritardo; non superare l''ostacolo; braccia piegate; elevazione insufficiente; atterraggio sbilanciato.', 'Lancio alto del pallone da parte del partner oltre l''ostacolo.', 'Uscita in elevazione superando l''ostacolo e presa alta con entrambe le mani.', null, null, null),
  ('GK-PRA-010', 'Presa alta in tuffo laterale', 'Presa alta con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, coni', 'Migliorare copertura laterale in elevazione e presa alta del pallone in tuffo.', 'Variare altezza e direzione del lancio; alternare destra e sinistra.', 'Spinta esplosiva della gamba opposta; braccia tese; presa sopra la testa; atterraggio su spalla e fianco; occhi sul pallone.', 'Partire in ritardo; non coprire la distanza; piegare le braccia; guardare via dal pallone; atterrare con braccia tese.', 'Lancio alto e laterale del pallone da parte del partner.', 'Tuffo laterale con presa alta del pallone con entrambe le mani.', null, null, null),
  ('GK-PRA-011', 'Presa alta in tuffo diagonale', 'Presa alta con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, coni', 'Migliorare l''intervento in elevazione con tuffo diagonale e presa alta in situazioni dinamiche.', 'Variare direzione e altezza del lancio; alternare lanci tesi e lob.', 'Spinta esplosiva della gamba opposta; braccia tese; corpo allungato sulla traiettoria; presa alta; atterraggio su spalla e fianco.', 'Partire tardi; non coprire la diagonale; piegare le braccia; perdere il pallone; atterrare su mani o gomito.', 'Lancio alto e diagonale del pallone da parte del partner.', 'Tuffo diagonale, estensione completa e presa alta con entrambe le mani.', null, null, null),
  ('GK-PRA-012', 'Presa alta in tuffo in avanti', 'Presa alta con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo', 'Migliorare l''intervento in avanti in elevazione e la presa alta del pallone lontano dal corpo.', 'Variare distanza e altezza; inserire ostacolo basso da superare.', 'Spinta esplosiva; braccia tese; presa sopra la testa; corpo in estensione completa; atterraggio su petto e spalle.', 'Uscire in ritardo; non estendersi; piegare le braccia; portare il pallone verso il corpo; atterrare su gomiti o mani.', 'Lancio alto del pallone da parte del partner.', 'Tuffo in avanti e presa alta del pallone con entrambe le mani.', null, null, null),
  ('GK-PRA-013', 'Presa alta in tuffo indietro', 'Presa alta con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo', 'Migliorare la presa alta in tuffo indietro gestendo coordinazione ed estensione del corpo.', 'Variare distanza e altezza; inserire ostacolo basso da superare.', 'Spinta esplosiva della gamba opposta; braccia tese; presa sopra la testa; arco del corpo; atterraggio su schiena e spalle.', 'Uscire in ritardo; estensione incompleta; braccia piegate; perdere il pallone dietro la testa; atterrare su gomiti o mani.', 'Lancio alto del pallone da parte del partner.', 'Tuffo indietro e presa alta del pallone con entrambe le mani.', null, null, null),
  ('GK-PRA-014', 'Presa alta in tuffo a gomito', 'Presa alta con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo', 'Migliorare la tecnica di presa alta in tuffo con corretta chiusura a gomito, aumentando sicurezza e stabilità.', 'Variare direzione del lancio; aggiungere ostacolo basso; aumentare leggermente la velocità.', 'Spinta esplosiva; braccia tese; chiusura a gomito per bloccare; presa sopra la testa; corpo allungato; atterraggio su fianco o spalla.', 'Uscire in ritardo; non chiudere a gomito; piegare le braccia; lasciare spazio tra mani e pallone; atterrare su mani o gomiti.', 'Lancio alto del pallone da parte del partner.', 'Tuffo a gomito e presa alta del pallone con entrambe le mani.', null, null, null),
  ('GK-PRA-015', 'Presa alta in tuffo a destra', 'Presa alta con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo', 'Migliorare l''intervento in elevazione verso destra con presa alta, coordinazione, estensione e sicurezza.', 'Variare distanza e altezza; inserire ostacolo basso; aumentare leggermente la velocità.', 'Spinta esplosiva della gamba opposta; braccia tese; presa sopra la testa; corpo allungato; atterraggio su fianco o spalla destra.', 'Uscire in ritardo; non spingere lateralmente; piegare le braccia; occhi non fissi; atterrare su mani o gomito.', 'Lancio alto del pallone da parte del partner.', 'Tuffo a destra e presa alta del pallone con entrambe le mani.', null, null, null),
  ('GK-PRA-016', 'Presa alta in tuffo basso', 'Presa alta con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo', 'Allenare la presa alta del pallone in tuffo verso il basso, migliorando reattività, coordinazione e sicurezza.', 'Variare distanza e altezza; inserire ostacolo basso; aumentare leggermente la velocità.', 'Spinta esplosiva della gamba opposta; braccia tese; presa sopra la testa; corpo allungato verso il pallone; atterraggio su fianco o spalla.', 'Uscire in ritardo; piegare le braccia; occhi non fissi; atterrare su mani o gomito.', 'Lancio alto del pallone da parte del partner.', 'Tuffo basso e presa alta del pallone con entrambe le mani.', null, null, null),
  ('GK-PRA-017', 'Presa alta in tuffo frontale', 'Presa alta con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare la presa alta del pallone in tuffo frontale, curando reattività, coordinazione e sicurezza nell''intervento.', 'Variare l''altezza e la distanza del lancio. Inserire ostacolo basso da superare prima dell''intervento.', 'Spinta esplosiva in avanti; braccia tese verso il pallone; presa sopra la testa, pollici vicini; corpo allungato in estensione completa; atterraggio su petto e spalle.', 'Uscire in ritardo; non estendersi completamente; piegare le braccia in presa; perdere il pallone sopra la testa; atterrare su mani o gomiti.', 'Lancio alto del pallone da parte del partner.', 'Tuffo frontale, presa alta del pallone con entrambe le mani.', null, null, null),
  ('GK-PRA-018', 'Presa bassa in tuffo frontale', 'Presa bassa con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare la tecnica di presa bassa in tuffo frontale, aumentando reattività, coordinazione e sicurezza nell''intervento.', 'Variare la distanza e la velocità del passaggio. Inserire ostacolo basso da superare prima dell''intervento.', 'Partenza in posizione pronta; spinta esplosiva in avanti; mani aperte e dita rivolte verso il pallone; presa sicura con entrambe le mani; corpo dietro il pallone; atterraggio su petto e spalle.', 'Uscire in ritardo; piegare le braccia; occhi non fissi sul pallone; mani ravvicinate o rigide; atterrare su gomiti o mani.', 'Passaggio rasoterra da parte del partner.', 'Tuffo frontale basso, presa del pallone con entrambe le mani.', null, null, null),
  ('GK-PRA-019', 'Deviazione in tuffo frontale', 'Deviazione con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare la capacità di deviare il pallone in tuffo frontale, aumentando reattività, coordinazione e protezione della porta.', 'Variare la traiettoria del passaggio (centrale, destra, sinistra). Cambiare la velocità del lancio. Inserire un ostacolo davanti al portiere.', 'Partenza in posizione pronta; spinta esplosiva verso il pallone; mani aperte; deviazione con entrambe le mani; occhi sempre sul pallone; corpo allungato a copertura della porta; atterraggio su spalla e fianchi.', 'Uscire in ritardo; mani rigide o non aperte; occhi non fissati sul pallone; deviare centralmente; atterrare su gomiti o mani tese.', 'Il partner effettua un passaggio rasoterra verso il centro o leggermente decentrato rispetto alla posizione del portiere.', 'Il portiere si tuffa frontalmente e devia il pallone con entrambe le mani, allontanandolo dalla porta.', null, null, null),
  ('GK-PRA-020', 'Presa bassa in tuffo laterale', 'Presa bassa con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare la presa bassa in tuffo laterale, la reattività, la coordinazione e la sicurezza nell’intervento, andando vicino al terreno.', 'Lanciare da destra e sinistra. Variare distanza e velocità. Inserire ostacolo basso da superare prima dell’intervento. Passaggio leggermente più lontano dal portiere.', 'Partenza in posizione pronta; spinta esplosiva laterale; corpo allungato e copertura della palla; mani aperte; presa sicura vicino al terreno; atterraggio su fianco e spalla.', 'Uscire in ritardo; piegare il braccio di presa; occhi non fissi; non andare vicino al terreno; atterrare su gomiti o mani tese.', 'Il partner effettua un passaggio rasoterra verso uno dei lati della porta.', 'Il portiere si sposta lateralmente e si tuffa basso, bloccando il pallone con entrambe le mani vicino al terreno.', null, null, null),
  ('GK-PRA-021', 'Tuffo basso laterale in appoggio', 'Presa bassa con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare la tecnica del tuffo basso laterale in appoggio, aumentando reattività, capacità di copertura del lato e sicurezza nella presa a terra.', 'Variare il lato del passaggio, la distanza dal portiere e inserire un ostacolo basso da superare prima dell’intervento.', 'Partenza pronta; spinta esplosiva verso il lato; mani aperte; presa bassa sicura; appoggio su fianco e avambraccio; corpo dietro il pallone; atterraggio controllato e protezione della palla.', 'Uscire in ritardo; mani rigide; occhi non fissi; non portare il corpo dietro il pallone; atterrare su gomito o spalla; lasciare rimbalzare il pallone.', 'Il partner effettua un passaggio rasoterra verso destra o sinistra del portiere.', 'Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', null, null, null),
  ('GK-PRA-022', 'Tuffo basso laterale in spinta', 'Presa bassa con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare la tecnica del tuffo basso laterale in spinta, aumentando reattività, rapidità d’intervento e sicurezza nella presa a terra.', 'Variare lato, distanza e velocità del passaggio. Inserire un ostacolo basso da superare prima dell’intervento.', 'Partenza pronta; spinta esplosiva verso il lato; mani aperte; presa bassa sicura; spinta laterale con gamba interna; corpo dietro il pallone; atterraggio su fianco e spalla.', 'Uscire in ritardo; mani rigide; occhi non fissi; non spingere lateralmente; atterrare su gomito o mani tese; lasciare rimbalzare il pallone.', 'Il partner effettua un passaggio rasoterra forte verso il lato del portiere.', 'Il portiere effettua un tuffo basso laterale in spinta, afferra il pallone con entrambe le mani e lo protegge.', null, null, null),
  ('GK-PRA-023', 'Tuffo basso laterale in appoggio con ripartenza', 'Presa bassa con intervento attivo', 'Disturbo', 10, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare tuffo basso laterale in appoggio, presa sicura e rapidità di ripartenza verso la posizione di guardia.', 'Variare lato e distanza del passaggio. Inserire ostacolo basso. Aggiungere uno stimolo visivo o sonoro prima del passaggio.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; appoggio su fianco e avambraccio; corpo dietro la palla; occhi sul pallone; ripartenza immediata verso la guardia.', 'Uscire in ritardo; mani rigide; occhi non fissi; non proteggere il pallone; non ripartire rapidamente; atterrare su gomito o spalla; lasciare rimbalzare il pallone.', 'Il partner effettua un passaggio rasoterra verso il lato del portiere.', 'Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere si rialza rapidamente e ritorna in posizione di guardia.', null, null),
  ('GK-PRA-024', 'Tuffo basso laterale in appoggio con ripartenza', 'Presa bassa con intervento attivo', 'Disturbo', 10, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare la tecnica del tuffo basso laterale in appoggio, la presa sicura del pallone e la rapidità di ripartenza verso la posizione di guardia.', 'Variare lato e distanza del passaggio. Inserire ostacolo basso. Aggiungere uno stimolo visivo o sonoro prima del passaggio.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; appoggio su fianco e avambraccio; corpo dietro la palla; occhi sul pallone; ripartenza immediata con ritorno in guardia.', 'Uscire in ritardo; mani rigide; occhi non fissi; non proteggere il pallone; ripartenza lenta; atterrare su gomito o spalla; lasciare rimbalzare il pallone.', 'Il partner effettua un passaggio rasoterra verso il lato del portiere.', 'Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere si rialza rapidamente e ritorna in posizione di guardia.', null, null),
  ('GK-PRA-025', 'Tuffo basso laterale in appoggio con passaggio di ritorno', 'Presa bassa con intervento attivo', 'Disturbo', 10, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare tuffo basso laterale in appoggio, presa sicura, rapidità d’intervento e accuratezza nel passaggio di ritorno.', 'Variare lato e distanza del passaggio. Inserire ostacolo basso prima dell’intervento.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; appoggio su fianco e avambraccio; corpo dietro la palla; occhi sul pallone; passaggio di ritorno rasoterra preciso e forte.', 'Uscire in ritardo; mani rigide; occhi non fissi; non proteggere il pallone; non ripartire rapidamente; passaggio di ritorno impreciso o lento; lasciare rimbalzare il pallone.', 'Il partner effettua un passaggio rasoterra verso il lato del portiere.', 'Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere esegue un passaggio di ritorno rasoterra preciso verso il partner.', null, null),
  ('GK-PRA-026', 'Tuffo basso frontale in appoggio', 'Presa bassa con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare la tecnica del tuffo basso frontale in appoggio, curando presa sicura e rapidità d’intervento dal centro della porta.', 'Variare distanza del passaggio. Inserire ostacolo basso da superare. Alternare passaggi veloci e lenti.', 'Partenza pronta; spinta esplosiva in avanti; mani aperte; occhi sul pallone; corpo dietro la palla; presa sicura; appoggio su avambracci e pettorali; protezione al petto; ripartenza immediata.', 'Uscire in ritardo; mani rigide; occhi non fissi; non portare il corpo dietro il pallone; atterrare su gomito o spalla; non proteggere il pallone; ripartenza lenta.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere si rialza rapidamente e ritorna in posizione di guardia.', null, null),
  ('GK-PRA-027', 'Tuffo basso frontale con ripartenza', 'Presa bassa con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare tuffo basso frontale in presa, sicurezza del pallone e rapidità di ripartenza verso la posizione di guardia.', 'Variare velocità e direzione del passaggio. Inserire ostacolo basso. Alternare rasoterra e palloni leggermente rimbalzati.', 'Partenza pronta; spinta esplosiva in avanti; mani aperte; tuffo frontale con corpo dietro il pallone; presa sicura; protezione al petto; occhi sul pallone; ripartenza immediata e comunicazione.', 'Uscire in ritardo; mani rigide; occhi non fissi; corpo non dietro la palla; non proteggere; restare a terra troppo; ripartenza lenta o con passi incrociati.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere si rialza rapidamente e ritorna in posizione di guardia.', null, null),
  ('GK-PRA-028', 'Tuffo basso frontale con passaggio di ritorno', 'Presa bassa con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare tuffo basso frontale in presa, sicurezza del pallone e rapidità d’intervento, con successivo passaggio di ritorno preciso e rasoterra.', 'Variare distanza del partner; inserire ostacolo basso; alternare rasoterra centrali e decentrati; aumentare velocità.', 'Partenza pronta; spinta esplosiva; mani aperte; corpo dietro la palla; presa sicura; protezione al petto; passaggio di ritorno preciso e forte; occhi sul pallone e comunicazione.', 'Uscire in ritardo; mani rigide; occhi non fissi; corpo non dietro la palla; atterrare male; non proteggere; passaggio di ritorno lento o impreciso.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere effettua un passaggio di ritorno rasoterra verso il partner.', null, null),
  ('GK-PRA-029', 'Tuffo basso frontale con ritorno in porta', 'Presa bassa con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare tuffo basso frontale in presa, sicurezza del pallone e rapidità di recupero con ritorno in porta per mantenere la posizione di guardia.', 'Variare distanza; inserire uno o due ostacoli bassi; alternare rasoterra centrali e decentrati; aumentare velocità del passaggio in entrata e ritorno.', 'Partenza pronta; spinta esplosiva; mani aperte; corpo dietro la palla; presa sicura; protezione al petto; ritorno rapido in piedi; comunicazione.', 'Uscire in ritardo; mani rigide; occhi non fissi; corpo non dietro la palla; non proteggere; restare a terra troppo; rientro lento; passaggio impreciso.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere effettua un passaggio di ritorno rasoterra verso il partner.', 'Il portiere si rialza rapidamente e rientra in posizione di guardia.', null),
  ('GK-PRA-030', 'Tuffo basso frontale con ritorno e ripartenza laterale', 'Presa bassa con intervento attivo', 'Disturbo', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare tuffo basso frontale in presa, sicurezza, rapidità di ritorno e capacità di ripartenza laterale per mantenere la posizione di guardia.', 'Variare distanza; inserire ostacoli bassi; alternare rasoterra centrali e decentrati; eseguire la ripartenza a destra e sinistra.', 'Partenza pronta; spinta esplosiva; mani aperte; corpo dietro la palla; presa sicura; protezione; ritorno rapido in piedi; ripartenza laterale bassa e veloce; occhi sul pallone.', 'Uscire in ritardo; mani rigide; occhi non fissi; corpo non dietro la palla; non proteggere; restare a terra; ripartenza lenta o incrociata; rientrare troppo alti.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere ritorna rapidamente in piedi.', 'Il portiere riparte lateralmente e rientra in posizione di guardia.', null),
  ('GK-PRA-031', 'Tuffo basso frontale con ritorno, ripartenza e reazione', 'Presa bassa con intervento attivo', 'Disturbo', 10, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Migliorare tuffo basso frontale in presa, velocità di ritorno in guardia e capacità di reagire a un nuovo stimolo mantenendo qualità tecnica.', 'Variare distanza e velocità; inserire ostacoli; alternare passaggi centrali e laterali; dopo il ritorno chiedere spostamento laterale prima del nuovo stimolo.', 'Partenza pronta e reattiva; spinta esplosiva; mani aperte; presa sicura; protezione al petto; ritorno rapido; ripartenza equilibrata; piedi bassi; comunicazione costante.', 'Uscire in ritardo; mani rigide; occhi non fissi; corpo non dietro; non portare palla al petto; ritorno lento; equilibrio precario; posizione di guardia troppo alta.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il partner invia un nuovo passaggio o stimolo e il portiere reagisce con un nuovo intervento.', null),
  ('GK-PRA-032', 'Tuffo basso frontale con ritorno e reazione a stimolo visivo', 'Presa bassa con intervento attivo', 'Disturbo', 10, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, manichino, cartoncini colorati o numeri', 'Migliorare tuffo basso frontale in presa, rapidità di ritorno in guardia e capacità di reagire rapidamente a uno stimolo visivo con un nuovo intervento preciso.', 'Variare distanza e velocità; inserire ostacoli; alternare passaggi centrali e laterali; utilizzare colori, numeri, forme o combinazioni; alternare stimolo visivo e sonoro.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; protezione; ritorno rapido; occhi attivi sullo stimolo; reazione immediata e comunicazione.', 'Uscire in ritardo; mani rigide; occhi non su palla/stimolo; corpo non dietro; non proteggere; ritorno lento; reazione ritardata; equilibrio precario.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il partner mostra uno stimolo visivo e invia un nuovo passaggio: il portiere reagisce.', null),
  ('GK-PRA-033', 'Tuffo basso frontale con ritorno, ripartenza, reazione e secondo stimolo', 'Presa bassa con intervento attivo', 'Disturbo', 12, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, manichino, cartoncini colorati o numeri', 'Migliorare tuffo basso frontale in presa, ritorno in guardia e capacità di reagire rapidamente a un secondo stimolo visivo e a un nuovo intervento.', 'Variare distanza e velocità; inserire ostacoli; alternare passaggi centrali e laterali; utilizzare colori, numeri, forme o combinazioni; alternare stimolo sonoro.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; protezione; ritorno rapido; occhi sempre attivi; reazione immediata; comunicazione.', 'Uscire in ritardo; mani rigide; occhi non su palla/stimolo; corpo non dietro; non proteggere; ritorno lento; reazione ritardata; equilibrio precario.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il partner effettua un secondo passaggio rasoterra: il portiere reagisce e prende il pallone.', 'Il partner mostra un secondo stimolo visivo e il portiere reagisce effettuando un nuovo passaggio/intervento.'),
  ('GK-PRA-034', 'Tuffo basso frontale con ritorno, ripartenza e stimolo sonoro', 'Presa bassa con intervento attivo', 'Disturbo', 12, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, manichino, speaker portatile per stimolo sonoro', 'Migliorare tuffo basso frontale in presa, velocità di ritorno in guardia e capacità di reagire rapidamente a uno stimolo sonoro e a un nuovo intervento.', 'Variare distanza e velocità; inserire ostacoli; alternare passaggi; utilizzare fischio, clap, bip o musica; alternare stimolo sonoro e visivo.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; protezione; ritorno rapido; mantenere sguardo avanti e ascolto attivo; reazione immediata; comunicazione.', 'Uscire in ritardo; mani rigide; occhi non sul pallone; corpo non dietro; non proteggere; ritorno lento; reazione ritardata allo stimolo; equilibrio precario.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il portiere attende in guardia lo stimolo sonoro.', 'Alla ricezione dello stimolo sonoro, il partner effettua un secondo passaggio e il portiere reagisce con un nuovo intervento.'),
  ('GK-PRA-035', 'Tuffo basso frontale con ritorno, ripartenza e giocata finale', 'Presa bassa con intervento attivo', 'Disturbo', 14, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, mini porta, sagoma', 'Migliorare tuffo basso frontale in presa, rapidità di ritorno in guardia, capacità di ripartenza e reattività su una seconda giocata.', 'Variare distanza e velocità; inserire ostacoli; alternare passaggio rasoterra e tiro; inserire finta del partner prima della seconda giocata.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; protezione; ritorno rapido; ripartenza bassa ed equilibrata; lettura della giocata finale; comunicazione.', 'Uscire in ritardo; mani rigide; occhi non sul pallone; corpo non dietro; non proteggere; ritorno lento; ripartenza laterale lunga; reazione tardiva sulla giocata finale.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il portiere si riposiziona lateralmente per la seconda giocata.', 'Il partner effettua una seconda giocata e il portiere interviene.'),
  ('GK-PRA-036', 'Tuffo basso frontale con ritorno, ripartenza e stimolo visivo + sonoro', 'Presa bassa con intervento attivo', 'Disturbo', 14, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, manichino, cartoncini colorati o numeri, speaker o fischietto', 'Migliorare tuffo basso frontale in presa, reattività a stimoli visivi e sonori, rapidità di ritorno in guardia e reattività sui passaggi successivi.', 'Variare distanza e velocità; inserire ostacoli; alternare passaggio rasoterra e tiro; utilizzare colori, numeri, fischi, bip o musica; alternare ordine degli stimoli.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; protezione; ritorno rapido; occhi sempre attivi; reazione entro circa un secondo; comunicazione costante.', 'Uscire in ritardo; mani rigide; occhi non su palla/stimolo; corpo non dietro; non proteggere; ritorno lento; reazione ritardata; equilibrio precario.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il portiere reagisce allo stimolo visivo e a quello sonoro.', 'Il partner effettua un nuovo passaggio rasoterra e il portiere reagisce con un nuovo intervento.')
)
update public.exercises e
set
  nome = o.nome,
  sottocategoria = o.sottocategoria,
  fase = o.fase,
  durata_min = o.durata_min,
  portieri_min = o.portieri_min,
  portieri_max = o.portieri_max,
  intensita = o.intensita,
  difficolta = o.difficolta,
  materiale = o.materiale,
  obiettivo = o.obiettivo,
  variante = o.variante,
  coaching_points = o.coaching_points,
  errori_comuni = o.errori_comuni,
  schema_step_1 = o.schema_step_1,
  schema_step_2 = o.schema_step_2,
  schema_step_3 = o.schema_step_3,
  schema_step_4 = o.schema_step_4,
  schema_step_5 = o.schema_step_5,
  subcategory_id = s.id
from official o
join public.exercise_subcategories s
  on s.category_id = 1
 and s.nome = o.sottocategoria
 and s.fase = o.fase
where e.codice = o.codice
  and e.category_id = 1;


