-- Sincronizzazione ufficiale GK-PRA-001 -> GK-PRA-040.
-- UPSERT per codice: aggiunge 037-040, aggiorna gli esistenti e preserva schema_url/foto_url.

begin;

alter table public.exercises add column if not exists schema_step_6 text;

alter table public.exercises drop constraint if exists exercises_difficolta_check;
alter table public.exercises
  add constraint exercises_difficolta_check check (difficolta in (1, 2, 3, 4));

do $$
begin
  if exists (
    values
      ('Presa alta', 'Analitico'),
      ('Presa alta', 'Disturbo'),
      ('Presa rasoterra', 'Disturbo'),
      ('Deviazione', 'Disturbo')
    except
    select nome, fase
    from public.exercise_subcategories
    where category_id = 1
  ) then
    raise exception 'Sincronizzazione annullata: eseguire prima 0008_clean_exercise_subcategories.sql.';
  end if;
end $$;

with official (codice, nome, categoria, sottocategoria, fase, obiettivo, descrizione, durata_min, portieri_min, portieri_max, intensita, difficolta, materiale, variante, coaching_points, errori_comuni, attivo, schema_step_1, schema_step_2, schema_step_3, schema_step_4, schema_step_5, schema_step_6) as (values
  ('GK-PRA-001', 'Presa alta frontale in posizione', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Analitico', 'Migliorare tecnica di presa alta, lettura della traiettoria, posizionamento e sicurezza nella presa.', 'Lancio alto frontale del pallone da parte del preparatore. Presa alta sopra la testa con entrambe le mani.', 8, 1, 4, 'Bassa', 1, 'Palloni, coni', 'Variare lato, altezza e velocità del lancio mantenendo la corretta posizione di attesa.', 'Occhi sempre sulla palla; mani a coppa sopra la testa; pollici vicini; gomiti leggermente flessi; atterraggio in equilibrio.', 'Guardare il pallone tardi; mani non a coppa; gomiti larghi; presa instabile.', true, 'Lancio alto frontale del pallone da parte del preparatore.', 'Presa alta sopra la testa con entrambe le mani.', null, null, null, null),
  ('GK-PRA-002', 'Presa alta con elevazione', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Analitico', 'Migliorare elevazione, coordinazione e tecnica di presa alta nel punto più alto.', 'Lancio alto frontale del pallone da parte del preparatore. Elevazione e presa alta sopra la testa.', 10, 1, 4, 'Media', 2, 'Palloni, coni', 'Variare altezza del lancio e gamba di stacco.', 'Attaccare il pallone; spinta decisa; braccia tese verso l''alto; presa sopra la testa; atterraggio equilibrato.', 'Stacco tardivo; presa troppo bassa; braccia piegate; atterraggio rigido.', true, 'Lancio alto frontale del pallone da parte del preparatore.', 'Elevazione e presa alta sopra la testa.', null, null, null, null),
  ('GK-PRA-003', 'Presa alta con passaggio dell''allenatore', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Analitico', 'Migliorare lettura della traiettoria e presa alta su servizio arcuato dell''allenatore.', 'Passaggio/lancio dell''allenatore verso il portiere. Presa alta del portiere sulla traiettoria del pallone.', 10, 1, 4, 'Media', 2, 'Palloni, coni', 'Variare direzione, altezza e punto di partenza del servizio.', 'Posizione pronta; leggere subito il lancio; muovere i piedi prima della presa; mani sicure sul pallone.', 'Piedi fermi; lettura tardiva; presa davanti al viso; perdita di equilibrio.', true, 'Passaggio/lancio dell''allenatore verso il portiere.', 'Presa alta del portiere sulla traiettoria del pallone.', null, null, null, null),
  ('GK-PRA-004', 'Presa alta in salto frontale', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Analitico', 'Migliorare coordinazione e tecnica di presa alta in salto frontale.', 'Lancio frontale del pallone da parte del preparatore. Salto verso l''alto e presa alta del pallone sopra la testa.', 10, 1, 2, 'Media', 2, 'Palloni, coni', 'Variare altezza e velocità del lancio; inserire un passo indietro prima del salto.', 'Occhi sul pallone; spinta decisa con le gambe; braccia distese; presa sopra la testa.', 'Guardare il pallone tardi; saltare con poca spinta; bloccare il pallone davanti al viso o al petto.', true, 'Lancio frontale del pallone da parte del preparatore.', 'Salto verso l''alto e presa alta del pallone sopra la testa.', null, null, null, null),
  ('GK-PRA-005', 'Presa alta in tuffo laterale da lancio del preparatore', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Analitico', 'Migliorare coordinazione nel tuffo laterale e presa alta in sospensione.', 'Lancio del pallone dal preparatore lateralmente. Tuffo laterale e presa alta con entrambe le mani.', 10, 1, 2, 'Alta', 3, 'Palloni, coni', 'Variare distanza e direzione del lancio; inserire un leggero rimbalzo prima del tuffo.', 'Spinta decisa con la gamba opposta; braccia tese; presa sopra la testa; pollici vicini; occhi sulla palla.', 'Spingere con la gamba sbagliata; estensione incompleta; mani morbide o presa davanti al viso.', true, 'Lancio del pallone dal preparatore lateralmente.', 'Tuffo laterale e presa alta con entrambe le mani.', null, null, null, null),
  ('GK-PRA-006', 'Presa alta in tuffo frontale', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Analitico', 'Migliorare reattività, tecnica di presa alta e spinta in elevazione.', 'Lancio frontale del pallone da parte del partner. Tuffo frontale e presa alta del pallone con entrambe le mani.', 8, 1, 2, 'Alta', 3, 'Palloni, coni', 'Variare distanza, potenza e direzione del lancio; alternare lanci tesi e lob.', 'Spinta esplosiva; braccia tese; occhi sul pallone; afferrare sopra la testa; atterrare in equilibrio.', 'Spinta insufficiente; lettura tardiva; braccia piegate; atterraggio sbilanciato.', true, 'Lancio frontale del pallone da parte del partner.', 'Tuffo frontale e presa alta del pallone con entrambe le mani.', null, null, null, null),
  ('GK-PRA-007', 'Presa alta su palla arretrata', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Migliorare tempo di reazione, coordinazione e presa alta su lanci arretrati.', 'Lancio della palla dal preparatore su traiettoria arretrata. Spinta, salto e presa alta della palla sopra la testa.', 8, 1, 2, 'Alta', 3, 'Palloni, coni', 'Variare traiettoria e altezza; alternare lanci tesi e lob.', 'Spinta decisa; braccia tese; presa sopra la testa; pollici vicini; occhi sempre sul pallone.', 'Partire in ritardo; spinta debole; braccia piegate; estensione incompleta.', true, 'Lancio della palla dal preparatore su traiettoria arretrata.', 'Spinta, salto e presa alta della palla sopra la testa.', null, null, null, null),
  ('GK-PRA-008', 'Presa alta in uscita', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Migliorare la tempistica dell''uscita alta e la presa sicura del pallone in elevazione.', 'Lancio alto e profondo del partner verso l''area. Uscita in elevazione e presa alta del pallone con entrambe le mani.', 8, 1, 1, 'Alta', 3, 'Palloni, coni', 'Variare profondità e traiettoria del lancio; inserire rimbalzi prima della presa.', 'Uscita decisa e veloce; braccia tese; presa sopra la testa; ginocchio in spinta; atterraggio equilibrato.', 'Uscire in ritardo; braccia piegate; occhi non fissi sul pallone; piedi disallineati in atterraggio.', true, 'Lancio alto e profondo del partner verso l''area.', 'Uscita in elevazione e presa alta del pallone con entrambe le mani.', null, null, null, null),
  ('GK-PRA-009', 'Presa alta in uscita con ostacolo', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Migliorare l''uscita in elevazione superando un ostacolo e la presa alta del pallone.', 'Lancio alto del pallone da parte del partner oltre l''ostacolo. Uscita in elevazione superando l''ostacolo e presa alta con entrambe le mani.', 10, 1, 1, 'Alta', 3, 'Palloni, coni, paletti o ostacoli', 'Variare altezza e distanza del lancio; inserire più ostacoli; lancio da posizione laterale.', 'Spinta decisa; braccia tese; presa sopra la testa; ginocchio in spinta; atterraggio equilibrato.', 'Uscire in ritardo; non superare l''ostacolo; braccia piegate; elevazione insufficiente; atterraggio sbilanciato.', true, 'Lancio alto del pallone da parte del partner oltre l''ostacolo.', 'Uscita in elevazione superando l''ostacolo e presa alta con entrambe le mani.', null, null, null, null),
  ('GK-PRA-010', 'Presa alta in tuffo laterale', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Migliorare copertura laterale in elevazione e presa alta del pallone in tuffo.', 'Lancio alto e laterale del pallone da parte del partner. Tuffo laterale con presa alta del pallone con entrambe le mani.', 8, 1, 2, 'Alta', 3, 'Palloni, coni', 'Variare altezza e direzione del lancio; alternare destra e sinistra.', 'Spinta esplosiva della gamba opposta; braccia tese; presa sopra la testa; atterraggio su spalla e fianco; occhi sul pallone.', 'Partire in ritardo; non coprire la distanza; piegare le braccia; guardare via dal pallone; atterrare con braccia tese.', true, 'Lancio alto e laterale del pallone da parte del partner.', 'Tuffo laterale con presa alta del pallone con entrambe le mani.', null, null, null, null),
  ('GK-PRA-011', 'Presa alta in tuffo diagonale', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Migliorare l''intervento in elevazione con tuffo diagonale e presa alta in situazioni dinamiche.', 'Lancio alto e diagonale del pallone da parte del partner. Tuffo diagonale, estensione completa e presa alta con entrambe le mani.', 8, 1, 2, 'Alta', 3, 'Palloni, coni', 'Variare direzione e altezza del lancio; alternare lanci tesi e lob.', 'Spinta esplosiva della gamba opposta; braccia tese; corpo allungato sulla traiettoria; presa alta; atterraggio su spalla e fianco.', 'Partire tardi; non coprire la diagonale; piegare le braccia; perdere il pallone; atterrare su mani o gomito.', true, 'Lancio alto e diagonale del pallone da parte del partner.', 'Tuffo diagonale, estensione completa e presa alta con entrambe le mani.', null, null, null, null),
  ('GK-PRA-012', 'Presa alta in tuffo in avanti', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Migliorare l''intervento in avanti in elevazione e la presa alta del pallone lontano dal corpo.', 'Lancio alto del pallone da parte del partner. Tuffo in avanti e presa alta del pallone con entrambe le mani.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo', 'Variare distanza e altezza; inserire ostacolo basso da superare.', 'Spinta esplosiva; braccia tese; presa sopra la testa; corpo in estensione completa; atterraggio su petto e spalle.', 'Uscire in ritardo; non estendersi; piegare le braccia; portare il pallone verso il corpo; atterrare su gomiti o mani.', true, 'Lancio alto del pallone da parte del partner.', 'Tuffo in avanti e presa alta del pallone con entrambe le mani.', null, null, null, null),
  ('GK-PRA-013', 'Presa alta in tuffo indietro', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Migliorare la presa alta in tuffo indietro gestendo coordinazione ed estensione del corpo.', 'Lancio alto del pallone da parte del partner. Tuffo indietro e presa alta del pallone con entrambe le mani.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo', 'Variare distanza e altezza; inserire ostacolo basso da superare.', 'Spinta esplosiva della gamba opposta; braccia tese; presa sopra la testa; arco del corpo; atterraggio su schiena e spalle.', 'Uscire in ritardo; estensione incompleta; braccia piegate; perdere il pallone dietro la testa; atterrare su gomiti o mani.', true, 'Lancio alto del pallone da parte del partner.', 'Tuffo indietro e presa alta del pallone con entrambe le mani.', null, null, null, null),
  ('GK-PRA-014', 'Presa alta in tuffo a gomito', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Migliorare la tecnica di presa alta in tuffo con corretta chiusura a gomito, aumentando sicurezza e stabilità.', 'Lancio alto del pallone da parte del partner. Tuffo a gomito e presa alta del pallone con entrambe le mani.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo', 'Variare direzione del lancio; aggiungere ostacolo basso; aumentare leggermente la velocità.', 'Spinta esplosiva; braccia tese; chiusura a gomito per bloccare; presa sopra la testa; corpo allungato; atterraggio su fianco o spalla.', 'Uscire in ritardo; non chiudere a gomito; piegare le braccia; lasciare spazio tra mani e pallone; atterrare su mani o gomiti.', true, 'Lancio alto del pallone da parte del partner.', 'Tuffo a gomito e presa alta del pallone con entrambe le mani.', null, null, null, null),
  ('GK-PRA-015', 'Presa alta in tuffo a destra', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Migliorare l''intervento in elevazione verso destra con presa alta, coordinazione, estensione e sicurezza.', 'Lancio alto del pallone da parte del partner. Tuffo a destra e presa alta del pallone con entrambe le mani.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo', 'Variare distanza e altezza; inserire ostacolo basso; aumentare leggermente la velocità.', 'Spinta esplosiva della gamba opposta; braccia tese; presa sopra la testa; corpo allungato; atterraggio su fianco o spalla destra.', 'Uscire in ritardo; non spingere lateralmente; piegare le braccia; occhi non fissi; atterrare su mani o gomito.', true, 'Lancio alto del pallone da parte del partner.', 'Tuffo a destra e presa alta del pallone con entrambe le mani.', null, null, null, null),
  ('GK-PRA-016', 'Presa alta in tuffo basso', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Allenare la presa alta del pallone in tuffo verso il basso, migliorando reattività, coordinazione e sicurezza.', 'Lancio alto del pallone da parte del partner. Tuffo basso e presa alta del pallone con entrambe le mani.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo', 'Variare distanza e altezza; inserire ostacolo basso; aumentare leggermente la velocità.', 'Spinta esplosiva della gamba opposta; braccia tese; presa sopra la testa; corpo allungato verso il pallone; atterraggio su fianco o spalla.', 'Uscire in ritardo; piegare le braccia; occhi non fissi; atterrare su mani o gomito.', true, 'Lancio alto del pallone da parte del partner.', 'Tuffo basso e presa alta del pallone con entrambe le mani.', null, null, null, null),
  ('GK-PRA-017', 'Presa alta in tuffo frontale', 'Tecnica presa alta e rasoterra', 'Presa alta', 'Disturbo', 'Migliorare la presa alta del pallone in tuffo frontale, curando reattività, coordinazione e sicurezza nell''intervento.', 'Lancio alto del pallone da parte del partner. Tuffo frontale, presa alta del pallone con entrambe le mani.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare l''altezza e la distanza del lancio. Inserire ostacolo basso da superare prima dell''intervento.', 'Spinta esplosiva in avanti; braccia tese verso il pallone; presa sopra la testa, pollici vicini; corpo allungato in estensione completa; atterraggio su petto e spalle.', 'Uscire in ritardo; non estendersi completamente; piegare le braccia in presa; perdere il pallone sopra la testa; atterrare su mani o gomiti.', true, 'Lancio alto del pallone da parte del partner.', 'Tuffo frontale, presa alta del pallone con entrambe le mani.', null, null, null, null),
  ('GK-PRA-018', 'Presa bassa in tuffo frontale', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare la tecnica di presa bassa in tuffo frontale, aumentando reattività, coordinazione e sicurezza nell''intervento.', 'Passaggio rasoterra da parte del partner. Tuffo frontale basso, presa del pallone con entrambe le mani.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare la distanza e la velocità del passaggio. Inserire ostacolo basso da superare prima dell''intervento.', 'Partenza in posizione pronta; spinta esplosiva in avanti; mani aperte e dita rivolte verso il pallone; presa sicura con entrambe le mani; corpo dietro il pallone; atterraggio su petto e spalle.', 'Uscire in ritardo; piegare le braccia; occhi non fissi sul pallone; mani ravvicinate o rigide; atterrare su gomiti o mani.', true, 'Passaggio rasoterra da parte del partner.', 'Tuffo frontale basso, presa del pallone con entrambe le mani.', null, null, null, null),
  ('GK-PRA-019', 'Deviazione in tuffo frontale', 'Tecnica presa alta e rasoterra', 'Deviazione', 'Disturbo', 'Migliorare la capacità di deviare il pallone in tuffo frontale, aumentando reattività, coordinazione e protezione della porta.', 'Il partner effettua un passaggio rasoterra verso il centro o leggermente decentrato rispetto alla posizione del portiere. Il portiere si tuffa frontalmente e devia il pallone con entrambe le mani, allontanandolo dalla porta.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare la traiettoria del passaggio (centrale, destra, sinistra). Cambiare la velocità del lancio. Inserire un ostacolo davanti al portiere.', 'Partenza in posizione pronta; spinta esplosiva verso il pallone; mani aperte; deviazione con entrambe le mani; occhi sempre sul pallone; corpo allungato a copertura della porta; atterraggio su spalla e fianchi.', 'Uscire in ritardo; mani rigide o non aperte; occhi non fissati sul pallone; deviare centralmente; atterrare su gomiti o mani tese.', true, 'Il partner effettua un passaggio rasoterra verso il centro o leggermente decentrato rispetto alla posizione del portiere.', 'Il portiere si tuffa frontalmente e devia il pallone con entrambe le mani, allontanandolo dalla porta.', null, null, null, null),
  ('GK-PRA-020', 'Presa bassa in tuffo laterale', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare la presa bassa in tuffo laterale, la reattività, la coordinazione e la sicurezza nell’intervento, andando vicino al terreno.', 'Il partner effettua un passaggio rasoterra verso uno dei lati della porta. Il portiere si sposta lateralmente e si tuffa basso, bloccando il pallone con entrambe le mani vicino al terreno.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Lanciare da destra e sinistra. Variare distanza e velocità. Inserire ostacolo basso da superare prima dell’intervento. Passaggio leggermente più lontano dal portiere.', 'Partenza in posizione pronta; spinta esplosiva laterale; corpo allungato e copertura della palla; mani aperte; presa sicura vicino al terreno; atterraggio su fianco e spalla.', 'Uscire in ritardo; piegare il braccio di presa; occhi non fissi; non andare vicino al terreno; atterrare su gomiti o mani tese.', true, 'Il partner effettua un passaggio rasoterra verso uno dei lati della porta.', 'Il portiere si sposta lateralmente e si tuffa basso, bloccando il pallone con entrambe le mani vicino al terreno.', null, null, null, null),
  ('GK-PRA-021', 'Tuffo basso laterale in appoggio', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare la tecnica del tuffo basso laterale in appoggio, aumentando reattività, capacità di copertura del lato e sicurezza nella presa a terra.', 'Il partner effettua un passaggio rasoterra verso destra o sinistra del portiere. Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare il lato del passaggio, la distanza dal portiere e inserire un ostacolo basso da superare prima dell’intervento.', 'Partenza pronta; spinta esplosiva verso il lato; mani aperte; presa bassa sicura; appoggio su fianco e avambraccio; corpo dietro il pallone; atterraggio controllato e protezione della palla.', 'Uscire in ritardo; mani rigide; occhi non fissi; non portare il corpo dietro il pallone; atterrare su gomito o spalla; lasciare rimbalzare il pallone.', true, 'Il partner effettua un passaggio rasoterra verso destra o sinistra del portiere.', 'Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', null, null, null, null),
  ('GK-PRA-022', 'Tuffo basso laterale in spinta', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare la tecnica del tuffo basso laterale in spinta, aumentando reattività, rapidità d’intervento e sicurezza nella presa a terra.', 'Il partner effettua un passaggio rasoterra forte verso il lato del portiere. Il portiere effettua un tuffo basso laterale in spinta, afferra il pallone con entrambe le mani e lo protegge.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare lato, distanza e velocità del passaggio. Inserire un ostacolo basso da superare prima dell’intervento.', 'Partenza pronta; spinta esplosiva verso il lato; mani aperte; presa bassa sicura; spinta laterale con gamba interna; corpo dietro il pallone; atterraggio su fianco e spalla.', 'Uscire in ritardo; mani rigide; occhi non fissi; non spingere lateralmente; atterrare su gomito o mani tese; lasciare rimbalzare il pallone.', true, 'Il partner effettua un passaggio rasoterra forte verso il lato del portiere.', 'Il portiere effettua un tuffo basso laterale in spinta, afferra il pallone con entrambe le mani e lo protegge.', null, null, null, null),
  ('GK-PRA-023', 'Tuffo basso laterale in appoggio con ripartenza', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso laterale in appoggio, presa sicura e rapidità di ripartenza verso la posizione di guardia.', 'Il partner effettua un passaggio rasoterra verso il lato del portiere. Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge. Il portiere si rialza rapidamente e ritorna in posizione di guardia.', 10, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare lato e distanza del passaggio. Inserire ostacolo basso. Aggiungere uno stimolo visivo o sonoro prima del passaggio.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; appoggio su fianco e avambraccio; corpo dietro la palla; occhi sul pallone; ripartenza immediata verso la guardia.', 'Uscire in ritardo; mani rigide; occhi non fissi; non proteggere il pallone; non ripartire rapidamente; atterrare su gomito o spalla; lasciare rimbalzare il pallone.', true, 'Il partner effettua un passaggio rasoterra verso il lato del portiere.', 'Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere si rialza rapidamente e ritorna in posizione di guardia.', null, null, null),
  ('GK-PRA-024', 'Tuffo basso laterale in appoggio con ripartenza', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare la tecnica del tuffo basso laterale in appoggio, la presa sicura del pallone e la rapidità di ripartenza verso la posizione di guardia.', 'Il partner effettua un passaggio rasoterra verso il lato del portiere. Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge. Il portiere si rialza rapidamente e ritorna in posizione di guardia.', 10, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare lato e distanza del passaggio. Inserire ostacolo basso. Aggiungere uno stimolo visivo o sonoro prima del passaggio.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; appoggio su fianco e avambraccio; corpo dietro la palla; occhi sul pallone; ripartenza immediata con ritorno in guardia.', 'Uscire in ritardo; mani rigide; occhi non fissi; non proteggere il pallone; ripartenza lenta; atterrare su gomito o spalla; lasciare rimbalzare il pallone.', true, 'Il partner effettua un passaggio rasoterra verso il lato del portiere.', 'Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere si rialza rapidamente e ritorna in posizione di guardia.', null, null, null),
  ('GK-PRA-025', 'Tuffo basso laterale in appoggio con passaggio di ritorno', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso laterale in appoggio, presa sicura, rapidità d’intervento e accuratezza nel passaggio di ritorno.', 'Il partner effettua un passaggio rasoterra verso il lato del portiere. Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge. Il portiere esegue un passaggio di ritorno rasoterra preciso verso il partner.', 10, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare lato e distanza del passaggio. Inserire ostacolo basso prima dell’intervento.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; appoggio su fianco e avambraccio; corpo dietro la palla; occhi sul pallone; passaggio di ritorno rasoterra preciso e forte.', 'Uscire in ritardo; mani rigide; occhi non fissi; non proteggere il pallone; non ripartire rapidamente; passaggio di ritorno impreciso o lento; lasciare rimbalzare il pallone.', true, 'Il partner effettua un passaggio rasoterra verso il lato del portiere.', 'Il portiere effettua un tuffo basso laterale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere esegue un passaggio di ritorno rasoterra preciso verso il partner.', null, null, null),
  ('GK-PRA-026', 'Tuffo basso frontale in appoggio', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare la tecnica del tuffo basso frontale in appoggio, curando presa sicura e rapidità d’intervento dal centro della porta.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale in appoggio, afferra il pallone con entrambe le mani e lo protegge. Il portiere si rialza rapidamente e ritorna in posizione di guardia.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare distanza del passaggio. Inserire ostacolo basso da superare. Alternare passaggi veloci e lenti.', 'Partenza pronta; spinta esplosiva in avanti; mani aperte; occhi sul pallone; corpo dietro la palla; presa sicura; appoggio su avambracci e pettorali; protezione al petto; ripartenza immediata.', 'Uscire in ritardo; mani rigide; occhi non fissi; non portare il corpo dietro il pallone; atterrare su gomito o spalla; non proteggere il pallone; ripartenza lenta.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale in appoggio, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere si rialza rapidamente e ritorna in posizione di guardia.', null, null, null),
  ('GK-PRA-027', 'Tuffo basso frontale con ripartenza', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso frontale in presa, sicurezza del pallone e rapidità di ripartenza verso la posizione di guardia.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge. Il portiere si rialza rapidamente e ritorna in posizione di guardia.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare velocità e direzione del passaggio. Inserire ostacolo basso. Alternare rasoterra e palloni leggermente rimbalzati.', 'Partenza pronta; spinta esplosiva in avanti; mani aperte; tuffo frontale con corpo dietro il pallone; presa sicura; protezione al petto; occhi sul pallone; ripartenza immediata e comunicazione.', 'Uscire in ritardo; mani rigide; occhi non fissi; corpo non dietro la palla; non proteggere; restare a terra troppo; ripartenza lenta o con passi incrociati.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere si rialza rapidamente e ritorna in posizione di guardia.', null, null, null),
  ('GK-PRA-028', 'Tuffo basso frontale con passaggio di ritorno', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso frontale in presa, sicurezza del pallone e rapidità d’intervento, con successivo passaggio di ritorno preciso e rasoterra.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge. Il portiere effettua un passaggio di ritorno rasoterra verso il partner.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare distanza del partner; inserire ostacolo basso; alternare rasoterra centrali e decentrati; aumentare velocità.', 'Partenza pronta; spinta esplosiva; mani aperte; corpo dietro la palla; presa sicura; protezione al petto; passaggio di ritorno preciso e forte; occhi sul pallone e comunicazione.', 'Uscire in ritardo; mani rigide; occhi non fissi; corpo non dietro la palla; atterrare male; non proteggere; passaggio di ritorno lento o impreciso.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere effettua un passaggio di ritorno rasoterra verso il partner.', null, null, null),
  ('GK-PRA-029', 'Tuffo basso frontale con ritorno in porta', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso frontale in presa, sicurezza del pallone e rapidità di recupero con ritorno in porta per mantenere la posizione di guardia.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge. Il portiere effettua un passaggio di ritorno rasoterra verso il partner. Il portiere si rialza rapidamente e rientra in posizione di guardia.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare distanza; inserire uno o due ostacoli bassi; alternare rasoterra centrali e decentrati; aumentare velocità del passaggio in entrata e ritorno.', 'Partenza pronta; spinta esplosiva; mani aperte; corpo dietro la palla; presa sicura; protezione al petto; ritorno rapido in piedi; comunicazione.', 'Uscire in ritardo; mani rigide; occhi non fissi; corpo non dietro la palla; non proteggere; restare a terra troppo; rientro lento; passaggio impreciso.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere effettua un passaggio di ritorno rasoterra verso il partner.', 'Il portiere si rialza rapidamente e rientra in posizione di guardia.', null, null),
  ('GK-PRA-030', 'Tuffo basso frontale con ritorno e ripartenza laterale', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso frontale in presa, sicurezza, rapidità di ritorno e capacità di ripartenza laterale per mantenere la posizione di guardia.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge. Il portiere ritorna rapidamente in piedi. Il portiere riparte lateralmente e rientra in posizione di guardia.', 8, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare distanza; inserire ostacoli bassi; alternare rasoterra centrali e decentrati; eseguire la ripartenza a destra e sinistra.', 'Partenza pronta; spinta esplosiva; mani aperte; corpo dietro la palla; presa sicura; protezione; ritorno rapido in piedi; ripartenza laterale bassa e veloce; occhi sul pallone.', 'Uscire in ritardo; mani rigide; occhi non fissi; corpo non dietro la palla; non proteggere; restare a terra; ripartenza lenta o incrociata; rientrare troppo alti.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone con entrambe le mani e lo protegge.', 'Il portiere ritorna rapidamente in piedi.', 'Il portiere riparte lateralmente e rientra in posizione di guardia.', null, null),
  ('GK-PRA-031', 'Tuffo basso frontale con ritorno, ripartenza e reazione', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso frontale in presa, velocità di ritorno in guardia e capacità di reagire a un nuovo stimolo mantenendo qualità tecnica.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge. Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia. Il partner invia un nuovo passaggio o stimolo e il portiere reagisce con un nuovo intervento.', 10, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, sagoma', 'Variare distanza e velocità; inserire ostacoli; alternare passaggi centrali e laterali; dopo il ritorno chiedere spostamento laterale prima del nuovo stimolo.', 'Partenza pronta e reattiva; spinta esplosiva; mani aperte; presa sicura; protezione al petto; ritorno rapido; ripartenza equilibrata; piedi bassi; comunicazione costante.', 'Uscire in ritardo; mani rigide; occhi non fissi; corpo non dietro; non portare palla al petto; ritorno lento; equilibrio precario; posizione di guardia troppo alta.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il partner invia un nuovo passaggio o stimolo e il portiere reagisce con un nuovo intervento.', null, null),
  ('GK-PRA-032', 'Tuffo basso frontale con ritorno e reazione a stimolo visivo', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso frontale in presa, rapidità di ritorno in guardia e capacità di reagire rapidamente a uno stimolo visivo con un nuovo intervento preciso.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge. Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia. Il partner mostra uno stimolo visivo e invia un nuovo passaggio: il portiere reagisce.', 10, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, manichino, cartoncini colorati o numeri', 'Variare distanza e velocità; inserire ostacoli; alternare passaggi centrali e laterali; utilizzare colori, numeri, forme o combinazioni; alternare stimolo visivo e sonoro.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; protezione; ritorno rapido; occhi attivi sullo stimolo; reazione immediata e comunicazione.', 'Uscire in ritardo; mani rigide; occhi non su palla/stimolo; corpo non dietro; non proteggere; ritorno lento; reazione ritardata; equilibrio precario.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il partner mostra uno stimolo visivo e invia un nuovo passaggio: il portiere reagisce.', null, null),
  ('GK-PRA-033', 'Tuffo basso frontale con ritorno, ripartenza, reazione e secondo stimolo', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso frontale in presa, ritorno in guardia e capacità di reagire rapidamente a un secondo stimolo visivo e a un nuovo intervento.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge. Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia. Il partner effettua un secondo passaggio rasoterra: il portiere reagisce e prende il pallone. Il partner mostra un secondo stimolo visivo e il portiere reagisce effettuando un nuovo passaggio/intervento.', 12, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, manichino, cartoncini colorati o numeri', 'Variare distanza e velocità; inserire ostacoli; alternare passaggi centrali e laterali; utilizzare colori, numeri, forme o combinazioni; alternare stimolo sonoro.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; protezione; ritorno rapido; occhi sempre attivi; reazione immediata; comunicazione.', 'Uscire in ritardo; mani rigide; occhi non su palla/stimolo; corpo non dietro; non proteggere; ritorno lento; reazione ritardata; equilibrio precario.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il partner effettua un secondo passaggio rasoterra: il portiere reagisce e prende il pallone.', 'Il partner mostra un secondo stimolo visivo e il portiere reagisce effettuando un nuovo passaggio/intervento.', null),
  ('GK-PRA-034', 'Tuffo basso frontale con ritorno, ripartenza e stimolo sonoro', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso frontale in presa, velocità di ritorno in guardia e capacità di reagire rapidamente a uno stimolo sonoro e a un nuovo intervento.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge. Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia. Il portiere attende in guardia lo stimolo sonoro. Alla ricezione dello stimolo sonoro, il partner effettua un secondo passaggio e il portiere reagisce con un nuovo intervento.', 12, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, manichino, speaker portatile per stimolo sonoro', 'Variare distanza e velocità; inserire ostacoli; alternare passaggi; utilizzare fischio, clap, bip o musica; alternare stimolo sonoro e visivo.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; protezione; ritorno rapido; mantenere sguardo avanti e ascolto attivo; reazione immediata; comunicazione.', 'Uscire in ritardo; mani rigide; occhi non sul pallone; corpo non dietro; non proteggere; ritorno lento; reazione ritardata allo stimolo; equilibrio precario.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il portiere attende in guardia lo stimolo sonoro.', 'Alla ricezione dello stimolo sonoro, il partner effettua un secondo passaggio e il portiere reagisce con un nuovo intervento.', null),
  ('GK-PRA-035', 'Tuffo basso frontale con ritorno, ripartenza e giocata finale', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso frontale in presa, rapidità di ritorno in guardia, capacità di ripartenza e reattività su una seconda giocata.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge. Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia. Il portiere si riposiziona lateralmente per la seconda giocata. Il partner effettua una seconda giocata e il portiere interviene.', 14, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, mini porta, sagoma', 'Variare distanza e velocità; inserire ostacoli; alternare passaggio rasoterra e tiro; inserire finta del partner prima della seconda giocata.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; protezione; ritorno rapido; ripartenza bassa ed equilibrata; lettura della giocata finale; comunicazione.', 'Uscire in ritardo; mani rigide; occhi non sul pallone; corpo non dietro; non proteggere; ritorno lento; ripartenza laterale lunga; reazione tardiva sulla giocata finale.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il portiere si riposiziona lateralmente per la seconda giocata.', 'Il partner effettua una seconda giocata e il portiere interviene.', null),
  ('GK-PRA-036', 'Tuffo basso frontale con ritorno, ripartenza e stimolo visivo + sonoro', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare tuffo basso frontale in presa, reattività a stimoli visivi e sonori, rapidità di ritorno in guardia e reattività sui passaggi successivi.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge. Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia. Il portiere reagisce allo stimolo visivo e a quello sonoro. Il partner effettua un nuovo passaggio rasoterra e il portiere reagisce con un nuovo intervento.', 14, 1, 2, 'Alta', 3, 'Palloni, cono o ostacolo, manichino, cartoncini colorati o numeri, speaker o fischietto', 'Variare distanza e velocità; inserire ostacoli; alternare passaggio rasoterra e tiro; utilizzare colori, numeri, fischi, bip o musica; alternare ordine degli stimoli.', 'Partenza pronta; spinta esplosiva; mani aperte; presa sicura; protezione; ritorno rapido; occhi sempre attivi; reazione entro circa un secondo; comunicazione costante.', 'Uscire in ritardo; mani rigide; occhi non su palla/stimolo; corpo non dietro; non proteggere; ritorno lento; reazione ritardata; equilibrio precario.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale, afferra il pallone e lo protegge.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il portiere reagisce allo stimolo visivo e a quello sonoro.', 'Il partner effettua un nuovo passaggio rasoterra e il portiere reagisce con un nuovo intervento.', null),
  ('GK-PRA-037', 'Tuffo basso frontale con ritorno, ripartenza e gioco combinato', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare la tecnica del tuffo basso frontale in presa, il rapido recupero, la ripartenza e la capacità di collegare un secondo passaggio con una giocata combinata.', 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere. Il portiere esegue un tuffo basso frontale in appoggio e blocca il pallone con entrambe le mani. Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia. Il partner effettua un secondo passaggio rasoterra. Il portiere effettua un passaggio rasoterra verso il partner opposto. Il partner controlla il pallone e conclude rasoterra verso la porta oppure cambia gioco.', 12, 1, 2, 'Alta', 4, 'Palloni, cono o ostacolo, sagoma/manichino, cartoncini colorati o numeri', 'Variare distanza e velocità dei passaggi. Alternare il lato della seconda giocata. Inserire uno stimolo visivo prima del secondo passaggio. Consentire al partner finale di controllare e cambiare gioco oppure concludere rasoterra.', 'Partenza pronta e reattiva; spinta esplosiva in avanti; presa sicura con corpo dietro il pallone; ritorno rapido in piedi; riposizionamento in guardia; qualità del passaggio rasoterra del portiere; lettura della giocata finale; comunicazione costante.', 'Uscire in ritardo; mani rigide; non proteggere il pallone; ritorno lento; perdita dell''orientamento dopo il secondo passaggio; passaggio del portiere impreciso; mancata lettura della giocata finale.', true, 'Il partner effettua un passaggio rasoterra frontalmente verso il portiere.', 'Il portiere esegue un tuffo basso frontale in appoggio e blocca il pallone con entrambe le mani.', 'Il portiere ritorna rapidamente in piedi e riparte verso la posizione di guardia.', 'Il partner effettua un secondo passaggio rasoterra.', 'Il portiere effettua un passaggio rasoterra verso il partner opposto.', 'Il partner controlla il pallone e conclude rasoterra verso la porta oppure cambia gioco.'),
  ('GK-PRA-038', 'Tuffo basso laterale con spinta + ritorno', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Migliorare la tecnica del tuffo basso laterale in presa, la spinta della gamba opposta, la rapidità di recupero e il ritorno in posizione di guardia per un nuovo intervento.', 'Il partner effettua un passaggio rasoterra lateralmente verso il portiere. Il portiere effettua un tuffo basso laterale, spingendo con la gamba opposta e prende il pallone. Recupera subito il pallone e si porta in posizione eretta su un ginocchio. Ritorna rapidamente in piedi e assume la posizione di guardia. Il partner effettua un passaggio rasoterra dal lato opposto e il portiere ripete il lavoro.', 10, 1, 2, 'Alta', 4, 'Palloni, coni o ostacoli opzionali', 'Variare distanza e velocità dei passaggi. Lavorare su un solo lato o alternare i lati. Inserire ostacoli bassi prima del passaggio. Utilizzare stimoli visivi diversi.', 'Partenza pronta e reattiva; spinta esplosiva della gamba opposta; mano esterna a protezione e presa con entrambe le mani; corpo dietro il pallone; recupero immediato vicino al petto; ritorno rapido in piedi; equilibrio centrale; reazione immediata al nuovo passaggio.', 'Spinta insufficiente o tardiva; mani lente o mal posizionate; corpo davanti al pallone; recupero instabile; ritorno lento o con passi incrociati; disattenzione sul nuovo passaggio.', true, 'Il partner effettua un passaggio rasoterra lateralmente verso il portiere.', 'Il portiere effettua un tuffo basso laterale, spingendo con la gamba opposta e prende il pallone.', 'Recupera subito il pallone e si porta in posizione eretta su un ginocchio.', 'Ritorna rapidamente in piedi e assume la posizione di guardia.', 'Il partner effettua un passaggio rasoterra dal lato opposto e il portiere ripete il lavoro.', null),
  ('GK-PRA-039', 'Tuffo basso in avanti + spinta e ritorno', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Sviluppare la capacità di tuffo basso in avanti per la presa, la velocità di reazione e l''esplosività nella risalita in piedi mantenendo alta l''intensità.', 'Il partner effettua un passaggio rasoterra frontalmente. Il portiere esegue un tuffo basso in avanti e prende il pallone a terra. Spinge con le mani in modo esplosivo e torna rapidamente in piedi. Il portiere rientra in posizione di guardia e si prepara al passaggio successivo. Il partner effettua un secondo passaggio rasoterra.', 10, 1, 2, 'Alta', 4, 'Palloni, coni o ostacoli opzionali', 'Aumentare la distanza del passaggio. Inserire uno o due ostacoli prima del tuffo. Partire già in posizione di ginocchio. Utilizzare stimoli visivi diversi.', 'Partenza pronta e reattiva; tuffo in avanti con presa sicura; mani aperte verso il pallone; corpo dietro il pallone; spinta esplosiva con le mani e appoggio deciso dei piedi; ritorno rapido con passi brevi; equilibrio centrale; reazione immediata al passaggio successivo.', 'Ritardo nella partenza; tuffo corto o presa incompleta; mani troppo vicine; spinta debole con le mani; risalita lenta o con passi incrociati; corpo non dietro il pallone; perdita di equilibrio.', true, 'Il partner effettua un passaggio rasoterra frontalmente.', 'Il portiere esegue un tuffo basso in avanti e prende il pallone a terra.', 'Spinge con le mani in modo esplosivo e torna rapidamente in piedi.', 'Il portiere rientra in posizione di guardia e si prepara al passaggio successivo.', 'Il partner effettua un secondo passaggio rasoterra.', null),
  ('GK-PRA-040', 'Combinazione bassa + alta con due partner', 'Tecnica presa alta e rasoterra', 'Presa rasoterra', 'Disturbo', 'Sviluppare la capacità di gestire in rapida successione una presa bassa e una presa alta, migliorando reattività, transizione e sicurezza negli interventi e nei recuperi.', 'Il primo partner effettua un passaggio rasoterra al portiere. Il portiere esegue un tuffo basso e blocca il pallone a terra. Si rialza rapidamente e si posiziona al centro della porta. Il secondo partner effettua un passaggio alto al portiere. Il portiere salta, prende il pallone in elevazione e ritorna in posizione di guardia.', 12, 1, 2, 'Alta', 4, 'Palloni, coni o ostacoli opzionali', 'Invertire l''ordine: prima alta poi bassa. Aumentare la distanza dei passaggi. Inserire un ostacolo tra i due passaggi. Utilizzare stimoli visivi differenti.', 'Partenza pronta e reattiva; tuffo basso con presa sicura; recupero esplosivo in piedi; posizionamento rapido per la seconda giocata; salto verticale e presa alta sicura; atterraggio stabile; ritorno in posizione di guardia; massima concentrazione.', 'Ritardo sulla prima o seconda giocata; tuffo basso indeciso; recupero lento o non equilibrato; salto senza spinta efficace; mani non corrette nella presa alta; atterraggio instabile o ritorno con passi incrociati.', true, 'Il primo partner effettua un passaggio rasoterra al portiere.', 'Il portiere esegue un tuffo basso e blocca il pallone a terra.', 'Si rialza rapidamente e si posiziona al centro della porta.', 'Il secondo partner effettua un passaggio alto al portiere.', 'Il portiere salta, prende il pallone in elevazione e ritorna in posizione di guardia.', null)
)
insert into public.exercises (
  codice, nome, category_id, subcategory_id, categoria, sottocategoria, fase,
  obiettivo, descrizione, durata_min, portieri_min, portieri_max, intensita,
  difficolta, materiale, variante, coaching_points, errori_comuni, attivo,
  schema_step_1, schema_step_2, schema_step_3, schema_step_4, schema_step_5, schema_step_6
)
select
  o.codice, o.nome, 1, s.id, o.categoria, o.sottocategoria, o.fase,
  o.obiettivo, o.descrizione, o.durata_min, o.portieri_min, o.portieri_max, o.intensita,
  o.difficolta, o.materiale, o.variante, o.coaching_points, o.errori_comuni, o.attivo,
  o.schema_step_1, o.schema_step_2, o.schema_step_3, o.schema_step_4, o.schema_step_5, o.schema_step_6
from official o
join public.exercise_subcategories s
  on s.category_id = 1
 and s.nome = o.sottocategoria
 and s.fase = o.fase
on conflict (codice) do update set
  nome = excluded.nome,
  category_id = excluded.category_id,
  subcategory_id = excluded.subcategory_id,
  categoria = excluded.categoria,
  sottocategoria = excluded.sottocategoria,
  fase = excluded.fase,
  obiettivo = excluded.obiettivo,
  descrizione = excluded.descrizione,
  durata_min = excluded.durata_min,
  portieri_min = excluded.portieri_min,
  portieri_max = excluded.portieri_max,
  intensita = excluded.intensita,
  difficolta = excluded.difficolta,
  materiale = excluded.materiale,
  variante = excluded.variante,
  coaching_points = excluded.coaching_points,
  errori_comuni = excluded.errori_comuni,
  attivo = excluded.attivo,
  schema_step_1 = excluded.schema_step_1,
  schema_step_2 = excluded.schema_step_2,
  schema_step_3 = excluded.schema_step_3,
  schema_step_4 = excluded.schema_step_4,
  schema_step_5 = excluded.schema_step_5,
  schema_step_6 = excluded.schema_step_6;

commit;
